export type WordSeedDifficulty = 'easy' | 'medium' | 'hard';
export type WordSeedLanguage = 'es' | 'en';

export interface WordCompletionWordSeed {
  word: string;
  difficulty: WordSeedDifficulty;
  language?: WordSeedLanguage;
}

export const WORD_COMPLETION_WORDS_SEED: WordCompletionWordSeed[] = [
  { word: 'CASA', difficulty: 'easy' },
  { word: 'MESA', difficulty: 'easy' },
  { word: 'GATO', difficulty: 'easy' },
  { word: 'PATO', difficulty: 'easy' },
  { word: 'LUNA', difficulty: 'easy' },
  { word: 'ROSA', difficulty: 'easy' },
  { word: 'AGUA', difficulty: 'easy' },
  { word: 'BOCA', difficulty: 'easy' },
  { word: 'ROPA', difficulty: 'easy' },
  { word: 'DEDO', difficulty: 'easy' },
  { word: 'PELO', difficulty: 'easy' },
  { word: 'MANO', difficulty: 'easy' },
  { word: 'NUBE', difficulty: 'easy' },
  { word: 'TREN', difficulty: 'easy' },
  { word: 'PISO', difficulty: 'easy' },
  { word: 'FLOR', difficulty: 'easy' },
  { word: 'SOL', difficulty: 'easy' },
  { word: 'MAR', difficulty: 'easy' },
  { word: 'PAN', difficulty: 'easy' },
  { word: 'LUZ', difficulty: 'easy' },
  { word: 'PEZ', difficulty: 'easy' },
  { word: 'RÍO', difficulty: 'easy' },
  { word: 'OSO', difficulty: 'easy' },
  { word: 'AVE', difficulty: 'easy' },
  { word: 'CAMA', difficulty: 'easy' },
  { word: 'SOPA', difficulty: 'easy' },
  { word: 'VASO', difficulty: 'easy' },
  { word: 'LAGO', difficulty: 'easy' },
  { word: 'HOJA', difficulty: 'easy' },
  { word: 'PERA', difficulty: 'easy' },
  { word: 'RANA', difficulty: 'easy' },
  { word: 'FOCA', difficulty: 'easy' },
  { word: 'LOBO', difficulty: 'easy' },
  { word: 'MONO', difficulty: 'easy' },
  { word: 'CARRO', difficulty: 'easy' },
  { word: 'LIBRO', difficulty: 'easy' },

  { word: 'MURCIÉLAGO', difficulty: 'medium' },
  { word: 'MARIPOSA', difficulty: 'medium' },
  { word: 'TELESCOPIO', difficulty: 'medium' },
  { word: 'BIBLIOTECA', difficulty: 'medium' },
  { word: 'DINOSAURIO', difficulty: 'medium' },
  { word: 'HIPOPÓTAMO', difficulty: 'medium' },
  { word: 'LABORATORIO', difficulty: 'medium' },
  { word: 'PERIÓDICO', difficulty: 'medium' },
  { word: 'CHOCOLATINA', difficulty: 'medium' },
  { word: 'ELECTRÓNICO', difficulty: 'medium' },
  { word: 'METEOROLOGÍA', difficulty: 'medium' },
  { word: 'ARQUITECTURA', difficulty: 'medium' },
  { word: 'CARPINTERO', difficulty: 'medium' },
  { word: 'ZAPATERÍA', difficulty: 'medium' },
  { word: 'PANADERÍA', difficulty: 'medium' },
  { word: 'VENTILADOR', difficulty: 'medium' },
  { word: 'COMPUTADORA', difficulty: 'medium' },
  { word: 'TELEVISOR', difficulty: 'medium' },
  { word: 'CALENDARIO', difficulty: 'medium' },
  { word: 'CUADERNO', difficulty: 'medium' },
  { word: 'MOCHILA', difficulty: 'medium' },
  { word: 'ESCUELA', difficulty: 'medium' },
  { word: 'HOSPITAL', difficulty: 'medium' },
  { word: 'AMBULANCIA', difficulty: 'medium' },
  { word: 'BICICLETA', difficulty: 'medium' },
  { word: 'CARRETERA', difficulty: 'medium' },
  { word: 'MONTAÑA', difficulty: 'medium' },
  { word: 'CASCADA', difficulty: 'medium' },
  { word: 'TORMENTA', difficulty: 'medium' },
  { word: 'RELÁMPAGO', difficulty: 'medium' },
  { word: 'ESTRELLA', difficulty: 'medium' },
  { word: 'PLANETA', difficulty: 'medium' },
  { word: 'SATÉLITE', difficulty: 'medium' },
  { word: 'GALAXIA', difficulty: 'medium' },
  { word: 'PIRÁMIDE', difficulty: 'medium' },
  { word: 'CASTILLO', difficulty: 'medium' },
  { word: 'AVENTURA', difficulty: 'medium' },
  { word: 'MISTERIO', difficulty: 'medium' },
  { word: 'CANGREJO', difficulty: 'medium' },
  { word: 'BALLENA', difficulty: 'medium' },
  { word: 'TIBURÓN', difficulty: 'medium' },
  { word: 'PINGÜINO', difficulty: 'medium' },

  { word: 'CRIPTOGRAFÍA', difficulty: 'hard' },
  { word: 'FONOLOGÍA', difficulty: 'hard' },
  { word: 'QUIRÚRGICO', difficulty: 'hard' },
  { word: 'MICROSCOPIO', difficulty: 'hard' },
  { word: 'NEUROLOGÍA', difficulty: 'hard' },
  { word: 'FOTOSÍNTESIS', difficulty: 'hard' },
  { word: 'TERMODINÁMICA', difficulty: 'hard' },
  { word: 'GEOQUÍMICA', difficulty: 'hard' },
  { word: 'ARQUEOLOGÍA', difficulty: 'hard' },
  { word: 'ANTROPOLOGÍA', difficulty: 'hard' },
  { word: 'BIOTECNOLOGÍA', difficulty: 'hard' },
  { word: 'ASTROFÍSICA', difficulty: 'hard' },
  { word: 'OCEANOGRAFÍA', difficulty: 'hard' },
  { word: 'PALEONTOLOGÍA', difficulty: 'hard' },
  { word: 'NEUROCIENCIA', difficulty: 'hard' },
  { word: 'CIBERSEGURIDAD', difficulty: 'hard' },
  { word: 'PROGRAMACIÓN', difficulty: 'hard' },
  { word: 'AUTOMATIZACIÓN', difficulty: 'hard' },
  { word: 'SINCRONIZACIÓN', difficulty: 'hard' },
  { word: 'CONFIGURACIÓN', difficulty: 'hard' },
  { word: 'AUTENTICACIÓN', difficulty: 'hard' },
  { word: 'OPTIMIZACIÓN', difficulty: 'hard' },
  { word: 'VIRTUALIZACIÓN', difficulty: 'hard' },
  { word: 'INFRAESTRUCTURA', difficulty: 'hard' },
  { word: 'INTEROPERABILIDAD', difficulty: 'hard' },
  { word: 'DESCENTRALIZACIÓN', difficulty: 'hard' },
  { word: 'RESPONSABILIDAD', difficulty: 'hard' },
  { word: 'TRANSFORMACIÓN', difficulty: 'hard' },
  { word: 'ADMINISTRACIÓN', difficulty: 'hard' },
  { word: 'CONSTITUCIÓN', difficulty: 'hard' },
  { word: 'INVESTIGACIÓN', difficulty: 'hard' },
  { word: 'EXPERIMENTACIÓN', difficulty: 'hard' },
  { word: 'COMUNICACIÓN', difficulty: 'hard' },
  { word: 'ORGANIZACIÓN', difficulty: 'hard' },
  { word: 'PLANIFICACIÓN', difficulty: 'hard' },
  { word: 'CLASIFICACIÓN', difficulty: 'hard' },
  { word: 'IDENTIFICACIÓN', difficulty: 'hard' },
  { word: 'ELECTROCARDIOGRAMA', difficulty: 'hard' },
  { word: 'PARALELEPÍPEDO', difficulty: 'hard' },
  { word: 'DESOXIRRIBONUCLEICO', difficulty: 'hard' },
  { word: 'HIDROELECTRICIDAD', difficulty: 'hard' },
  { word: 'CONTRAINTELIGENCIA', difficulty: 'hard' },

  { word: 'HOME', difficulty: 'easy', language: 'en' },
  { word: 'TABLE', difficulty: 'easy', language: 'en' },
  { word: 'CAT', difficulty: 'easy', language: 'en' },
  { word: 'DUCK', difficulty: 'easy', language: 'en' },
  { word: 'MOON', difficulty: 'easy', language: 'en' },
  { word: 'ROSE', difficulty: 'easy', language: 'en' },
  { word: 'WATER', difficulty: 'easy', language: 'en' },
  { word: 'MOUTH', difficulty: 'easy', language: 'en' },
  { word: 'CLOTHES', difficulty: 'easy', language: 'en' },
  { word: 'FINGER', difficulty: 'easy', language: 'en' },
  { word: 'HAIR', difficulty: 'easy', language: 'en' },
  { word: 'HAND', difficulty: 'easy', language: 'en' },
  { word: 'CLOUD', difficulty: 'easy', language: 'en' },
  { word: 'TRAIN', difficulty: 'easy', language: 'en' },
  { word: 'FLOOR', difficulty: 'easy', language: 'en' },
  { word: 'FLOWER', difficulty: 'easy', language: 'en' },
  { word: 'SUN', difficulty: 'easy', language: 'en' },
  { word: 'SEA', difficulty: 'easy', language: 'en' },
  { word: 'BREAD', difficulty: 'easy', language: 'en' },
  { word: 'LIGHT', difficulty: 'easy', language: 'en' },
  { word: 'FISH', difficulty: 'easy', language: 'en' },
  { word: 'RIVER', difficulty: 'easy', language: 'en' },
  { word: 'BEAR', difficulty: 'easy', language: 'en' },
  { word: 'BIRD', difficulty: 'easy', language: 'en' },
  { word: 'BED', difficulty: 'easy', language: 'en' },
  { word: 'SOUP', difficulty: 'easy', language: 'en' },
  { word: 'GLASS', difficulty: 'easy', language: 'en' },
  { word: 'LAKE', difficulty: 'easy', language: 'en' },
  { word: 'LEAF', difficulty: 'easy', language: 'en' },
  { word: 'PEAR', difficulty: 'easy', language: 'en' },
  { word: 'FROG', difficulty: 'easy', language: 'en' },
  { word: 'SEAL', difficulty: 'easy', language: 'en' },
  { word: 'WOLF', difficulty: 'easy', language: 'en' },
  { word: 'MONKEY', difficulty: 'easy', language: 'en' },
  { word: 'CAR', difficulty: 'easy', language: 'en' },
  { word: 'BOOK', difficulty: 'easy', language: 'en' },

  { word: 'BUTTERFLY', difficulty: 'medium', language: 'en' },
  { word: 'TELESCOPE', difficulty: 'medium', language: 'en' },
  { word: 'LIBRARY', difficulty: 'medium', language: 'en' },
  { word: 'DINOSAUR', difficulty: 'medium', language: 'en' },
  { word: 'HIPPOPOTAMUS', difficulty: 'medium', language: 'en' },
  { word: 'LABORATORY', difficulty: 'medium', language: 'en' },
  { word: 'NEWSPAPER', difficulty: 'medium', language: 'en' },
  { word: 'CHOCOLATE', difficulty: 'medium', language: 'en' },
  { word: 'ELECTRONIC', difficulty: 'medium', language: 'en' },
  { word: 'METEOROLOGY', difficulty: 'medium', language: 'en' },
  { word: 'ARCHITECTURE', difficulty: 'medium', language: 'en' },
  { word: 'CARPENTER', difficulty: 'medium', language: 'en' },
  { word: 'SHOEMAKER', difficulty: 'medium', language: 'en' },
  { word: 'BAKERY', difficulty: 'medium', language: 'en' },
  { word: 'VENTILATOR', difficulty: 'medium', language: 'en' },
  { word: 'COMPUTER', difficulty: 'medium', language: 'en' },
  { word: 'TELEVISION', difficulty: 'medium', language: 'en' },
  { word: 'CALENDAR', difficulty: 'medium', language: 'en' },
  { word: 'NOTEBOOK', difficulty: 'medium', language: 'en' },
  { word: 'BACKPACK', difficulty: 'medium', language: 'en' },
  { word: 'SCHOOL', difficulty: 'medium', language: 'en' },
  { word: 'HOSPITAL', difficulty: 'medium', language: 'en' },
  { word: 'AMBULANCE', difficulty: 'medium', language: 'en' },
  { word: 'BICYCLE', difficulty: 'medium', language: 'en' },
  { word: 'HIGHWAY', difficulty: 'medium', language: 'en' },
  { word: 'MOUNTAIN', difficulty: 'medium', language: 'en' },
  { word: 'WATERFALL', difficulty: 'medium', language: 'en' },
  { word: 'STORM', difficulty: 'medium', language: 'en' },
  { word: 'LIGHTNING', difficulty: 'medium', language: 'en' },
  { word: 'PLANET', difficulty: 'medium', language: 'en' },
  { word: 'SATELLITE', difficulty: 'medium', language: 'en' },
  { word: 'GALAXY', difficulty: 'medium', language: 'en' },
  { word: 'PYRAMID', difficulty: 'medium', language: 'en' },
  { word: 'CASTLE', difficulty: 'medium', language: 'en' },
  { word: 'ADVENTURE', difficulty: 'medium', language: 'en' },
  { word: 'MYSTERY', difficulty: 'medium', language: 'en' },
  { word: 'CRAB', difficulty: 'medium', language: 'en' },
  { word: 'WHALE', difficulty: 'medium', language: 'en' },
  { word: 'SHARK', difficulty: 'medium', language: 'en' },
  { word: 'PENGUIN', difficulty: 'medium', language: 'en' },

  { word: 'CRYPTOGRAPHY', difficulty: 'hard', language: 'en' },
  { word: 'PHONOLOGY', difficulty: 'hard', language: 'en' },
  { word: 'SURGICAL', difficulty: 'hard', language: 'en' },
  { word: 'MICROSCOPE', difficulty: 'hard', language: 'en' },
  { word: 'NEUROLOGY', difficulty: 'hard', language: 'en' },
  { word: 'PHOTOSYNTHESIS', difficulty: 'hard', language: 'en' },
  { word: 'THERMODYNAMICS', difficulty: 'hard', language: 'en' },
  { word: 'GEOCHEMISTRY', difficulty: 'hard', language: 'en' },
  { word: 'ARCHAEOLOGY', difficulty: 'hard', language: 'en' },
  { word: 'ANTHROPOLOGY', difficulty: 'hard', language: 'en' },
  { word: 'BIOTECHNOLOGY', difficulty: 'hard', language: 'en' },
  { word: 'ASTROPHYSICS', difficulty: 'hard', language: 'en' },
  { word: 'OCEANOGRAPHY', difficulty: 'hard', language: 'en' },
  { word: 'PALEONTOLOGY', difficulty: 'hard', language: 'en' },
  { word: 'NEUROSCIENCE', difficulty: 'hard', language: 'en' },
  { word: 'CYBERSECURITY', difficulty: 'hard', language: 'en' },
  { word: 'PROGRAMMING', difficulty: 'hard', language: 'en' },
  { word: 'AUTOMATION', difficulty: 'hard', language: 'en' },
  { word: 'SYNCHRONIZATION', difficulty: 'hard', language: 'en' },
  { word: 'CONFIGURATION', difficulty: 'hard', language: 'en' },
  { word: 'AUTHENTICATION', difficulty: 'hard', language: 'en' },
  { word: 'OPTIMIZATION', difficulty: 'hard', language: 'en' },
  { word: 'VIRTUALIZATION', difficulty: 'hard', language: 'en' },
  { word: 'INFRASTRUCTURE', difficulty: 'hard', language: 'en' },
  { word: 'INTEROPERABILITY', difficulty: 'hard', language: 'en' },
  { word: 'DECENTRALIZATION', difficulty: 'hard', language: 'en' },
  { word: 'RESPONSIBILITY', difficulty: 'hard', language: 'en' },
  { word: 'TRANSFORMATION', difficulty: 'hard', language: 'en' },
  { word: 'ADMINISTRATION', difficulty: 'hard', language: 'en' },
  { word: 'CONSTITUTION', difficulty: 'hard', language: 'en' },
  { word: 'INVESTIGATION', difficulty: 'hard', language: 'en' },
  { word: 'EXPERIMENTATION', difficulty: 'hard', language: 'en' },
  { word: 'COMMUNICATION', difficulty: 'hard', language: 'en' },
  { word: 'ORGANIZATION', difficulty: 'hard', language: 'en' },
  { word: 'PLANNING', difficulty: 'hard', language: 'en' },
  { word: 'CLASSIFICATION', difficulty: 'hard', language: 'en' },
  { word: 'IDENTIFICATION', difficulty: 'hard', language: 'en' },
  { word: 'ELECTROCARDIOGRAM', difficulty: 'hard', language: 'en' },
  { word: 'PARALLELEPIPED', difficulty: 'hard', language: 'en' },
  { word: 'DEOXYRIBONUCLEIC', difficulty: 'hard', language: 'en' },
  { word: 'HYDROELECTRICITY', difficulty: 'hard', language: 'en' },
  { word: 'COUNTERINTELLIGENCE', difficulty: 'hard', language: 'en' },
];
