import { TriviaQuestion } from '../types/trivia.types';

export const GEOGRAPHY_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'geography-continents',
    category: 'geography',
    promptEs: 'Selecciona continentes.',
    promptEn: 'Select continents.',
    optionsEs: ['América', 'África', 'Europa', 'Amazonas'],
    optionsEn: ['America', 'Africa', 'Europe', 'Amazon'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['america africa europa', 'américa áfrica europa'],
    acceptedAnswersEn: ['america africa europe'],
  },
  {
    id: 'geography-largest-ocean',
    category: 'geography',
    promptEs: '¿Cuál es el océano más grande del planeta?',
    promptEn: 'What is the largest ocean on Earth?',
    optionsEs: ['Atlántico', 'Índico', 'Pacífico', 'Ártico'],
    optionsEn: ['Atlantic', 'Indian', 'Pacific', 'Arctic'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['pacifico', 'océano pacífico', 'oceano pacifico'],
    acceptedAnswersEn: ['pacific', 'pacific ocean'],
  },
  {
    id: 'geography-bolivia-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital constitucional de Bolivia?',
    promptEn: 'What is the constitutional capital of Bolivia?',
    optionsEs: ['La Paz', 'Santa Cruz', 'Sucre', 'Cochabamba'],
    optionsEn: ['La Paz', 'Santa Cruz', 'Sucre', 'Cochabamba'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['sucre'],
    acceptedAnswersEn: ['sucre'],
  },

    {
    id: 'geography-nile-river',
    category: 'geography',
    promptEs: '¿Cuál es el río más largo del mundo?',
    promptEn: 'What is the longest river in the world?',
    optionsEs: ['Amazonas', 'Nilo', 'Misisipi', 'Yangtsé'],
    optionsEn: ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['nilo', 'el nilo'],
    acceptedAnswersEn: ['nile', 'the nile'],
  },
  {
    id: 'geography-highest-mountain',
    category: 'geography',
    promptEs: '¿Cuál es la montaña más alta del mundo sobre el nivel del mar?',
    promptEn: 'What is the highest mountain in the world above sea level?',
    optionsEs: ['K2', 'Everest', 'Kangchenjunga', 'Lhotse'],
    optionsEn: ['K2', 'Everest', 'Kangchenjunga', 'Lhotse'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['everest', 'el everest', 'monte everest'],
    acceptedAnswersEn: ['everest', 'mount everest'],
  },
  {
    id: 'geography-france-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Francia?',
    promptEn: 'What is the capital of France?',
    optionsEs: ['Lyon', 'Marsella', 'París', 'Niza'],
    optionsEn: ['Lyon', 'Marseille', 'Paris', 'Nice'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['paris', 'parís'],
    acceptedAnswersEn: ['paris'],
  },
  {
    id: 'geography-largest-country',
    category: 'geography',
    promptEs: '¿Cuál es el país más grande del mundo por territorio?',
    promptEn: 'What is the largest country in the world by land area?',
    optionsEs: ['Canadá', 'China', 'Estados Unidos', 'Rusia'],
    optionsEn: ['Canada', 'China', 'United States', 'Russia'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['rusia'],
    acceptedAnswersEn: ['russia'],
  },
  {
    id: 'geography-smallest-country',
    category: 'geography',
    promptEs: '¿Cuál es el país más pequeño del mundo?',
    promptEn: 'What is the smallest country in the world?',
    optionsEs: ['Mónaco', 'San Marino', 'Vaticano', 'Malta'],
    optionsEn: ['Monaco', 'San Marino', 'Vatican City', 'Malta'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['vaticano', 'el vaticano', 'ciudad del vaticano'],
    acceptedAnswersEn: ['vatican', 'vatican city'],
  },
  {
    id: 'geography-japan-islands',
    category: 'geography',
    promptEs: 'Selecciona islas que pertenecen a Japón.',
    promptEn: 'Select islands that belong to Japan.',
    optionsEs: ['Honshu', 'Hokkaido', 'Kyushu', 'Madagascar'],
    optionsEn: ['Honshu', 'Hokkaido', 'Kyushu', 'Madagascar'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['honshu hokkaido kyushu'],
    acceptedAnswersEn: ['honshu hokkaido kyushu'],
  },
  {
    id: 'geography-australia-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Australia?',
    promptEn: 'What is the capital of Australia?',
    optionsEs: ['Sídney', 'Melbourne', 'Canberra', 'Brisbane'],
    optionsEn: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['canberra'],
    acceptedAnswersEn: ['canberra'],
  },
  {
    id: 'geography-amazon-rainforest',
    category: 'geography',
    promptEs: '¿En qué continente se encuentra la selva amazónica?',
    promptEn: 'In which continent is the Amazon rainforest located?',
    optionsEs: ['África', 'América del Sur', 'Asia', 'Oceanía'],
    optionsEn: ['Africa', 'South America', 'Asia', 'Oceania'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['america del sur', 'américa del sur', 'sudamerica', 'sudamérica'],
    acceptedAnswersEn: ['south america'],
  },
  {
    id: 'geography-egypt-river',
    category: 'geography',
    promptEs: '¿Qué gran río atraviesa Egipto?',
    promptEn: 'Which major river flows through Egypt?',
    optionsEs: ['Tíber', 'Nilo', 'Éufrates', 'Ganges'],
    optionsEn: ['Tiber', 'Nile', 'Euphrates', 'Ganges'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['nilo', 'el nilo'],
    acceptedAnswersEn: ['nile', 'the nile'],
  },
  {
    id: 'geography-canada-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Canadá?',
    promptEn: 'What is the capital of Canada?',
    optionsEs: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
    optionsEn: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['ottawa'],
    acceptedAnswersEn: ['ottawa'],
  },
  {
    id: 'geography-italy-volcanoes',
    category: 'geography',
    promptEs: 'Selecciona volcanes situados en Italia.',
    promptEn: 'Select volcanoes located in Italy.',
    optionsEs: ['Vubio', 'Etna', 'Vesubio', 'Krakatoa'],
    optionsEn: ['Vubio', 'Etna', 'Vesuvius', 'Krakatoa'],
    correctOptionIndexes: [1, 2],
    acceptedAnswersEs: ['etna vesubio', 'vesubio etna'],
    acceptedAnswersEn: ['etna vesuvius', 'vesuvius etna'],
  },
  {
    id: 'geography-desert-largest',
    category: 'geography',
    promptEs: '¿Cuál es el desierto cálido más grande del mundo?',
    promptEn: 'What is the largest hot desert in the world?',
    optionsEs: ['Gobi', 'Sahara', 'Atacama', 'Kalahari'],
    optionsEn: ['Gobi', 'Sahara', 'Atacama', 'Kalahari'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['sahara', 'el sahara'],
    acceptedAnswersEn: ['sahara', 'the sahara'],
  },
  {
    id: 'geography-brazil-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Brasil?',
    promptEn: 'What is the capital of Brazil?',
    optionsEs: ['Río de Janeiro', 'São Paulo', 'Brasilia', 'Salvador'],
    optionsEn: ['Rio de Janeiro', 'São Paulo', 'Brasilia', 'Salvador'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['brasilia'],
    acceptedAnswersEn: ['brasilia'],
  },
  {
    id: 'geography-panama-canal',
    category: 'geography',
    promptEs: '¿Qué dos océanos conecta el Canal de Panamá?',
    promptEn: 'Which two oceans does the Panama Canal connect?',
    optionsEs: ['Atlántico e Índico', 'Pacífico e Índico', 'Atlántico y Pacífico', 'Ártico y Antártico'],
    optionsEn: ['Atlantic and Indian', 'Pacific and Indian', 'Atlantic and Pacific', 'Arctic and Antarctic'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['atlantico y pacifico', 'atlántico y pacífico'],
    acceptedAnswersEn: ['atlantic and pacific'],
  },
  {
    id: 'geography-spain-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de España?',
    promptEn: 'What is the capital of Spain?',
    optionsEs: ['Barcelona', 'Valencia', 'Sevilla', 'Madrid'],
    optionsEn: ['Barcelona', 'Valencia', 'Seville', 'Madrid'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['madrid'],
    acceptedAnswersEn: ['madrid'],
  },
  {
    id: 'geography-mediterranean-islands',
    category: 'geography',
    promptEs: 'Selecciona islas del Mar Mediterráneo.',
    promptEn: 'Select islands in the Mediterranean Sea.',
    optionsEs: ['Sicilia', 'Cerdeña', 'Mallorca', 'Hawái'],
    optionsEn: ['Sicily', 'Sardinia', 'Mallorca', 'Hawaii'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['sicilia cerdeña mallorca'],
    acceptedAnswersEn: ['sicily sardinia mallorca'],
  },
  {
    id: 'geography-united-kingdom-countries',
    category: 'geography',
    promptEs: '¿Qué países forman parte del Reino Unido?',
    promptEn: 'Which countries are part of the United Kingdom?',
    optionsEs: ['Inglaterra', 'Escocia', 'Gales', 'Irlanda del Norte'],
    optionsEn: ['England', 'Scotland', 'Wales', 'Northern Ireland'],
    correctOptionIndexes: [0, 1, 2, 3],
    acceptedAnswersEs: ['inglaterra escocia gales irlanda del norte'],
    acceptedAnswersEn: ['england scotland wales northern ireland'],
  },
  {
    id: 'geography-india-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de la India?',
    promptEn: 'What is the capital of India?',
    optionsEs: ['Bombay', 'Nueva Delhi', 'Calcuta', 'Madras'],
    optionsEn: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['nueva delhi'],
    acceptedAnswersEn: ['new delhi'],
  },
  {
    id: 'geography-alps-continent',
    category: 'geography',
    promptEs: '¿En qué continente se encuentra la cordillera de los Alpes?',
    promptEn: 'In which continent is the Alps mountain range located?',
    optionsEs: ['Asia', 'América', 'Europa', 'África'],
    optionsEn: ['Asia', 'America', 'Europe', 'Africa'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['europa'],
    acceptedAnswersEn: ['europe'],
  },
  {
    id: 'geography-usa-largest-state',
    category: 'geography',
    promptEs: '¿Cuál es el estado más grande de EE. UU. por superficie?',
    promptEn: 'What is the largest US state by area?',
    optionsEs: ['Texas', 'California', 'Alaska', 'Montana'],
    optionsEn: ['Texas', 'California', 'Alaska', 'Montana'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['alaska'],
    acceptedAnswersEn: ['alaska'],
  },
  {
    id: 'geography-south-africa-capitals',
    category: 'geography',
    promptEs: 'Selecciona las capitales oficiales de Sudáfrica.',
    promptEn: 'Select the official capitals of South Africa.',
    optionsEs: ['Pretoria', 'Ciudad del Cabo', 'Bloemfontein', 'Johannesburgo'],
    optionsEn: ['Pretoria', 'Cape Town', 'Bloemfontein', 'Johannesburg'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['pretoria ciudad del cabo bloemfontein'],
    acceptedAnswersEn: ['pretoria cape town bloemfontein'],
  },
  {
    id: 'geography-china-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de China?',
    promptEn: 'What is the capital of China?',
    optionsEs: ['Shanghái', 'Hong Kong', 'Pekín', 'Cantón'],
    optionsEn: ['Shanghai', 'Hong Kong', 'Beijing', 'Guangzhou'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['pekin', 'pekín'],
    acceptedAnswersEn: ['beijing'],
  },
  {
    id: 'geography-dead-sea-type',
    category: 'geography',
    promptEs: 'Geográficamente hablando, ¿qué es realmente el Mar Muerto?',
    promptEn: 'Geographically speaking, what actually is the Dead Sea?',
    optionsEs: ['Un océano', 'Un lago', 'Un golfo', 'Un estrecho'],
    optionsEn: ['An ocean', 'A lake', 'A gulf', 'A strait'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['un lago', 'lago'],
    acceptedAnswersEn: ['a lake', 'lake'],
  },
  {
    id: 'geography-mexico-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de México?',
    promptEn: 'What is the capital of Mexico?',
    optionsEs: ['Guadalajara', 'Monterrey', 'Ciudad de México', 'Cancún'],
    optionsEn: ['Guadalajara', 'Monterrey', 'Mexico City', 'Cancun'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['ciudad de mexico', 'ciudad de méxico', 'cdmx'],
    acceptedAnswersEn: ['mexico city'],
  },
  {
    id: 'geography-equator-countries',
    category: 'geography',
    promptEs: 'Selecciona países por donde pasa la línea del ecuador.',
    promptEn: 'Select countries that the equator passes through.',
    optionsEs: ['Ecuador', 'Colombia', 'Brasil', 'Argentina'],
    optionsEn: ['Ecuador', 'Colombia', 'Brazil', 'Argentina'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['ecuador colombia brasil'],
    acceptedAnswersEn: ['ecuador colombia brazil'],
  },
  {
    id: 'geography-germany-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Alemania?',
    promptEn: 'What is the capital of Germany?',
    optionsEs: ['Múnich', 'Fráncfort', 'Hamburgo', 'Berlín'],
    optionsEn: ['Munich', 'Frankfurt', 'Hamburg', 'Berlin'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['berlin', 'berlín'],
    acceptedAnswersEn: ['berlin'],
  },
  {
    id: 'geography-missing-antarctica',
    category: 'geography',
    promptEs: '¿Cuál es el único continente que no tiene población humana nativa permanente?',
    promptEn: 'Which is the only continent with no permanent native human population?',
    optionsEs: ['Oceanía', 'Antártida', 'África', 'Asia'],
    optionsEn: ['Oceania', 'Antarctica', 'Africa', 'Asia'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['antartida', 'antártida'],
    acceptedAnswersEn: ['antarctica'],
  },
  {
    id: 'geography-argentina-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Argentina?',
    promptEn: 'What is the capital of Argentina?',
    optionsEs: ['Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza'],
    optionsEn: ['Cordoba', 'Rosario', 'Buenos Aires', 'Mendoza'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['buenos aires'],
    acceptedAnswersEn: ['buenos aires'],
  },
  {
    id: 'geography-scandinavian-countries',
    category: 'geography',
    promptEs: 'Selecciona los países tradicionalmente considerados escandinavos.',
    promptEn: 'Select the countries traditionally considered Scandinavian.',
    optionsEs: ['Noruega', 'Suecia', 'Dinamarca', 'Italia'],
    optionsEn: ['Norway', 'Sweden', 'Denmark', 'Italy'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['noruega suecia dinamarca'],
    acceptedAnswersEn: ['norway sweden denmark'],
  },
  {
    id: 'geography-italy-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Italia?',
    promptEn: 'What is the capital of Italy?',
    optionsEs: ['Milán', 'Florencia', 'Venecia', 'Roma'],
    optionsEn: ['Milan', 'Florence', 'Venice', 'Rome'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['roma'],
    acceptedAnswersEn: ['rome'],
  },
  {
    id: 'geography-iceland-feature',
    category: 'geography',
    promptEs: '¿Por qué característica geológica principal es famosa Islandia?',
    promptEn: 'For what main geological feature is Iceland famous?',
    optionsEs: ['Volcanes y glaciares', 'Desiertos de arena', 'Selvas tropicales', 'Arrecifes de coral'],
    optionsEn: ['Volcanoes and glaciers', 'Sandy deserts', 'Tropical rainforests', 'Coral reefs'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['volcanes y glaciares'],
    acceptedAnswersEn: ['volcanoes and glaciers'],
  },
  {
    id: 'geography-russia-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Rusia?',
    promptEn: 'What is the capital of Russia?',
    optionsEs: ['San Petersburgo', 'Novosibirsk', 'Moscú', 'Kazán'],
    optionsEn: ['Saint Petersburg', 'Novosibirsk', 'Moscow', 'Kazan'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['moscu', 'moscú'],
    acceptedAnswersEn: ['moscow'],
  },
  {
    id: 'geography-great-lakes',
    category: 'geography',
    promptEs: 'Selecciona lagos que forman parte de los Grandes Lagos de Norteamérica.',
    promptEn: 'Select lakes that are part of the Great Lakes of North America.',
    optionsEs: ['Superior', 'Michigan', 'Huron', 'Titicaca'],
    optionsEn: ['Superior', 'Michigan', 'Huron', 'Titicaca'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['superior michigan huron'],
    acceptedAnswersEn: ['superior michigan huron'],
  },
  {
    id: 'geography-egypt-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Egipto?',
    promptEn: 'What is the capital of Egypt?',
    optionsEs: ['Alejandría', 'El Cairo', 'Giza', 'Luxor'],
    optionsEn: ['Alexandria', 'Cairo', 'Giza', 'Luxor'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['el cairo', 'cairo'],
    acceptedAnswersEn: ['cairo', 'the cairo'],
  },
  {
    id: 'geography-highest-waterfall',
    category: 'geography',
    promptEs: '¿Cuál es la cascada más alta del mundo?',
    promptEn: 'What is the highest waterfall in the world?',
    optionsEs: ['Cataratas del Niágara', 'Cataratas de Iguazú', 'Salto Ángel', 'Cataratas Victoria'],
    optionsEn: ['Niagara Falls', 'Iguazu Falls', 'Angel Falls', 'Victoria Falls'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['salto angel', 'salto ángel'],
    acceptedAnswersEn: ['angel falls'],
  },
  {
    id: 'geography-colombia-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Colombia?',
    promptEn: 'What is the capital of Colombia?',
    optionsEs: ['Medellín', 'Cali', 'Bogotá', 'Cartagena'],
    optionsEn: ['Medellin', 'Cali', 'Bogota', 'Cartagena'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['bogota', 'bogotá'],
    acceptedAnswersEn: ['bogota'],
  },
  {
    id: 'geography-united-states-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de los Estados Unidos?',
    promptEn: 'What is the capital of the United States?',
    optionsEs: ['Nueva York', 'Los Ángeles', 'Chicago', 'Washington D.C.'],
    optionsEn: ['New York', 'Los Angeles', 'Chicago', 'Washington D.C.'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['washington d.c.', 'washington dc', 'washington'],
    acceptedAnswersEn: ['washington d.c.', 'washington dc', 'washington'],
  },
  {
    id: 'geography-peru-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Perú?',
    promptEn: 'What is the capital of Peru?',
    optionsEs: ['Cusco', 'Arequipa', 'Lima', 'Trujillo'],
    optionsEn: ['Cusco', 'Arequipa', 'Lima', 'Trujillo'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['lima'],
    acceptedAnswersEn: ['lima'],
  },
  {
    id: 'geography-balkan-countries',
    category: 'geography',
    promptEs: 'Selecciona países situados en la península de los Balcanes.',
    promptEn: 'Select countries located on the Balkan Peninsula.',
    optionsEs: ['Grecia', 'Bulgaria', 'Albania', 'Portugal'],
    optionsEn: ['Greece', 'Bulgaria', 'Albania', 'Portugal'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['grecia bulgaria albania'],
    acceptedAnswersEn: ['greece bulgaria albania'],
  },
  {
    id: 'geography-portugal-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Portugal?',
    promptEn: 'What is the capital of Portugal?',
    optionsEs: ['Oporto', 'Lisboa', 'Coímbra', 'Braga'],
    optionsEn: ['Porto', 'Lisbon', 'Coimbra', 'Braga'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['lisboa'],
    acceptedAnswersEn: ['lisbon'],
  },
  {
    id: 'geography-south-america-rivers',
    category: 'geography',
    promptEs: 'Selecciona ríos que se encuentran en América del Sur.',
    promptEn: 'Select rivers located in South America.',
    optionsEs: ['Amazonas', 'Orinoco', 'Paraná', 'Misisipi'],
    optionsEn: ['Amazon', 'Orinoco', 'Parana', 'Mississippi'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['amazonas orinoco parana', 'amazonas orinoco paraná'],
    acceptedAnswersEn: ['amazon orinoco parana'],
  },
  {
    id: 'geography-greece-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Grecia?',
    promptEn: 'What is the capital of Greece?',
    optionsEs: ['Esparta', 'Salónica', 'Atenas', 'Miconos'],
    optionsEn: ['Sparta', 'Thessaloniki', 'Athens', 'Mykonos'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['atenas'],
    acceptedAnswersEn: ['athens'],
  },
  {
    id: 'geography-caribbean-islands',
    category: 'geography',
    promptEs: 'Selecciona islas que están en el Mar Caribe.',
    promptEn: 'Select islands that are in the Caribbean Sea.',
    optionsEs: ['Cuba', 'Jamaica', 'Puerto Rico', 'Madagascar'],
    optionsEn: ['Cuba', 'Jamaica', 'Puerto Rico', 'Madagascar'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['cuba jamaica puerto rico'],
    acceptedAnswersEn: ['cuba jamaica puerto rico'],
  },
  {
    id: 'geography-netherlands-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital oficial de los Países Bajos?',
    promptEn: 'What is the official capital of the Netherlands?',
    optionsEs: ['La Haya', 'Róterdam', 'Ámsterdam', 'Utrecht'],
    optionsEn: ['The Hague', 'Rotterdam', 'Amsterdam', 'Utrecht'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['amsterdam', 'ámsterdam'],
    acceptedAnswersEn: ['amsterdam'],
  },
  {
    id: 'geography-chile-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Chile?',
    promptEn: 'What is the capital of Chile?',
    optionsEs: ['Valparaíso', 'Concepción', 'Santiago', 'Antofasta'],
    optionsEn: ['Valparaiso', 'Concepcion', 'Santiago', 'Antofagasta'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['santiago', 'santiago de chile'],
    acceptedAnswersEn: ['santiago'],
  },
  {
    id: 'geography-turkey-cities',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Turquía?',
    promptEn: 'What is the capital of Turkey?',
    optionsEs: ['Estambul', 'Ankara', 'Esmirna', 'Antalya'],
    optionsEn: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['ankara'],
    acceptedAnswersEn: ['ankara'],
  },
  {
    id: 'geography-highest-lake',
    category: 'geography',
    promptEs: '¿Qué lago navegable es el más alto del mundo?',
    promptEn: 'Which navigable lake is the highest in the world?',
    optionsEs: ['Lago Titicaca', 'Lago Maracaibo', 'Lago Superior', 'Lago Baikal'],
    optionsEn: ['Lake Titicaca', 'Lake Maracaibo', 'Lake Superior', 'Lake Baikal'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['titicaca', 'lago titicaca'],
    acceptedAnswersEn: ['titicaca', 'lake titicaca'],
  },
  {
    id: 'geography-cuba-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Cuba?',
    promptEn: 'What is the capital of Cuba?',
    optionsEs: ['Varadero', 'Santiago de Cuba', 'La Habana', 'Camagüey'],
    optionsEn: ['Varadero', 'Santiago de Cuba', 'Havana', 'Camaguey'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['la habana', 'habana'],
    acceptedAnswersEn: ['havana', 'the havana'],
  },
  {
    id: 'geography-venezuela-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Venezuela?',
    promptEn: 'What is the capital of Venezuela?',
    optionsEs: ['Maracaibo', 'Valencia', 'Caracas', 'Barquisimeto'],
    optionsEn: ['Maracaibo', 'Valencia', 'Caracas', 'Barquisimeto'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['caracas'],
    acceptedAnswersEn: ['caracas'],
  },
  {
    id: 'geography-ukraine-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Ucrania?',
    promptEn: 'What is the capital of Ukraine?',
    optionsEs: ['Odesa', 'Járkov', 'Kiev', 'Leópolis'],
    optionsEn: ['Odesa', 'Kharkiv', 'Kyiv', 'Lviv'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['kiev', 'kyiv'],
    acceptedAnswersEn: ['kyiv', 'kiev'],
  },
  {
    id: 'geography-southeast-asia-countries',
    category: 'geography',
    promptEs: 'Selecciona países situados en el sudeste asiático.',
    promptEn: 'Select countries located in Southeast Asia.',
    optionsEs: ['Tailandia', 'Vietnam', 'Indonesia', 'Egipto'],
    optionsEn: ['Thailand', 'Vietnam', 'Indonesia', 'Egypt'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['tailandia vietnam indonesia'],
    acceptedAnswersEn: ['thailand vietnam indonesia'],
  },
  {
    id: 'geography-switzerland-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Suiza?',
    promptEn: 'What is the capital of Switzerland?',
    optionsEs: ['Zúrich', 'Ginebra', 'Berna', 'Basilea'],
    optionsEn: ['Zurich', 'Geneva', 'Bern', 'Basel'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['berna'],
    acceptedAnswersEn: ['bern'],
  },
  {
    id: 'geography-thailand-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Tailandia?',
    promptEn: 'What is the capital of Thailand?',
    optionsEs: ['Phuket', 'Bangkok', 'Chiang Mai', 'Pattaya'],
    optionsEn: ['Phuket', 'Bangkok', 'Chiang Mai', 'Pattaya'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['bangkok'],
    acceptedAnswersEn: ['bangkok'],
  },
  {
    id: 'geography-poland-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Polonia?',
    promptEn: 'What is the capital of Polonia?',
    optionsEs: ['Cracovia', 'Gdansk', 'Varsovia', 'Wroclaw'],
    optionsEn: ['Krakow', 'Gdansk', 'Warsaw', 'Wroclaw'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['varsovia'],
    acceptedAnswersEn: ['warsaw'],
  },
  {
    id: 'geography-austria-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Austria?',
    promptEn: 'What is the capital of Austria?',
    optionsEs: ['Salzburgo', 'Innsbruck', 'Viena', 'Graz'],
    optionsEn: ['Salzburg', 'Innsbruck', 'Vienna', 'Graz'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['viena'],
    acceptedAnswersEn: ['vienna'],
  },
  {
    id: 'geography-norway-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Noruega?',
    promptEn: 'What is the capital of Norway?',
    optionsEs: ['Bergen', 'Trondheim', 'Oslo', 'Stavanger'],
    optionsEn: ['Bergen', 'Trondheim', 'Oslo', 'Stavanger'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['oslo'],
    acceptedAnswersEn: ['oslo'],
  },
  {
    id: 'geography-sweden-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Suecia?',
    promptEn: 'What is the capital of Sweden?',
    optionsEs: ['Gotemburgo', 'Malmö', 'Estocolmo', 'Uppsala'],
    optionsEn: ['Gothenburg', 'Malmo', 'Stockholm', 'Uppsala'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['estocolmo'],
    acceptedAnswersEn: ['stockholm'],
  },
  {
    id: 'geography-ireland-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de la República de Irlanda?',
    promptEn: 'What is the capital of the Republic of Ireland?',
    optionsEs: ['Belfast', 'Cork', 'Dublín', 'Galway'],
    optionsEn: ['Belfast', 'Cork', 'Dublin', 'Galway'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['dublin', 'dublín'],
    acceptedAnswersEn: ['dublin'],
  },
  {
    id: 'geography-belgium-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Bélgica?',
    promptEn: 'What is the capital of Belgium?',
    optionsEs: ['Amberes', 'Brujas', 'Bruselas', 'Gante'],
    optionsEn: ['Antwerp', 'Bruges', 'Brussels', 'Ghent'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['bruselas'],
    acceptedAnswersEn: ['brussels'],
  },
  {
    id: 'geography-central-america-countries',
    category: 'geography',
    promptEs: 'Selecciona países que pertenecen a América Central.',
    promptEn: 'Select countries that belong to Central America.',
    optionsEs: ['Guatemala', 'Honduras', 'Costa Rica', 'Paraguay'],
    optionsEn: ['Guatemala', 'Honduras', 'Costa Rica', 'Paraguay'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['guatemala honduras costa rica'],
    acceptedAnswersEn: ['guatemala honduras costa rica'],
  },
  {
    id: 'geography-south-korea-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Corea del Sur?',
    promptEn: 'What is the capital of South Korea?',
    optionsEs: ['Busan', 'Incheon', 'Seúl', 'Daegu'],
    optionsEn: ['Busan', 'Incheon', 'Seoul', 'Daegu'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['seoul', 'seúl', 'seul'],
    acceptedAnswersEn: ['seoul'],
  },
  {
    id: 'geography-philippines-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Filipinas?',
    promptEn: 'What is the capital of the Philippines?',
    optionsEs: ['Cebú', 'Davao', 'Manila', 'Quezon City'],
    optionsEn: ['Cebu', 'Davao', 'Manila', 'Quezon City'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['manila'],
    acceptedAnswersEn: ['manila'],
  },
  {
    id: 'geography-saudi-arabia-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Arabia Saudita?',
    promptEn: 'What is the capital of Saudi Arabia?',
    optionsEs: ['Yeda', 'La Meca', 'Riad', 'Medina'],
    optionsEn: ['Jeddah', 'Mecca', 'Riyadh', 'Medina'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['riad', 'riyadh'],
    acceptedAnswersEn: ['riyadh', 'riad'],
  },
  {
    id: 'geography-new-zealand-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Nueva Zelanda?',
    promptEn: 'What is the capital of New Zealand?',
    optionsEs: ['Auckland', 'Christchurch', 'Wellington', 'Hamilton'],
    optionsEn: ['Auckland', 'Christchurch', 'Wellington', 'Hamilton'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['wellington'],
    acceptedAnswersEn: ['wellington'],
  },
  {
    id: 'geography-morocco-capital',
    category: 'geography',
    promptEs: '¿Cuál es la capital de Marruecos?',
    promptEn: 'What is the capital of Morocco?',
    optionsEs: ['Casablanca', 'Marrakech', 'Rabat', 'Fez'],
    optionsEn: ['Casablanca', 'Marrakech', 'Rabat', 'Fez'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['rabat'],
    acceptedAnswersEn: ['rabat'],
  }, 
];