import { TriviaQuestion } from '../types/trivia.types';

export const HISTORY_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'history-independence-bolivia',
    category: 'history',
    promptEs: '¿En qué año se declaró la independencia de Bolivia?',
    promptEn: 'In what year was Bolivia declared independent?',
    optionsEs: ['1809', '1825', '1839', '1879'],
    optionsEn: ['1809', '1825', '1839', '1879'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1825', 'seis de agosto de 1825', '6 de agosto de 1825'],
    acceptedAnswersEn: ['1825', 'august 6 1825', '6 august 1825'],
  },
  {
    id: 'history-ancient-civilizations',
    category: 'history',
    promptEs: 'Selecciona civilizaciones de la antigüedad.',
    promptEn: 'Select civilizations from ancient history.',
    optionsEs: ['Egipcia', 'Romana', 'Inca', 'Internet'],
    optionsEn: ['Egyptian', 'Roman', 'Inca', 'Internet'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['egipcia romana inca', 'egipto roma incas'],
    acceptedAnswersEn: ['egyptian roman inca', 'egypt rome inca'],
  },
  {
    id: 'history-world-war-two',
    category: 'history',
    promptEs: '¿En qué año terminó la Segunda Guerra Mundial?',
    promptEn: 'In what year did World War II end?',
    optionsEs: ['1918', '1939', '1945', '1969'],
    optionsEn: ['1918', '1939', '1945', '1969'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['1945', 'mil novecientos cuarenta y cinco'],
    acceptedAnswersEn: ['1945', 'nineteen forty five'],
  },
  {
    id: 'history-code-hammurabi',
    category: 'history',
    promptEs: '¿Qué antigua civilización creó el Código de Hammurabi?',
    promptEn: 'Which ancient civilization created the Code of Hammurabi?',
    optionsEs: ['Babilonia', 'Egipto', 'Persia', 'Grecia'],
    optionsEn: ['Babylon', 'Egypt', 'Persia', 'Greece'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['babilonia', 'imperio babilonico', 'babilonica'],
    acceptedAnswersEn: ['babylon', 'babylonian', 'babylonian empire'],
  },
  {
    id: 'history-alexander-great',
    category: 'history',
    promptEs: '¿De qué antiguo reino era rey Alejandro Magno?',
    promptEn: 'Of which ancient kingdom was Alexander the Great king?',
    optionsEs: ['Esparta', 'Atenas', 'Macedonia', 'Troya'],
    optionsEn: ['Sparta', 'Athens', 'Macedonia', 'Troy'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['macedonia', 'reino de macedonia'],
    acceptedAnswersEn: ['macedonia', 'kingdom of macedonia'],
  },
  {
    id: 'history-first-emperor-rome',
    category: 'history',
    promptEs: '¿Quién fue el primer emperador del Imperio Romano?',
    promptEn: 'Who was the first emperor of the Roman Empire?',
    optionsEs: ['Julio César', 'César Augusto', 'Nerón', 'Calígula'],
    optionsEn: ['Julius Caesar', 'Caesar Augustus', 'Nero', 'Caligula'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['cesar augusto', 'augusto', 'octavio'],
    acceptedAnswersEn: ['caesar augustus', 'augustus', 'octavian'],
  },
  {
    id: 'history-cleopatra-country',
    category: 'history',
    promptEs: '¿De qué país fue reina Cleopatra?',
    promptEn: 'Of which country was Cleopatra queen?',
    optionsEs: ['Grecia', 'Egipto', 'Roma', 'Siria'],
    optionsEn: ['Greece', 'Egypt', 'Rome', 'Syria'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['egipto', 'reino de egipto'],
    acceptedAnswersEn: ['egypt', 'kingdom of egypt'],
  },
  {
    id: 'history-punic-wars',
    category: 'history',
    promptEs: '¿Contra qué ciudad luchó Roma en las Guerras Púnicas?',
    promptEn: 'Against which city did Rome fight in the Punic Wars?',
    optionsEs: ['Cartago', 'Esparta', 'Atenas', 'Alejandría'],
    optionsEn: ['Carthage', 'Sparta', 'Athens', 'Alexandria'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['cartago', 'ciudad de cartago'],
    acceptedAnswersEn: ['carthage', 'city of carthage'],
  },
  {
    id: 'history-democracy-origin',
    category: 'history',
    promptEs: '¿En qué ciudad antigua nació la democracia?',
    promptEn: 'In which ancient city did democracy originate?',
    optionsEs: ['Roma', 'Esparta', 'Atenas', 'Tebas'],
    optionsEn: ['Rome', 'Sparta', 'Athens', 'Thebes'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['atenas', 'ciudad de atenas'],
    acceptedAnswersEn: ['athens', 'city of athens'],
  },
  {
    id: 'history-great-wall-china',
    category: 'history',
    promptEs: '¿Contra qué invasores se construyó principalmente la Gran Muralla China?',
    promptEn: 'Against which invaders was the Great Wall of China primarily built?',
    optionsEs: ['Mongoles', 'Persas', 'Romanos', 'Griegos'],
    optionsEn: ['Mongols', 'Persians', 'Romans', 'Greeks'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['mongoles', 'los mongoles', 'tribus mongolas'],
    acceptedAnswersEn: ['mongols', 'the mongols', 'mongol tribes'],
  },
  {
    id: 'history-julius-caesar-assassination',
    category: 'history',
    promptEs: '¿En qué año fue asesinado Julio César?',
    promptEn: 'In what year was Julius Caesar assassinated?',
    optionsEs: ['44 a.C.', '14 d.C.', '100 a.C.', '476 d.C.'],
    optionsEn: ['44 BC', '14 AD', '100 BC', '476 AD'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['44 a.c.', '44 antes de cristo', 'cuarenta y cuatro antes de cristo'],
    acceptedAnswersEn: ['44 bc', '44 before christ', 'forty four bc'],
  },

  // --- EDAD MEDIA Y RENACIMIENTO ---
  {
    id: 'history-fall-rome-year',
    category: 'history',
    promptEs: '¿En qué año cayó el Imperio Romano de Occidente?',
    promptEn: 'In what year did the Western Roman Empire fall?',
    optionsEs: ['313', '476', '1453', '1492'],
    optionsEn: ['313', '476', '1453', '1492'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['476', 'año 476', 'cuatrocientos setenta y seis'],
    acceptedAnswersEn: ['476', 'year 476', 'four hundred seventy six'],
  },
  {
    id: 'history-charlemagne-emperor',
    category: 'history',
    promptEs: '¿En qué año fue coronado Carlomagno como Emperador de Occidente?',
    promptEn: 'In what year was Charlemagne crowned Emperor of the West?',
    optionsEs: ['500', '800', '1000', '1200'],
    optionsEn: ['500', '800', '1000', '1200'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['800', 'año 800', 'ochocientos'],
    acceptedAnswersEn: ['800', 'year 800', 'eight hundred'],
  },
  {
    id: 'history-black-death-century',
    category: 'history',
    promptEs: '¿En qué siglo azotó la Peste Negra a Europa?',
    promptEn: 'In which century did the Black Death strike Europe?',
    optionsEs: ['Siglo XII', 'Siglo XIII', 'Siglo XIV', 'Siglo XV'],
    optionsEn: ['12th Century', '13th Century', '14th Century', '15th Century'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['siglo xiv', 'xiv', 'siglo 14', '14'],
    acceptedAnswersEn: ['14th century', '14th', 'century xiv', '14'],
  },
  {
    id: 'history-magna-carta',
    category: 'history',
    promptEs: '¿En qué país se firmó la Carta Magna en 1215?',
    promptEn: 'In which country was the Magna Carta signed in 1215?',
    optionsEs: ['Francia', 'Inglaterra', 'España', 'Alemania'],
    optionsEn: ['France', 'England', 'Spain', 'Germany'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['inglaterra', 'reino de inglaterra'],
    acceptedAnswersEn: ['england', 'kingdom of england'],
  },
  {
    id: 'history-joan-of-arc',
    category: 'history',
    promptEs: '¿En qué guerra luchó Juana de Arco?',
    promptEn: 'In which war did Joan of Arc fight?',
    optionsEs: ['Guerra de los Cien Años', 'Guerra de las Rosas', 'Las Cruzadas', 'Guerra de los Treinta Años'],
    optionsEn: ['Hundred Years\' War', 'War of the Roses', 'The Crusades', 'Thirty Years\' War'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['guerra de los cien años', 'guerra de los 100 años'],
    acceptedAnswersEn: ['hundred years war', 'the hundred years war'],
  },
  {
    id: 'history-fall-constantinople',
    category: 'history',
    promptEs: '¿En qué año cayó Constantinopla ante el Imperio Otomano?',
    promptEn: 'In what year did Constantinople fall to the Ottoman Empire?',
    optionsEs: ['1453', '1492', '1517', '1588'],
    optionsEn: ['1453', '1492', '1517', '1588'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['1453', 'año 1453', 'mil cuatrocientos cincuenta y tres'],
    acceptedAnswersEn: ['1453', 'year 1453', 'fourteen fifty three'],
  },
  {
    id: 'history-printing-press',
    category: 'history',
    promptEs: '¿Quién inventó la imprenta de tipos móviles en Europa?',
    promptEn: 'Who invented the movable type printing press in Europe?',
    optionsEs: ['Leonardo da Vinci', 'Johannes Gutenberg', 'Galileo Galilei', 'Isaac Newton'],
    optionsEn: ['Leonardo da Vinci', 'Johannes Gutenberg', 'Galileo Galilei', 'Isaac Newton'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['johannes gutenberg', 'gutenberg', 'juan gutenberg'],
    acceptedAnswersEn: ['johannes gutenberg', 'gutenberg'],
  },
  {
    id: 'history-discovery-america',
    category: 'history',
    promptEs: '¿En qué año llegó Cristóbal Colón a América?',
    promptEn: 'In what year did Christopher Columbus arrive in America?',
    optionsEs: ['1488', '1492', '1500', '1519'],
    optionsEn: ['1488', '1492', '1500', '1519'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1492', 'año 1492', 'mil cuatrocientos noventa y dos'],
    acceptedAnswersEn: ['1492', 'year 1492', 'fourteen ninety two'],
  },

  // --- EDAD MODERNA Y REVOLUCIONES ---
  {
    id: 'history-protestant-reformation',
    category: 'history',
    promptEs: '¿Quién inició la Reforma Protestante en 1517?',
    promptEn: 'Who started the Protestant Reformation in 1517?',
    optionsEs: ['Juan Calvino', 'Martín Lutero', 'Enrique VIII', 'Erasmo de Rotterdam'],
    optionsEn: ['John Calvin', 'Martin Luther', 'Henry VIII', 'Erasmus of Rotterdam'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['martin lutero', 'lutero'],
    acceptedAnswersEn: ['martin luther', 'luther'],
  },
  {
    id: 'history-french-revolution-year',
    category: 'history',
    promptEs: '¿En qué año comenzó la Revolución Francesa?',
    promptEn: 'In what year did the French Revolution begin?',
    optionsEs: ['1776', '1789', '1799', '1804'],
    optionsEn: ['1776', '1789', '1799', '1804'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1789', 'año 1789', 'mil setecientos ochenta y nueve'],
    acceptedAnswersEn: ['1789', 'year 1789', 'seventeen eighty nine'],
  },
  {
    id: 'history-french-revolution-fortress',
    category: 'history',
    promptEs: '¿Qué fortaleza fue tomada al inicio de la Revolución Francesa?',
    promptEn: 'Which fortress was stormed at the beginning of the French Revolution?',
    optionsEs: ['El Louvre', 'La Bastilla', 'Versalles', 'El Palacio Real'],
    optionsEn: ['The Louvre', 'The Bastille', 'Versailles', 'The Royal Palace'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['la bastilla', 'bastilla'],
    acceptedAnswersEn: ['the bastille', 'bastille'],
  },
  {
    id: 'history-us-independence',
    category: 'history',
    promptEs: '¿En qué año se firmó la Declaración de Independencia de los EE. UU.?',
    promptEn: 'In what year was the US Declaration of Independence signed?',
    optionsEs: ['1774', '1776', '1783', '1789'],
    optionsEn: ['1774', '1776', '1783', '1789'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1776', '4 de julio de 1776', 'mil setecientos setenta y seis'],
    acceptedAnswersEn: ['1776', 'july 4 1776', 'seventeen seventy six'],
  },
  {
    id: 'history-napoleon-defeat',
    category: 'history',
    promptEs: '¿En qué batalla fue derrotado definitivamente Napoleón Bonaparte?',
    promptEn: 'In which battle was Napoleon Bonaparte definitively defeated?',
    optionsEs: ['Batalla de Leipzig', 'Batalla de Waterloo', 'Batalla de Austerlitz', 'Batalla de Trafalgar'],
    optionsEn: ['Battle of Leipzig', 'Battle of Waterloo', 'Battle of Austerlitz', 'Battle of Trafalgar'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['waterloo', 'batalla de waterloo'],
    acceptedAnswersEn: ['waterloo', 'battle of waterloo'],
  },
  {
    id: 'history-industrial-revolution',
    category: 'history',
    promptEs: '¿En qué país comenzó la Revolución Industrial?',
    promptEn: 'In which country did the Industrial Revolution begin?',
    optionsEs: ['Francia', 'Alemania', 'Gran Bretaña', 'Estados Unidos'],
    optionsEn: ['France', 'Germany', 'Great Britain', 'United States'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['gran bretaña', 'inglaterra', 'reino unido'],
    acceptedAnswersEn: ['great britain', 'england', 'united kingdom'],
  },
  {
    id: 'history-steam-engine',
    category: 'history',
    promptEs: '¿Quién perfeccionó la máquina de vapor en el siglo XVIII?',
    promptEn: 'Who perfected the steam engine in the 18th century?',
    optionsEs: ['James Watt', 'Thomas Edison', 'Nikola Tesla', 'Robert Fulton'],
    optionsEn: ['James Watt', 'Thomas Edison', 'Nikola Tesla', 'Robert Fulton'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['james watt', 'watt'],
    acceptedAnswersEn: ['james watt', 'watt'],
  },
  {
    id: 'history-independence-mexico',
    category: 'history',
    promptEs: '¿En qué año comenzó la Guerra de Independencia de México?',
    promptEn: 'In what year did the Mexican War of Independence begin?',
    optionsEs: ['1808', '1810', '1821', '1836'],
    optionsEn: ['1808', '1810', '1821', '1836'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1810', '16 de septiembre de 1810'],
    acceptedAnswersEn: ['1810', 'september 16 1810'],
  },
  {
    id: 'history-independence-argentina',
    category: 'history',promptEs: '¿En qué año se declaró la independencia de Argentina?',
    promptEn: 'In what year was the independence of Argentina declared?',
    optionsEs: ['1810', '1812', '1816', '1820'],
    optionsEn: ['1810', '1812', '1816', '1820'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['1816', '9 de julio de 1816'],
    acceptedAnswersEn: ['1816', 'july 9 1816'],
  },
  {
    id: 'history-simon-bolivar-birth',category: 'history',
    promptEs: '¿En qué país nació el libertador Simón Bolívar?',
    promptEn: 'In which country was the liberator Simón Bolívar born?',
    optionsEs: ['Colombia', 'Venezuela', 'Ecuador', 'Perú'],
    optionsEn: ['Colombia', 'Venezuela', 'Ecuador', 'Peru'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['venezuela'],
    acceptedAnswersEn: ['venezuela'],
  },
  {
    id: 'history-san-martin-liberator',
    category: 'history',
    promptEs: '¿Qué cordillera cruzó José de San Martín para liberar a Chile y Perú?',
    promptEn: 'Which mountain range did José de San Martín cross to liberate Chile and Peru?',
    optionsEs: ['Los Alpes', 'Los Andes', 'Los Pirineos', 'Las Rocosas'],
    optionsEn: ['The Alps', 'The Andes', 'The Pyrenees', 'The Rockies'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['los andes', 'cordillera de los andes'],
    acceptedAnswersEn: ['the andes', 'andes', 'andes mountains'],
  },
  {
    id: 'history-fall-aztec-empire',
    category: 'history',
    promptEs: '¿En qué año cayó Tenochtitlan en manos de los conquistadores españoles?',
    promptEn: 'In what year did Tenochtitlan fall to the Spanish conquistadors?',
    optionsEs: ['1492', '1519', '1521', '1532'],
    optionsEn: ['1492', '1519', '1521', '1532'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['1521', 'año 1521'],
    acceptedAnswersEn: ['1521', 'year 1521'],
  },
  {
    id: 'history-conquest-inca-empire',
    category: 'history',
    promptEs: '¿Qué conquistador español lideró la caída del Imperio Inca?',
    promptEn: 'Which Spanish conquistador led the downfall of the Inca Empire?',
    optionsEs: ['Hernán Cortés', 'Francisco Pizarro', 'Pedro de Valdivia', 'Diego de Almagro'],
    optionsEn: ['Hernan Cortes', 'Francisco Pizarro', 'Pedro de Valdivia', 'Diego de Almagro'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['francisco pizarro', 'pizarro'],
    acceptedAnswersEn: ['francisco pizarro', 'pizarro'],
  },
  {
    id: 'history-treaty-of-tordesillas',
    category: 'history',
    promptEs: '¿Qué dos países firmaron el Tratado de Tordesillas en 1494?',
    promptEn: 'Which two countries signed the Treaty of Tordesillas in 1494?',
    optionsEs: ['España y Portugal', 'España y Francia', 'Inglaterra y Francia', 'Portugal e Inglaterra'],
    optionsEn: ['Spain and Portugal', 'Spain and France', 'England and France', 'Portugal and England'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['españa y portugal', 'portugal y españa'],
    acceptedAnswersEn: ['spain and portugal', 'portugal and spain'],
  },
  {
    id: 'history-brazil-independence',
    category: 'history',
    promptEs: '¿De qué país europeo se independizó Brasil en 1822?',
    promptEn: 'From which European country did Brazil become independent in 1822?',
    optionsEs: ['España', 'Francia', 'Portugal', 'Inglaterra'],
    optionsEn: ['Spain', 'France', 'Portugal', 'England'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['portugal'],
    acceptedAnswersEn: ['portugal'],
  },
  {
    id: 'history-ww1-start',
    category: 'history',
    promptEs: '¿En qué año comenzó la Primera Guerra Mundial?',
    promptEn: 'In what year did World War I begin?',
    optionsEs: ['1912', '1914', '1918', '1939'],
    optionsEn: ['1912', '1914', '1918', '1939'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1914', 'año 1914'],
    acceptedAnswersEn: ['1914', 'year 1914'],
  },
  {
    id: 'history-ww1-trigger',
    category: 'history',
    promptEs: '¿El asesinato de qué archiduque desencadenó la Primera Guerra Mundial?',
    promptEn: 'The assassination of which archduke triggered World War I?',
    optionsEs: ['Francisco Fernando', 'Leopoldo II', 'Rodolfo de Habsburgo', 'Federico el Grande'],
    optionsEn: ['Franz Ferdinand', 'Leopold II', 'Rudolf of Habsburg', 'Frederick the Great'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['francisco fernando', 'archiduque francisco fernando'],
    acceptedAnswersEn: ['franz ferdinand', 'archduke franz ferdinand'],
  },
  {
    id: 'history-russian-revolution',
    category: 'history',
    promptEs: '¿En qué año ocurrió la Revolución Rusa que dio origen a la URSS?',
    promptEn: 'In what year did the Russian Revolution occur, giving rise to the USSR?',
    optionsEs: ['1905', '1914', '1917', '1922'],
    optionsEn: ['1905', '1914', '1917', '1922'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['1917', 'año 1917'],
    acceptedAnswersEn: ['1917', 'year 1917'],
  },
  {
    id: 'history-treaty-versailles',
    category: 'history',
    promptEs: '¿Qué tratado puso fin formalmente a la Primera Guerra Mundial?',
    promptEn: 'Which treaty formally ended World War I?',
    optionsEs: ['Tratado de Utrecht', 'Tratado de Versalles', 'Tratado de París', 'Tratado de Trianón'],
    optionsEn: ['Treaty of Utrecht', 'Treaty of Versailles', 'Treaty of Paris', 'Treaty of Trianon'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['tratado de versalles', 'versalles'],
    acceptedAnswersEn: ['treaty of versailles', 'versailles'],
  },
  {
    id: 'history-great-depression',
    category: 'history',
    promptEs: '¿En qué año comenzó la Gran Depresión con el crac de la bolsa de Nueva York?',
    promptEn: 'In what year did the Great Depression begin with the New York stock market crash?',
    optionsEs: ['1919', '1929', '1933', '1939'],
    optionsEn: ['1919', '1929', '1933', '1939'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1929', 'año 1929'],
    acceptedAnswersEn: ['1929', 'year 1929'],
  },
  {
    id: 'history-russian-last-tsar',
    category: 'history',
    promptEs: '¿Quién fue el último zar de Rusia?',
    promptEn: 'Who was the last tsar of Russia?',
    optionsEs: ['Nicolás II', 'Alejandro III', 'Pedro el Grande', 'Iván el Terrible'],
    optionsEn: ['Nicholas II', 'Alexander III', 'Peter the Great', 'Ivan the Terrible'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['nicolas ii', 'nicolas segundo'],
    acceptedAnswersEn: ['nicholas ii', 'nicholas the second'],
  },
  {
    id: 'history-ww2-start-event',
    category: 'history',
    promptEs: '¿La invasión de qué país por parte de Alemania detonó la Segunda Guerra Mundial?',
    promptEn: 'The invasion of which country by Germany detonated World War II?',
    optionsEs: ['Francia', 'Polonia', 'Austria', 'Checoslovaquia'],
    optionsEn: ['France', 'Poland', 'Austria', 'Czechoslovakia'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['polonia'],
    acceptedAnswersEn: ['poland'],
  },
  {
    id: 'history-pearl-harbor',
    category: 'history',
    promptEs: '¿En qué año fue el ataque a Pearl Harbor por parte de Japón?',
    promptEn: 'In what year was the attack on Pearl Harbor by Japan?',
    optionsEs: ['1939', '1941', '1942', '1945'],
    optionsEn: ['1939', '1941', '1942', '1945'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1941', '7 de diciembre de 1941'],
    acceptedAnswersEn: ['1941', 'december 7 1941'],
  },
  {
    id: 'history-dday-year',
    category: 'history',
    promptEs: '¿En qué año se llevó a cabo el Desembarco de Normandía (Día D)?',
    promptEn: 'In what year did the Normandy Landings (D-Day) take place?',
    optionsEs: ['1943', '1944', '1945', '1946'],
    optionsEn: ['1943', '1944', '1945', '1946'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1944', '6 de junio de 1944'],
    acceptedAnswersEn: ['1944', 'june 6 1944'],
  },
  {
    id: 'history-atomic-bombs',
    category: 'history',
    promptEs: '¿Sobre qué dos ciudades japonesas se lanzaron bombas atómicas en 1945?',
    promptEn: 'On which two Japanese cities were atomic bombs dropped in 1945?',
    optionsEs: ['Tokio y Kioto', 'Hiroshima y Nagasaki', 'Osaka y Nagoya', 'Hiroshima y Tokio'],
    optionsEn: ['Tokyo and Kyoto', 'Hiroshima and Nagasaki', 'Osaka and Nagoya', 'Hiroshima and Tokyo'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['hiroshima y nagasaki', 'nagasaki y hiroshima'],
    acceptedAnswersEn: ['hiroshima and nagasaki', 'nagasaki and hiroshima'],
  },
  {
    id: 'history-un-foundation',
    category: 'history',
    promptEs: '¿En qué año se fundó la Organización de las Naciones Unidas (ONU)?',
    promptEn: 'In what year was the United Nations (UN) founded?',
    optionsEs: ['1919', '1945', '1948', '1950'],
    optionsEn: ['1919', '1945', '1948', '1950'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1945', 'año 1945'],
    acceptedAnswersEn: ['1945', 'year 1945'],
  },
  {
    id: 'history-churchill-country',
    category: 'history',
    promptEs: '¿De qué país fue Primer Ministro Winston Churchill durante la Segunda Guerra Mundial?',
    promptEn: 'Of which country was Winston Churchill Prime Minister during World War II?',
    optionsEs: ['Estados Unidos', 'Canadá', 'Reino Unido', 'Australia'],
    optionsEn: ['United States', 'Canada', 'United Kingdom', 'Australia'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['reino unido', 'gran bretaña', 'inglaterra'],
    acceptedAnswersEn: ['united kingdom', 'great britain', 'uk'],
  },
];
