import { TriviaQuestion } from '../types/trivia.types';

export const MATH_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'math-primes',
    category: 'math',
    promptEs: 'Selecciona números primos.',
    promptEn: 'Select prime numbers.',
    optionsEs: ['2', '3', '4', '9'],
    optionsEn: ['2', '3', '4', '9'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['2 y 3', '2 3', 'dos y tres'],
    acceptedAnswersEn: ['2 and 3', '2 3', 'two and three'],
  },
  {
    id: 'math-pi',
    category: 'math',
    promptEs: '¿Cuál es una aproximación común del número pi?',
    promptEn: 'What is a common approximation of pi?',
    optionsEs: ['1.41', '2.72', '3.14', '9.81'],
    optionsEn: ['1.41', '2.72', '3.14', '9.81'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['3.14', '3,14', 'tres punto catorce'],
    acceptedAnswersEn: ['3.14', 'three point fourteen'],
  },
  {
    id: 'math-triangle',
    category: 'math',
    promptEs: '¿Cómo se llama un polígono de tres lados?',
    promptEn: 'What is a polygon with three sides called?',
    optionsEs: ['Cuadrado', 'Triángulo', 'Pentágono', 'Círculo'],
    optionsEn: ['Square', 'Triangle', 'Pentagon', 'Circle'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['triangulo', 'triángulo'],
    acceptedAnswersEn: ['triangle'],
  },
    {
    id: 'math-square-root-16',
    category: 'math',
    promptEs: '¿Cuál es la raíz cuadrada de 16?',
    promptEn: 'What is the square root of 16?',
    optionsEs: ['2', '4', '8', '16'],
    optionsEn: ['2', '4', '8', '16'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['4', 'cuatro'],
    acceptedAnswersEn: ['4', 'four'],
  },
  {
    id: 'math-even-numbers',
    category: 'math',
    promptEs: 'Selecciona los números pares.',
    promptEn: 'Select the even numbers.',
    optionsEs: ['1', '4', '7', '8'],
    optionsEn: ['1', '4', '7', '8'],
    correctOptionIndexes: [1, 3],
    acceptedAnswersEs: ['4 y 8', '4 8', 'cuatro y ocho'],
    acceptedAnswersEn: ['4 and 8', '4 8', 'four and eight'],
  },
  {
    id: 'math-right-angle',
    category: 'math',
    promptEs: '¿Cuántos grados mide un ángulo recto?',
    promptEn: 'How many degrees is a right angle?',
    optionsEs: ['45', '90', '180', '360'],
    optionsEn: ['45', '90', '180', '360'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['90', 'noventa', '90 grados'],
    acceptedAnswersEn: ['90', 'ninety', '90 degrees'],
  },
  {
    id: 'math-pythagoras',
    category: 'math',
    promptEs: '¿A qué tipo de triángulos se aplica el teorema de Pitágoras?',
    promptEn: 'To what type of triangles does the Pythagorean theorem apply?',
    optionsEs: ['Equilátero', 'Isósceles', 'Acutángulo', 'Rectángulo'],
    optionsEn: ['Equilateral', 'Isosceles', 'Acute', 'Right'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['rectangulo', 'rectángulo'],
    acceptedAnswersEn: ['right', 'right triangle'],
  },
  {
    id: 'math-factorial-5',
    category: 'math',
    promptEs: '¿Cuál es el valor de 5 factorial (5!)?',
    promptEn: 'What is the value of 5 factorial (5!)?',
    optionsEs: ['24', '60', '120', '720'],
    optionsEn: ['24', '60', '120', '720'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['120', 'ciento veinte'],
    acceptedAnswersEn: ['120', 'one hundred twenty'],
  },
  {
    id: 'math-cube-sides',
    category: 'math',
    promptEs: '¿Cuántas caras tiene un cubo?',
    promptEn: 'How many faces does a cube have?',
    optionsEs: ['4', '6', '8', '12'],
    optionsEn: ['4', '6', '8', '12'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['6', 'seis'],
    acceptedAnswersEn: ['6', 'six'],
  },
  {
    id: 'math-fibonacci-next',
    category: 'math',
    promptEs: 'En la sucesión 1, 1, 2, 3, 5, 8... ¿cuál es el siguiente número?',
    promptEn: 'In the sequence 1, 1, 2, 3, 5, 8... what is the next number?',
    optionsEs: ['10', '11', '12', '13'],
    optionsEn: ['10', '11', '12', '13'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['13', 'trece'],
    acceptedAnswersEn: ['13', 'thirteen'],
  },
  {
    id: 'math-zero-property',
    category: 'math',
    promptEs: 'Cualquier número real multiplicado por cero es igual a:',
    promptEn: 'Any real number multiplied by zero is equal to:',
    optionsEs: ['0', '1', 'El mismo número', 'Infinito'],
    optionsEn: ['0', '1', 'The same number', 'Infinity'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['0', 'cero'],
    acceptedAnswersEn: ['0', 'zero'],
  },
  {
    id: 'math-hexagon-sides',
    category: 'math',
    promptEs: '¿Cuántos lados tiene un hexágono?',
    promptEn: 'How many sides does a hexagon have?',
    optionsEs: ['5', '6', '7', '8'],
    optionsEn: ['5', '6', '7', '8'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['6', 'seis'],
    acceptedAnswersEn: ['6', 'six'],
  },
  {
    id: 'math-negative-multiplication',
    category: 'math',
    promptEs: '¿Cuál es el resultado de multiplicar (-3) por (-4)?',
    promptEn: 'What is the result of multiplying (-3) by (-4)?',
    optionsEs: ['-12', '-7', '7', '12'],
    optionsEn: ['-12', '-7', '7', '12'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['12', 'doce'],
    acceptedAnswersEn: ['12', 'twelve'],
  },
  {
    id: 'math-roman-c',
    category: 'math',
    promptEs: '¿Qué número representa la letra C en los números romanos?',
    promptEn: 'What number does the letter C represent in Roman numerals?',
    optionsEs: ['50', '100', '500', '1000'],
    optionsEn: ['50', '100', '500', '1000'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['100', 'cien'],
    acceptedAnswersEn: ['100', 'one hundred'],
  },
  {
    id: 'math-acute-angle',
    category: 'math',
    promptEs: 'Un ángulo agudo es aquel que mide menos de:',
    promptEn: 'An acute angle is one that measures less than:',
    optionsEs: ['45°', '90°', '180°', '360°'],
    optionsEn: ['45°', '90°', '180°', '360°'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['90', '90 grados', 'noventa grados'],
    acceptedAnswersEn: ['90', '90 degrees', 'ninety degrees'],
  },
  {
    id: 'math-quarter-hour',
    category: 'math',
    promptEs: '¿Cuántos minutos hay en un cuarto de hora?',
    promptEn: 'How many minutes are in a quarter of an hour?',
    optionsEs: ['15', '20', '25', '30'],
    optionsEn: ['15', '20', '25', '30'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['15', 'quince'],
    acceptedAnswersEn: ['15', 'fifteen'],
  },
  {
    id: 'math-solve-x-basic',
    category: 'math',
    promptEs: 'Si 2x + 5 = 15, ¿cuánto vale x?',
    promptEn: 'If 2x + 5 = 15, what is x?',
    optionsEs: ['2', '5', '10', '20'],
    optionsEn: ['2', '5', '10', '20'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['5', 'cinco'],
    acceptedAnswersEn: ['5', 'five'],
  },
  {
    id: 'math-centimeter-meter',
    category: 'math',
    promptEs: '¿Cuántos centímetros hay en un metro?',
    promptEn: 'How many centimeters are in a meter?',
    optionsEs: ['10', '100', '1000', '10000'],
    optionsEn: ['10', '100', '1000', '10000'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['100', 'cien'],
    acceptedAnswersEn: ['100', 'one hundred'],
  },
  {
    id: 'math-prime-one-ten',
    category: 'math',
    promptEs: 'Selecciona los números primos entre el 1 y el 10.',
    promptEn: 'Select the prime numbers between 1 and 10.',
    optionsEs: ['5', '6', '7', '9'],
    optionsEn: ['5', '6', '7', '9'],
    correctOptionIndexes: [0, 2],
    acceptedAnswersEs: ['5 y 7', '5 7', 'cinco y siete'],
    acceptedAnswersEn: ['5 and 7', '5 7', 'five and seven'],
  },
  {
    id: 'math-fraction-half',
    category: 'math',
    promptEs: '¿Cuál de las siguientes fracciones equivale a un medio (1/2)?',
    promptEn: 'Which of the following fractions is equivalent to one half (1/2)?',
    optionsEs: ['2/3', '2/4', '3/5', '4/6'],
    optionsEn: ['2/3', '2/4', '3/5', '4/6'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['2/4', 'dos cuartos'],
    acceptedAnswersEn: ['2/4', 'two fourths'],
  },
  {
    id: 'math-circle-degrees',
    category: 'math',
    promptEs: '¿Cuántos grados totales tiene una circunferencia completa?',
    promptEn: 'How many total degrees are in a full circle?',
    optionsEs: ['90', '180', '270', '360'],
    optionsEn: ['90', '180', '270', '360'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['360', 'trescientos sesenta'],
    acceptedAnswersEn: ['360', 'three hundred sixty'],
  },
  {
    id: 'math-power-zero',
    category: 'math',
    promptEs: '¿A cuánto equivale cualquier número distinto de cero elevado a la potencia 0?',
    promptEn: 'What is any non-zero number raised to the power of 0 equal to?',
    optionsEs: ['0', '1', 'El mismo número', 'No existe'],
    optionsEn: ['0', '1', 'The same number', 'Does not exist'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['1', 'uno'],
    acceptedAnswersEn: ['1', 'one'],
  },
  {
    id: 'math-triangle-angles',
    category: 'math',
    promptEs: '¿Cuánto suman los ángulos internos de cualquier triángulo?',
    promptEn: 'What is the sum of the internal angles of any triangle?',
    optionsEs: ['90°', '180°', '270°', '360°'],
    optionsEn: ['90°', '180°', '270°', '360°'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['180', '180 grados', 'ciento ochenta'],
    acceptedAnswersEn: ['180', '180 degrees', 'one hundred eighty'],
  },
  {
    id: 'math-diameter-radius',
    category: 'math',
    promptEs: 'Si el radio de un círculo mide 5 cm, ¿cuánto mide su diámetro?',
    promptEn: 'If the radius of a circle is 5 cm, how long is its diameter?',
    optionsEs: ['2.5 cm', '5 cm', '10 cm', '25 cm'],
    optionsEn: ['2.5 cm', '5 cm', '10 cm', '25 cm'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['10', '10 cm', 'diez'],
    acceptedAnswersEn: ['10', '10 cm', 'ten'],
  },
  {
    id: 'math-euler-number',
    category: 'math',
    promptEs: '¿Cuál es una aproximación común del número de Euler (e)?',
    promptEn: 'What is a common approximation of Euler\'s number (e)?',
    optionsEs: ['1.41', '2.72', '3.14', '1.61'],
    optionsEn: ['1.41', '2.72', '3.14', '1.61'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['2.72', '2,72'],
    acceptedAnswersEn: ['2.72'],
  },
  {
    id: 'math-binary-base',
    category: 'math',
    promptEs: '¿Cuántos dígitos utiliza el sistema numérico binario?',
    promptEn: 'How many digits does the binary numeral system use?',
    optionsEs: ['1', '2', '8', '10'],
    optionsEn: ['1', '2', '8', '10'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['2', 'dos'],
    acceptedAnswersEn: ['2', 'two'],
  },
  {
    id: 'math-percent-half',
    category: 'math',
    promptEs: '¿Qué porcentaje representa la fracción 1/4?',
    promptEn: 'What percentage does the fraction 1/4 represent?',
    optionsEs: ['14%', '25%', '40%', '50%'],
    optionsEn: ['14%', '25%', '40%', '50%'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['25%', '25', 'veinticinco por ciento'],
    acceptedAnswersEn: ['25%', '25', 'twenty-five percent'],
  },
  {
    id: 'math-milliliters-liter',
    category: 'math',
    promptEs: '¿Cuántos mililitros hay en un litro?',
    promptEn: 'How many milliliters are in a liter?',
    optionsEs: ['10', '100', '1000', '10000'],
    optionsEn: ['10', '100', '1000', '10000'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['1000', 'mil'],
    acceptedAnswersEn: ['1000', 'one thousand'],
  },
  {
    id: 'math-square-perimeter',
    category: 'math',
    promptEs: 'Si un cuadrado tiene lados de 6 cm, ¿cuál es su perímetro?',
    promptEn: 'If a square has sides of 6 cm, what is its perimeter?',
    optionsEs: ['12 cm', '24 cm', '36 cm', '48 cm'],
    optionsEn: ['12 cm', '24 cm', '36 cm', '48 cm'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['24', '24 cm', 'veinticuatro'],
    acceptedAnswersEn: ['24', '24 cm', 'twenty-four'],
  },
  {
    id: 'math-square-area',
    category: 'math',
    promptEs: 'Si un cuadrado tiene lados de 6 cm, ¿cuál es su área?',
    promptEn: 'If a square has sides of 6 cm, what is its area?',
    optionsEs: ['12 cm²', '24 cm²', '36 cm²', '48 cm²'],
    optionsEn: ['12 cm²', '24 cm²', '36 cm²', '48 cm²'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['36', '36 cm2', 'treinta y seis'],
    acceptedAnswersEn: ['36', '36 cm2', 'thirty-six'],
  },
  {
    id: 'math-hypotenuse-concept',
    category: 'math',
    promptEs: '¿Cómo se llama el lado más largo de un triángulo rectángulo?',
    promptEn: 'What is the longest side of a right triangle called?',
    optionsEs: ['Cateto opuesto', 'Cateto adyacente', 'Hipotenusa', 'Base'],
    optionsEn: ['Opposite side', 'Adjacent side', 'Hypotenuse', 'Base'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['hipotenusa'],
    acceptedAnswersEn: ['hypotenuse'],
  },
  {
    id: 'math-odd-numbers',
    category: 'math',
    promptEs: 'Selecciona los números impares.',
    promptEn: 'Select the odd numbers.',
    optionsEs: ['12', '15', '22', '33'],
    optionsEn: ['12', '15', '22', '33'],
    correctOptionIndexes: [1, 3],
    acceptedAnswersEs: ['15 y 33', '15 33', 'quince y treinta y tres'],
    acceptedAnswersEn: ['15 and 33', '15 33', 'fifteen and thirty-three'],
  },
  {
    id: 'math-seconds-hour',
    category: 'math',
    promptEs: '¿Cuántos segundos hay en una hora?',
    promptEn: 'How many seconds are in an hour?',
    optionsEs: ['60', '1200', '2400', '3600'],
    optionsEn: ['60', '1200', '2400', '3600'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['3600', 'tres mil seiscientos'],
    acceptedAnswersEn: ['3600', 'three thousand six hundred'],
  },
  {
    id: 'math-single-digit-primes',
    category: 'math',
    promptEs: '¿Cuál es el único número primo que también es par?',
    promptEn: 'What is the only prime number that is also even?',
    optionsEs: ['0', '2', '4', '6'],
    optionsEn: ['0', '2', '4', '6'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['2', 'dos'],
    acceptedAnswersEn: ['2', 'two'],
  },
  {
    id: 'math-octagon-sides',
    category: 'math',
    promptEs: '¿Cuántos lados tiene un octágono?',
    promptEn: 'How many sides does an octagon have?',
    optionsEs: ['6', '8', '10', '12'],
    optionsEn: ['6', '8', '10', '12'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['8', 'ocho'],
    acceptedAnswersEn: ['8', 'eight'],
  },
  {
    id: 'math-negative-addition',
    category: 'math',
    promptEs: '¿Cuál es el resultado de (-5) + (-8)?',
    promptEn: 'What is the result of (-5) + (-8)?',
    optionsEs: ['-13', '-3', '3', '13'],
    optionsEn: ['-13', '-3', '3', '13'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['-13', 'menos trece'],
    acceptedAnswersEn: ['-13', 'minus thirteen', 'negative thirteen'],
  },
  {
    id: 'math-golden-ratio',
    category: 'math',
    promptEs: '¿Qué letra griega representa habitualmente a la proporción áurea?',
    promptEn: 'Which Greek letter usually represents the golden ratio?',
    optionsEs: ['Alpha (α)', 'Beta (β)', 'Pi (π)', 'Phi (φ)'],
    optionsEn: ['Alpha (α)', 'Beta (β)', 'Pi (π)', 'Phi (φ)'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['phi', 'fi'],
    acceptedAnswersEn: ['phi'],
  },
  {
    id: 'math-solve-x-mult',
    category: 'math',
    promptEs: 'Si 4x = 32, ¿cuánto vale x?',
    promptEn: 'If 4x = 32, what is x?',
    optionsEs: ['6', '7', '8', '9'],
    optionsEn: ['6', '7', '8', '9'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['8', 'ocho'],
    acceptedAnswersEn: ['8', 'eight'],
  },
  {
    id: 'math-decimal-fraction',
    category: 'math',
    promptEs: '¿Qué fracción equivale al número decimal 0.75?',
    promptEn: 'Which fraction is equivalent to the decimal number 0.75?',
    optionsEs: ['1/2', '2/3', '3/4', '4/5'],
    optionsEn: ['1/2', '2/3', '3/4', '4/5'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['3/4', 'tres cuartos'],
    acceptedAnswersEn: ['3/4', 'three fourths'],
  },
  {
    id: 'math-pentagon-angles',
    category: 'math',
    promptEs: '¿Cuánto suman los ángulos internos de un pentágono regular?',
    promptEn: 'What is the sum of the internal angles of a regular pentagon?',
    optionsEs: ['360°', '540°', '720°', '900°'],
    optionsEn: ['360°', '540°', '720°', '900°'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['540', '540 grados', 'quinientos cuarenta'],
    acceptedAnswersEn: ['540', '540 degrees', 'five hundred forty'],
  },
  {
    id: 'math-google-zeros',
    category: 'math',
    promptEs: '¿Cuántos ceros tiene un gúgol (googol)?',
    promptEn: 'How many zeros does a googol have?',
    optionsEs: ['6', '9', '12', '100'],
    optionsEn: ['6', '9', '12', '100'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['100', 'cien'],
    acceptedAnswersEn: ['100', 'one hundred'],
  },
  {
    id: 'math-cube-root-27',category: 'math',promptEs: '¿Cuál es la raíz cúbica de 27?',promptEn: 'What is the cube root of 27?',optionsEs: ['3', '4', '9', '24'],optionsEn: ['3', '4', '9', '24'],correctOptionIndexes: [0],acceptedAnswersEs: ['3', 'tres'],acceptedAnswersEn: ['3', 'three'],},{id: 'math-obtuse-angle',category: 'math',promptEs: 'Un ángulo obtuso mide más de 90° pero menos de:',promptEn: 'An obtuse angle measures more than 90° but less than:',optionsEs: ['120°', '180°', '270°', '360°'],optionsEn: ['120°', '180°', '270°', '360°'],correctOptionIndexes: [1],acceptedAnswersEs: ['180', '180 grados', 'ciento ochenta'],acceptedAnswersEn: ['180', '180 degrees', 'one hundred eighty'],},{id: 'math-composite-numbers',category: 'math',promptEs: 'Selecciona los números compuestos (no primos).',promptEn: 'Select the composite (non-prime) numbers.',optionsEs: ['2', '6', '11', '15'],optionsEn: ['2', '6', '11', '15'],correctOptionIndexes: [1, 3],acceptedAnswersEs: ['6 y 15', '6 15', 'seis y quince'],acceptedAnswersEn: ['6 and 15', '6 15', 'six and fifteen'],},{id: 'math-isogoni-triangle',category: 'math',promptEs: '¿Cómo se llama el triángulo que tiene todos sus lados iguales?',promptEn: 'What is a triangle with all equal sides called?',optionsEs: ['Isósceles', 'Escaleno', 'Equilátero', 'Rectángulo'],optionsEn: ['Isosceles', 'Scalene', 'Equilateral', 'Right'],correctOptionIndexes: [2],acceptedAnswersEs: ['equilatero', 'equilátero'],acceptedAnswersEn: ['equilateral'],},{id: 'math-dice-probability',category: 'math',promptEs: 'Al lanzar un dado estándar, ¿cuál es la probabilidad de sacar un 6?',promptEn: 'When rolling a standard die, what is the probability of getting a 6?',optionsEs: ['1/2', '1/4', '1/6', '1/8'],optionsEn: ['1/2', '1/4', '1/6', '1/8'],correctOptionIndexes: [2],acceptedAnswersEs: ['1/6', 'un sexto'],acceptedAnswersEn: ['1/6', 'one sixth'],},{id: 'math-grams-kilo',category: 'math',promptEs: '¿Cuántos gramos hay en un kilogramo?',promptEn: 'How many grams are in a kilogram?',optionsEs: ['100', '500', '1000', '10000'],optionsEn: ['100', '500', '1000', '10000'],correctOptionIndexes: [2],acceptedAnswersEs: ['1000', 'mil'],acceptedAnswersEn: ['1000', 'one thousand'],},{id: 'math-quadrilateral-sides',category: 'math',promptEs: '¿Cuántos lados tiene cualquier cuadrilátero?',promptEn: 'How many sides does any quadrilateral have?',optionsEs: ['3', '4', '5', '6'],optionsEn: ['3', '4', '5', '6'],correctOptionIndexes: [1],acceptedAnswersEs: ['4', 'cuatro'],acceptedAnswersEn: ['4', 'four'],},{id: 'math-mode-concept',category: 'math',promptEs: 'En estadística, ¿cómo se llama el valor estadístico que más veces se repite?',promptEn: 'In statistics, what is the value that appears most frequently called?',optionsEs: ['Media', 'Mediana', 'Moda', 'Varianza'],optionsEn: ['Mean', 'Median', 'Mode', 'Variance'],correctOptionIndexes: [2],acceptedAnswersEs: ['moda'],acceptedAnswersEn: ['mode'],},{id: 'math-power-three-two',category: 'math',promptEs: '¿Cuál es el resultado de 3 elevado a la potencia 2 (3²)?',promptEn: 'What is the result of 3 raised to the power of 2 (3²)?',optionsEs: ['6', '8', '9', '27'],optionsEn: ['6', '8', '9', '27'],correctOptionIndexes: [2],acceptedAnswersEs: ['9', 'nueve'],acceptedAnswersEn: ['9', 'nine'],},{id: 'math-power-two-three',category: 'math',promptEs: '¿Cuál es el resultado de 2 elevado a la potencia 3 (2³)?',promptEn: 'What is the result of 2 raised to the power of 3 (2³)?',optionsEs: ['6', '8', '9', '16'],optionsEn: ['6', '8', '9', '16'],correctOptionIndexes: [1],acceptedAnswersEs: ['8', 'ocho'],acceptedAnswersEn: ['8', 'eight'],},



];
