import { TriviaQuestion } from '../types/trivia.types';

export const MUSIC_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'music-notes',
    category: 'music',
    promptEs: 'Selecciona notas musicales.',
    promptEn: 'Select musical notes.',
    optionsEs: ['Do', 'Sol', 'La', 'Kilómetro'],
    optionsEn: ['C', 'G', 'A', 'Kilometer'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['do sol la'],
    acceptedAnswersEn: ['c g a', 'do sol la'],
  },
  {
    id: 'music-instrument-keys',
    category: 'music',
    promptEs: '¿Qué instrumento se toca principalmente con teclas?',
    promptEn: 'Which instrument is primarily played with keys?',
    optionsEs: ['Piano', 'Tambor', 'Maraca', 'Platillo'],
    optionsEn: ['Piano', 'Drum', 'Maraca', 'Cymbal'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['piano'],
    acceptedAnswersEn: ['piano'],
  },
  {
    id: 'music-beethoven',
    category: 'music',
    promptEs: '¿Quién compuso la Novena Sinfonía?',
    promptEn: 'Who composed the Ninth Symphony?',
    optionsEs: ['Mozart', 'Beethoven', 'Vivaldi', 'Chopin'],
    optionsEn: ['Mozart', 'Beethoven', 'Vivaldi', 'Chopin'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['beethoven', 'ludwig van beethoven'],
    acceptedAnswersEn: ['beethoven', 'ludwig van beethoven'],
  },
  {
    id: 'music-clefs',
    category: 'music',
    promptEs: 'Selecciona claves musicales.',
    promptEn: 'Select musical clefs.',
    optionsEs: ['Sol', 'Fa', 'Do', 'Metro'],
    optionsEn: ['Treble', 'Bass', 'Alto', 'Meter'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['sol fa do', 'clave de sol', 'clave de fa'],
    acceptedAnswersEn: ['treble bass alto', 'treble and bass'],
  },
  {
    id: 'music-tempo',
    category: 'music',
    promptEs: '¿Qué término indica un tempo muy rápido?',
    promptEn: 'Which term indicates a very fast tempo?',
    optionsEs: ['Adagio', 'Andante', 'Allegro', 'Presto'],
    optionsEn: ['Adagio', 'Andante', 'Allegro', 'Presto'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['presto'],
    acceptedAnswersEn: ['presto'],
  },
  {
    id: 'music-guitar-strings',
    category: 'music',
    promptEs: '¿Cuántas cuerdas tiene una guitarra estándar?',
    promptEn: 'How many strings does a standard guitar have?',
    optionsEs: ['4', '5', '6', '12'],
    optionsEn: ['4', '5', '6', '12'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['6', 'seis'],
    acceptedAnswersEn: ['6', 'six'],
  },
  {
    id: 'music-mozart-country',
    category: 'music',
    promptEs: '¿En qué país nació Wolfgang Amadeus Mozart?',
    promptEn: 'In which country was Wolfgang Amadeus Mozart born?',
    optionsEs: ['Alemania', 'Austria', 'Francia', 'Italia'],
    optionsEn: ['Germany', 'Austria', 'France', 'Italy'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['austria'],
    acceptedAnswersEn: ['austria'],
  },
  {
    id: 'music-woodwind',
    category: 'music',
    promptEs: 'Selecciona instrumentos de viento madera.',
    promptEn: 'Select woodwind instruments.',
    optionsEs: ['Flauta', 'Clarín', 'Oboe', 'Trompeta'],
    optionsEn: ['Flute', 'Clarinet', 'Oboe', 'Trumpet'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['flauta clarin oboe', 'flauta clarinete oboe'],
    acceptedAnswersEn: ['flute clarinet oboe'],
  },
  {
    id: 'music-beatles-members',
    category: 'music',
    promptEs: 'Selecciona integrantes de The Beatles.',
    promptEn: 'Select members of The Beatles.',
    optionsEs: ['John Lennon', 'Paul McCartney', 'Mick Jagger', 'Ringo Starr'],
    optionsEn: ['John Lennon', 'Paul McCartney', 'Mick Jagger', 'Ringo Starr'],
    correctOptionIndexes: [0, 1, 3],
    acceptedAnswersEs: ['john paul ringo', 'lennon mccartney starr'],
    acceptedAnswersEn: ['john paul ringo', 'lennon mccartney starr'],
  },
  {
    id: 'music-reggae-king',
    category: 'music',
    promptEs: '¿Quién es considerado el Rey del Reggae?',
    promptEn: 'Who is considered the King of Reggae?',
    optionsEs: ['Bob Marley', 'Peter Tosh', 'Jimmy Cliff', 'Sean Paul'],
    optionsEn: ['Bob Marley', 'Peter Tosh', 'Jimmy Cliff', 'Sean Paul'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['bob marley', 'marley'],
    acceptedAnswersEn: ['bob marley', 'marley'],
  },
  {
    id: 'music-dynamic-loud',
    category: 'music',
    promptEs: '¿Qué término italiano significa tocar fuerte?',
    promptEn: 'Which Italian term means to play loudly?',
    optionsEs: ['Piano', 'Forte', 'Mezzo', 'Crescendo'],
    optionsEn: ['Piano', 'Forte', 'Mezzo', 'Crescendo'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['forte'],
    acceptedAnswersEn: ['forte'],
  },
  {
    id: 'music-bow-instruments',
    category: 'music',
    promptEs: 'Selecciona instrumentos que usan arco.',
    promptEn: 'Select instruments played with a bow.',
    optionsEs: ['Violín', 'Violonchelo', 'Arpa', 'Contrabajo'],
    optionsEn: ['Violin', 'Cello', 'Harp', 'Double bass'],
    correctOptionIndexes: [0, 1, 3],
    acceptedAnswersEs: ['violin violonchelo contrabajo', 'violin cello contrabajo'],
    acceptedAnswersEn: ['violin cello double bass'],
  },
  {
    id: 'music-queen-singer',
    category: 'music',
    promptEs: '¿Quién era el cantante principal de la banda Queen?',
    promptEn: 'Who was the lead singer of the band Queen?',
    optionsEs: ['Freddie Mercury', 'Brian May', 'David Bowie', 'Elton John'],
    optionsEn: ['Freddie Mercury', 'Brian May', 'David Bowie', 'Elton John'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['freddie mercury', 'mercury'],
    acceptedAnswersEn: ['freddie mercury', 'mercury'],
  },
  {
    id: 'music-percussion',
    category: 'music',
    promptEs: 'Selecciona instrumentos de percusión.',
    promptEn: 'Select percussion instruments.',
    optionsEs: ['Tambor', 'Xilófono', 'Flauta', 'Triángulo'],
    optionsEn: ['Drum', 'Xylophone', 'Flute', 'Triangle'],
    correctOptionIndexes: [0, 1, 3],
    acceptedAnswersEs: ['tambor xilofono triangulo'],
    acceptedAnswersEn: ['drum xylophone triangle'],
  },
  {
    id: 'music-four-seasons',
    category: 'music',
    promptEs: '¿Quién compuso Las Cuatro Estaciones?',
    promptEn: 'Who composed The Four Seasons?',
    optionsEs: ['Bach', 'Vivaldi', 'Handel', 'Telemann'],
    optionsEn: ['Bach', 'Vivaldi', 'Handel', 'Telemann'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['vivaldi', 'antonio vivaldi'],
    acceptedAnswersEn: ['vivaldi', 'antonio vivaldi'],
  },
  {
    id: 'music-pop-king',
    category: 'music',
    promptEs: '¿Quién es conocido mundialmente como el Rey del Pop?',
    promptEn: 'Who is globally known as the King of Pop?',
    optionsEs: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Madonna'],
    optionsEn: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Madonna'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['michael jackson', 'jackson'],
    acceptedAnswersEn: ['michael jackson', 'jackson'],
  },
  {
    id: 'music-brass',
    category: 'music',
    promptEs: 'Selecciona instrumentos de viento metal.',
    promptEn: 'Select brass instruments.',
    optionsEs: ['Trompeta', 'Trombón', 'Tuba', 'Fagot'],
    optionsEn: ['Trumpet', 'Trombone', 'Tuba', 'Bassoon'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['trompeta trombon tuba'],
    acceptedAnswersEn: ['trumpet trombone tuba'],
  },
  {
    id: 'music-opera-voice',
    category: 'music',
    promptEs: '¿Cuál es la voz masculina más aguda en la ópera?',
    promptEn: 'What is the highest male voice type in opera?',
    optionsEs: ['Tenor', 'Barítono', 'Bajo', 'Soprano'],
    optionsEn: ['Tenor', 'Baritone', 'Bass', 'Soprano'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['tenor'],
    acceptedAnswersEn: ['tenor'],
  },
  {
    id: 'music-national-anthem-us',
    category: 'music',
    promptEs: '¿Cómo se llama el himno nacional de EE. UU.?',
    promptEn: 'What is the national anthem of the USA called?',
    optionsEs: ['God Save the Queen', 'The Star-Spangled Banner', 'La Marsellesa', 'America'],
    optionsEn: ['God Save the Queen', 'The Star-Spangled Banner', 'La Marseillaise', 'America'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['the star-spangled banner', 'star-spangled banner'],
    acceptedAnswersEn: ['the star-spangled banner', 'star-spangled banner'],
  },
  {
    id: 'music-sharp-sign',
    category: 'music',
    promptEs: '¿Qué símbolo musical eleva una nota un semitono?',
    promptEn: 'Which musical symbol raises a pitch by a half step?',
    optionsEs: ['Bemol', 'Sostenido', 'Becuadro', 'Clave'],
    optionsEn: ['Flat', 'Sharp', 'Natural', 'Clef'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['sostenido'],
    acceptedAnswersEn: ['sharp'],
  },
  {
    id: 'music-jazz-instruments',
    category: 'music',
    promptEs: 'Selecciona instrumentos icónicos del Jazz.',
    promptEn: 'Select iconic Jazz instruments.',
    optionsEs: ['Saxofón', 'Trompeta', 'Contrabajo', 'Acordeón'],
    optionsEn: ['Saxophone', 'Trumpet', 'Double bass', 'Accordion'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['saxofon trompeta contrabajo', 'saxo trompeta contrabajo'],
    acceptedAnswersEn: ['saxophone trumpet double bass'],
  },
  {
    id: 'music-chopin-instrument',
    category: 'music',
    promptEs: '¿Para qué instrumento compuso principalmente Frédéric Chopin?',
    promptEn: 'For which instrument did Frédéric Chopin primarily compose?',
    optionsEs: ['Violín', 'Flauta', 'Piano', 'Órgano'],
    optionsEn: ['Violin', 'Flute', 'Piano', 'Organ'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['piano'],
    acceptedAnswersEn: ['piano'],
  },
  {
    id: 'music-interval-unison',
    category: 'music',
    promptEs: '¿Cómo se llama el intervalo entre dos notas de la misma frecuencia?',
    promptEn: 'What is the interval between two notes of the same pitch called?',
    optionsEs: ['Tercera', 'Quinta', 'Octava', 'Unísono'],
    optionsEn: ['Third', 'Fifth', 'Octave', 'Unison'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['unisono', 'unísono'],
    acceptedAnswersEn: ['unison'],
  },
  {
    id: 'music-pink-floyd-album',
    category: 'music',
    promptEs: '¿Qué álbum icónico de Pink Floyd muestra un prisma en su portada?',
    promptEn: 'Which iconic Pink Floyd album features a prism on its cover?',
    optionsEs: ['The Wall', 'Animals', 'The Dark Side of the Moon', 'Wish You Were Here'],
    optionsEn: ['The Wall', 'Animals', 'The Dark Side of the Moon', 'Wish You Were Here'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['the dark side of the moon', 'dark side of the moon'],
    acceptedAnswersEn: ['the dark side of the moon', 'dark side of the moon'],
  },
  {
    id: 'music-female-voices',
    category: 'music',
    promptEs: 'Selecciona tipos de voces femeninas.',
    promptEn: 'Select female voice types.',
    optionsEs: ['Soprano', 'Contralto', 'Mezzosoprano', 'Barítono'],
    optionsEn: ['Soprano', 'Contralto', 'Mezzosoprano', 'Baritone'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['soprano contralto mezzosoprano'],
    acceptedAnswersEn: ['soprano contralto mezzosoprano'],
  },
  {
    id: 'music-reggaeton-origin',
    category: 'music',
    promptEs: '¿Qué isla caribeña es la cuna principal del Reggaetón?',promptEn: 'Which Caribbean island is the primary birthplace of Reggaeton?',optionsEs: ['Cuba', 'Puerto Rico', 'Jamaica', 'República Dominicana'],optionsEn: ['Cuba', 'Puerto Rico', 'Jamaica', 'Dominican Republic'],correctOptionIndexes: [1],acceptedAnswersEs: ['puerto rico'],acceptedAnswersEn: ['puerto rico'],},{id: 'music-electronic-pioneers',category: 'music',promptEs: 'Selecciona artistas influyentes de la música electrónica.',promptEn: 'Select influential electronic music artists.',optionsEs: ['Kraftwerk', 'Daft Punk', 'Avicii', 'Beethoven'],optionsEn: ['Kraftwerk', 'Daft Punk', 'Avicii', 'Beethoven'],correctOptionIndexes: [0, 1, 2],acceptedAnswersEs: ['kraftwerk daft punk avicii'],acceptedAnswersEn: ['kraftwerk daft punk avicii'],},{id: 'music-woodstock-year',category: 'music',promptEs: '¿En qué año se celebró el festival original de Woodstock?',promptEn: 'In what year was the original Woodstock festival held?',optionsEs: ['1965', '1969', '1972', '1975'],optionsEn: ['1965', '1969', '1972', '1975'],correctOptionIndexes: [1],acceptedAnswersEs: ['1969'],acceptedAnswersEn: ['1969'],},{id: 'music-flat-sign',category: 'music',promptEs: '¿Qué símbolo musical reduce una nota un semitono?',promptEn: 'Which musical symbol lowers a pitch by a half step?',optionsEs: ['Sostenido', 'Bemol', 'Becuadro', 'Acento'],optionsEn: ['Sharp', 'Flat', 'Natural', 'Accent'],correctOptionIndexes: [1],acceptedAnswersEs: ['bemol'],acceptedAnswersEn: ['flat'],},{id: 'music-string-plucked',category: 'music',promptEs: 'Selecciona instrumentos de cuerda pulsada.',promptEn: 'Select plucked string instruments.',optionsEs: ['Arpa', 'Guitarra', 'Ukelele', 'Violín'],optionsEn: ['Harp', 'Guitar', 'Ukulele', 'Violin'],correctOptionIndexes: [0, 1, 2],acceptedAnswersEs: ['arpa guitarra ukelele'],acceptedAnswersEn: ['harp guitar ukulele'],},{id: 'music-metronome',category: 'music',promptEs: '¿Qué aparato se utiliza para medir el tempo musical?',promptEn: 'What device is used to measure musical tempo?',optionsEs: ['Afinador', 'Metrónomo', 'Diapasón', 'Podómetro'],optionsEn: ['Tuner', 'Metronome', 'Tuning fork', 'Podometer'],correctOptionIndexes: [1],acceptedAnswersEs: ['metronomo', 'metrónomo'],acceptedAnswersEn: ['metronome'],},{id: 'music-thriller-artist',category: 'music',promptEs: '¿Qué artista lanzó el álbum "Thriller" en 1982?',promptEn: 'Which artist released the album "Thriller" in 1982?',optionsEs: ['Prince', 'Michael Jackson', 'Madonna', 'David Bowie'],optionsEn: ['Prince', 'Michael Jackson', 'Madonna', 'David Bowie'],correctOptionIndexes: [1],acceptedAnswersEs: ['michael jackson', 'jackson'],acceptedAnswersEn: ['michael jackson', 'jackson'],},{id: 'music-stave-lines',category: 'music',promptEs: '¿Cuántas líneas tiene un pentagrama estándar?',promptEn: 'How many lines does a standard musical staff have?',optionsEs: ['4', '5', '6', '7'],optionsEn: ['4', '5', '6', '7'],correctOptionIndexes: [1],acceptedAnswersEs: ['5', 'cinco'],acceptedAnswersEn: ['5', 'five'],},

  {
    id: 'music-nirvana-singer',
    category: 'music',
    promptEs: '¿Quién era el cantante principal de la banda Nirvana?',
    promptEn: 'Who was the lead singer of the band Nirvana?',
    optionsEs: ['Kurt Cobain', 'Eddie Vedder', 'Chris Cornell', 'Axl Rose'],
    optionsEn: ['Kurt Cobain', 'Eddie Vedder', 'Chris Cornell', 'Axl Rose'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['kurt cobain', 'cobain'],
    acceptedAnswersEn: ['kurt cobain', 'cobain'],
  },
  {
    id: 'music-major-triad',
    category: 'music',
    promptEs: 'Selecciona las notas que forman la tríada de Do Mayor.',
    promptEn: 'Select the notes that form the C Major triad.',
    optionsEs: ['Do', 'Mi', 'Sol', 'Si'],
    optionsEn: ['C', 'E', 'G', 'B'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['do mi sol'],
    acceptedAnswersEn: ['c e g', 'do mi sol'],
  },
  {
    id: 'music-reggae-origin-country',
    category: 'music',
    promptEs: '¿En qué país se originó la música Reggae?',
    promptEn: 'In which country did Reggae music originate?',
    optionsEs: ['Cuba', 'Jamaica', 'Bahamas', 'Haití'],
    optionsEn: ['Cuba', 'Jamaica', 'Bahamas', 'Haiti'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['jamaica'],
    acceptedAnswersEn: ['jamaica'],
  },
  {
    id: 'music-bow-parts',
    category: 'music',
    promptEs: 'Selecciona partes que forman un arco de violín.',
    promptEn: 'Select parts that make up a violin bow.',
    optionsEs: ['Nuez', 'Vara', 'Cerdas', 'Puente'],
    optionsEn: ['Frog', 'Stick', 'Hair', 'Bridge'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['nuez vara cerdas'],
    acceptedAnswersEn: ['frog stick hair'],
  },
  {
    id: 'music-vivaldi-nationality',
    category: 'music',
    promptEs: '¿De qué nacionalidad era el compositor Antonio Vivaldi?',
    promptEn: 'What nationality was the composer Antonio Vivaldi?',
    optionsEs: ['Española', 'Italiana', 'Francesa', 'Alemana'],
    optionsEn: ['Spanish', 'Italian', 'French', 'German'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['italiana', 'italiano'],
    acceptedAnswersEn: ['italian'],
  },
  {
    id: 'music-led-zeppelin-song',
    category: 'music',
    promptEs: '¿Qué famosa canción de Led Zeppelin habla de una "escalera"?',
    promptEn: 'Which famous Led Zeppelin song talks about a "stairway"?',
    optionsEs: ['Stairway to Heaven', 'Whole Lotta Love', 'Kashmir', 'Black Dog'],
    optionsEn: ['Stairway to Heaven', 'Whole Lotta Love', 'Kashmir', 'Black Dog'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['stairway to heaven'],
    acceptedAnswersEn: ['stairway to heaven'],
  },
  {
    id: 'music-double-bass-size',
    category: 'music',
    promptEs: '¿Cuál es el instrumento más grande y grave de la familia del violín?',
    promptEn: 'What is the largest and lowest-pitched instrument in the violin family?',
    optionsEs: ['Viola', 'Violonchelo', 'Contrabajo', 'Arpa'],
    optionsEn: ['Viola', 'Cello', 'Double bass', 'Harp'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['contrabajo'],
    acceptedAnswersEn: ['double bass', 'contrabass'],
  },
  {
    id: 'music-rock-pioneers',
    category: 'music',
    promptEs: 'Selecciona pioneros históricos del Rock and Roll.',
    promptEn: 'Select historical pioneers of Rock and Roll.',
    optionsEs: ['Elvis Presley', 'Chuck Berry', 'Little Richard', 'Eminem'],
    optionsEn: ['Elvis Presley', 'Chuck Berry', 'Little Richard', 'Eminem'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['elvis presley chuck berry little richard', 'elvis chuck little richard'],
    acceptedAnswersEn: ['elvis presley chuck berry little richard', 'elvis chuck little richard'],
  },
  {
    id: 'music-bach-era',
    category: 'music',
    promptEs: '¿A qué período musical perteneció Johann Sebastian Bach?',
    promptEn: 'To which musical period did Johann Sebastian Bach belong?',
    optionsEs: ['Renacimiento', 'Barroco', 'Clasicismo', 'Románticismo'],
    optionsEn: ['Renaissance', 'Baroque', 'Classical', 'Romantic'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['barroco'],
    acceptedAnswersEn: ['baroque'],
  },
  {
    id: 'music-woodwind-reeds',
    category: 'music',
    promptEs: 'Selecciona instrumentos de viento que usan caña o lengüeta.',
    promptEn: 'Select woodwind instruments that use a reed.',
    optionsEs: ['Clarinete', 'Oboe', 'Saxofón', 'Flauta Travesera'],
    optionsEn: ['Clarinet', 'Oboe', 'Saxophone', 'Flute'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['clarinete oboe saxofon', 'clarinete oboe saxo'],
    acceptedAnswersEn: ['clarinet oboe saxophone'],
  },
  {
    id: 'music-opera-italy',
    category: 'music',
    promptEs: '¿En qué país nació el género de la ópera?',
    promptEn: 'In which country did the opera genre originate?',
    optionsEs: ['Francia', 'Italia', 'Austria', 'España'],
    optionsEn: ['France', 'Italy', 'Austria', 'Spain'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['italia'],
    acceptedAnswersEn: ['italy'],
  },
  {
    id: 'music-hybrid-instruments',
    category: 'music',
    promptEs: 'Selecciona instrumentos que combinan teclado y cuerdas.',
    promptEn: 'Select instruments that combine a keyboard and strings.',
    optionsEs: ['Piano', 'Clavicordio', 'Órgano de tubos', 'Sintetizador'],
    optionsEn: ['Piano', 'Clavichord', 'Pipe organ', 'Synthesizer'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['piano clavicordio', 'piano y clavicordio'],
    acceptedAnswersEn: ['piano clavichord', 'piano and clavichord'],
  },
  {
    id: 'music-tango-country',
    category: 'music',
    promptEs: '¿Con qué país se asocia principalmente el origen del Tango?',
    promptEn: 'With which country is the origin of Tango primarily associated?',
    optionsEs: ['Brasil', 'Argentina', 'Colombia', 'México'],
    optionsEn: ['Brazil', 'Argentina', 'Colombia', 'Mexico'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['argentina'],
    acceptedAnswersEn: ['argentina'],
  },
  {
    id: 'music-silence-symbols',
    category: 'music',
    promptEs: 'Selecciona figuras que representan silencios en el pentagrama.',
    promptEn: 'Select figures that represent rests on the musical staff.',
    optionsEs: ['Silencio de negra', 'Silencio de blanca', 'Clave de Sol', 'Línea divisoria'],
    optionsEn: ['Quarter rest', 'Half rest', 'Treble clef', 'Bar line'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['silencio de negra silencio de blanca', 'silencios'],
    acceptedAnswersEn: ['quarter rest half rest', 'rests'],
  },
  {
    id: 'music-metallica-genre',
    category: 'music',
    promptEs: '¿Qué género musical define principalmente a la banda Metallica?',
    promptEn: 'Which musical genre primarily defines the band Metallica?',
    optionsEs: ['Heavy Metal / Thrash Metal', 'Jazz Fusion', 'Reggae', 'Pop Rock'],
    optionsEn: ['Heavy Metal / Thrash Metal', 'Jazz Fusion', 'Reggae', 'Pop Rock'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['heavy metal', 'thrash metal', 'metal'],
    acceptedAnswersEn: ['heavy metal', 'thrash metal', 'metal'],
  },
  {
    id: 'music-miles-davis-instrument',
    category: 'music',
    promptEs: '¿Qué instrumento tocaba la leyenda del jazz Miles Davis?',
    promptEn: 'What instrument did jazz legend Miles Davis play?',
    optionsEs: ['Saxofón', 'Trompeta', 'Piano', 'Batería'],
    optionsEn: ['Saxophone', 'Trumpet', 'Piano', 'Drums'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['trompeta'],
    acceptedAnswersEn: ['trumpet'],
  },
  {
    id: 'music-electronic-subgenres',
    category: 'music',
    promptEs: 'Selecciona subgéneros válidos de la música electrónica.',
    promptEn: 'Select valid subgenres of electronic music.',
    optionsEs: ['House', 'Techno', 'Dubstep', 'Salsa'],
    optionsEn: ['House', 'Techno', 'Dubstep', 'Salsa'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['house techno dubstep'],
    acceptedAnswersEn: ['house techno dubstep'],
  },
  {
    id: 'music-daft-punk-country',
    category: 'music',
    promptEs: '¿De qué país era originario el dúo electrónico Daft Punk?',
    promptEn: 'From which country was the electronic duo Daft Punk?',
    optionsEs: ['Reino Unido', 'Estados Unidos', 'Francia', 'Alemania'],
    optionsEn: ['United Kingdom', 'United States', 'France', 'Germany'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['francia'],
    acceptedAnswersEn: ['france'],
  },
  {
    id: 'music-woodwind-no-reed',
    category: 'music',
    promptEs: '¿Qué instrumento de viento madera no utiliza caña?',
    promptEn: 'Which woodwind instrument does not use a reed?',
    optionsEs: ['Oboe', 'Fagot', 'Flauta Travesera', 'Clarinete'],
    optionsEn: ['Oboe', 'Bassoon', 'Flute', 'Clarinet'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['flauta travesera', 'flauta'],
    acceptedAnswersEn: ['flute'],
  },
  {
    id: 'music-queen-members',
    category: 'music',
    promptEs: 'Selecciona integrantes originales de la banda Queen.',
    promptEn: 'Select original members of the band Queen.',
    optionsEs: ['Brian May', 'Roger Taylor', 'John Deacon', 'Mick Jagger'],
    optionsEn: ['Brian May', 'Roger Taylor', 'John Deacon', 'Mick Jagger'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['brian may roger taylor john deacon', 'may taylor deacon'],
    acceptedAnswersEn: ['brian may roger taylor john deacon', 'may taylor deacon'],
  },
  {
    id: 'music-stravinsky-work',
    category: 'music',
    promptEs: '¿Qué ballet compuso Igor Stravinsky que causó un disturbio en su estreno?',
    promptEn: 'Which ballet did Igor Stravinsky compose that caused a riot at its premiere?',
    optionsEs: ['El lago de los cisnes', 'La consagración de la primavera', 'El cascanueces', 'Giselle'],
    optionsEn: ['Swan Lake', 'The Rite of Spring', 'The Nutcracker', 'Giselle'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['la consagracion de la primavera', 'consagracion de la primavera'],acceptedAnswersEn: ['the rite of spring', 'rite of spring'],},{id: 'music-monophonic-texture',category: 'music',promptEs: '¿Cómo se llama la textura musical que consta de una sola línea melódica sin acompañamiento?',promptEn: 'What is the musical texture consisting of a single unaccompanied melodic line called?',optionsEs: ['Monofonía', 'Polifonía', 'Homofonía', 'Heterofonía'],optionsEn: ['Monophony', 'Polyphony', 'Homophony', 'Heterophony'],correctOptionIndexes: [0],acceptedAnswersEs: ['monofonia', 'monofonía'],acceptedAnswersEn: ['monophony'],},{id: 'music-acdc-guitarist',category: 'music',promptEs: '¿Quién es el icónico guitarrista principal de AC/DC conocido por su uniforme escolar?',promptEn: 'Who is the iconic lead guitarist of AC/DC known for his schoolboy uniform?',optionsEs: ['Angus Young', 'Malcolm Young', 'Slash', 'Keith Richards'],optionsEn: ['Angus Young', 'Malcolm Young', 'Slash', 'Keith Richards'],correctOptionIndexes: [0],acceptedAnswersEs: ['angus young', 'angus'],acceptedAnswersEn: ['angus young', 'angus'],},{id: 'music-percussion-pitched',category: 'music',promptEs: 'Selecciona instrumentos de percusión afinados (que producen notas determinadas).',promptEn: 'Select tuned percussion instruments (that produce definite pitches).',optionsEs: ['Xilófono', 'Marimba', 'Timbales', 'Bombo'],optionsEn: ['Xylophone', 'Marimba', 'Timpani', 'Bass drum'],correctOptionIndexes: [0, 1, 2],acceptedAnswersEs: ['xilofono marimba timbales'],acceptedAnswersEn: ['xylophone marimba timpani'],},{id: 'music-madonna-title',category: 'music',promptEs: '¿Qué título honorífico recibe la artista estadounidense Madonna?',promptEn: 'What honorary title is given to the American artist Madonna?',optionsEs: ['Reina del Pop', 'Princesa del Pop', 'Diva del Soul', 'Reina del Rock'],optionsEn: ['Queen of Pop', 'Princess of Pop', 'Diva of Soul', 'Queen of Rock'],correctOptionIndexes: [0],acceptedAnswersEs: ['reina del pop'],acceptedAnswersEn: ['queen of pop'],},{id: 'music-scale-degrees',category: 'music',promptEs: '¿Cuántas notas diferentes componen una escala diatónica estándar?',promptEn: 'How many different notes make up a standard diatonic scale?',optionsEs: ['5', '7', '12', '8'],optionsEn: ['5', '7', '12', '8'],correctOptionIndexes: [1],acceptedAnswersEs: ['7', 'siete'],acceptedAnswersEn: ['7', 'seven'],},{id: 'music-orchestra-sections',category: 'music',promptEs: 'Selecciona las secciones o familias principales de una orquesta sinfónica.',promptEn: 'Select the main sections or families of a symphony orchestra.',optionsEs: ['Cuerdas', 'Viento madera', 'Viento metal', 'Percusión'],optionsEn: ['Strings', 'Woodwinds', 'Brass', 'Percussion'],correctOptionIndexes: [0, 1, 2, 3],acceptedAnswersEs: ['cuerdas viento madera viento metal percusion', 'todas'],acceptedAnswersEn: ['strings woodwinds brass percussion', 'all'],},{id: 'music-jimi-hendrix-instrument',category: 'music',promptEs: '¿Qué instrumento hizo famoso a Jimi Hendrix?',promptEn: 'What instrument made Jimi Hendrix famous?',optionsEs: ['Bajo', 'Batería', 'Guitarra eléctrica', 'Teclado'],optionsEn: ['Bass', 'Drums', 'Electric guitar', 'Keyboard'],correctOptionIndexes: [2],acceptedAnswersEs: ['guitarra electrica', 'guitarra'],acceptedAnswersEn: ['electric guitar', 'guitar'],},{id: 'music-subwoofer-frequencies',category: 'music',promptEs: '¿Qué rango de frecuencias está diseñado para reproducir un altavoz subwoofer?',promptEn: 'Which frequency range is a subwoofer speaker designed to reproduce?',optionsEs: ['Agudas', 'Medias', 'Graves / Subgraves', 'Ultrasónicas'],optionsEn: ['High', 'Mid', 'Low / Sub-bass', 'Ultrasonic'],correctOptionIndexes: [2],acceptedAnswersEs: ['graves', 'subgraves'],acceptedAnswersEn: ['low', 'sub-bass', 'bass'],},{id: 'music-elvis-title',category: 'music',promptEs: '¿Quién es ampliamente recordado como el Rey del Rock and Roll?',promptEn: 'Who is widely remembered as the King of Rock and Roll?',optionsEs: ['Chuck Berry', 'Elvis Presley', 'Buddy Holly', 'Johnny Cash'],optionsEn: ['Chuck Berry', 'Elvis Presley', 'Buddy Holly', 'Johnny Cash'],correctOptionIndexes: [1],acceptedAnswersEs: ['elvis presley', 'elvis'],acceptedAnswersEn: ['elvis presley', 'elvis'],}

];
