import { TriviaQuestion } from '../types/trivia.types';

export const SCIENCE_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'science-planets',
    category: 'science',
    promptEs: 'Selecciona planetas del sistema solar.',
    promptEn: 'Select planets in the solar system.',
    optionsEs: ['Marte', 'Venus', 'Luna', 'Plutón'],
    optionsEn: ['Mars', 'Venus', 'Moon', 'Pluto'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['marte venus', 'marte y venus'],
    acceptedAnswersEn: ['mars venus', 'mars and venus'],
  },
  {
    id: 'science-water',
    category: 'science',
    promptEs: '¿Cuál es la fórmula química del agua?',
    promptEn: 'What is the chemical formula for water?',
    optionsEs: ['CO2', 'H2O', 'O2', 'NaCl'],
    optionsEn: ['CO2', 'H2O', 'O2', 'NaCl'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['h2o', 'h 2 o'],
    acceptedAnswersEn: ['h2o', 'h 2 o'],
  },
  {
    id: 'science-photosynthesis',
    category: 'science',
    promptEs: '¿Qué proceso usan las plantas para producir alimento con luz?',
    promptEn: 'What process do plants use to make food using light?',
    optionsEs: ['Fotosíntesis', 'Erosión', 'Evaporación', 'Combustión'],
    optionsEn: ['Photosynthesis', 'Erosion', 'Evaporation', 'Combustion'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['fotosintesis', 'fotosíntesis'],
    acceptedAnswersEn: ['photosynthesis'],
  },
   {
    id: 'science-gravity-scientist',
    category: 'science',
    promptEs: '¿Qué científico formuló la ley de la gravitación universal?',
    promptEn: 'Which scientist formulated the law of universal gravitation?',
    optionsEs: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'],
    optionsEn: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['isaac newton', 'newton'],
    acceptedAnswersEn: ['isaac newton', 'newton'],
  },
  {
    id: 'science-blood-cells',
    category: 'science',
    promptEs: 'Selecciona los componentes principales de la sangre humana.',
    promptEn: 'Select the main components of human blood.',
    optionsEs: ['Glóbulos rojos', 'Plaquetas', 'Clorofila', 'Neuronas'],
    optionsEn: ['Red blood cells', 'Platelets', 'Chlorophyll', 'Neurons'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['globulos rojos plaquetas', 'globulos rojos y plaquetas'],
    acceptedAnswersEn: ['red blood cells platelets', 'red blood cells and platelets'],
  },
  {
    id: 'science-light-speed',
    category: 'science',
    promptEs: '¿Cuál es aproximadamente la velocidad de la luz en el vacío?',
    promptEn: 'What is approximately the speed of light in a vacuum?',
    optionsEs: ['3,000 km/s', '300,000 km/s', '150,000 km/s', '1,000,000 km/s'],
    optionsEn: ['3,000 km/s', '300,000 km/s', '150,000 km/s', '1,000,000 km/s'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['300000 km/s', '300.000 km/s', '300000'],
    acceptedAnswersEn: ['300000 km/s', '300,000 km/s', '300000'],
  },
  {
    id: 'science-mammals',
    category: 'science',
    promptEs: 'Selecciona los animales que son mamíferos.',
    promptEn: 'Select the animals that are mammals.',
    optionsEs: ['Ballena', 'Delfín', 'Tiburón', 'Cocodrilo'],
    optionsEn: ['Whale', 'Dolphin', 'Shark', 'Crocodile'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['ballena delfin', 'ballena y delfin'],
    acceptedAnswersEn: ['whale dolphin', 'whale and dolphin'],
  },
  {
    id: 'science-atm-gas',
    category: 'science',
    promptEs: '¿Cuál es el gas más abundante en la atmósfera de la Tierra?',
    promptEn: 'What is the most abundant gas in Earth\'s atmosphere?',
    optionsEs: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Hidrógeno'],
    optionsEn: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['nitrogeno', 'nitrógeno'],
    acceptedAnswersEn: ['nitrogen'],
  },
  {
    id: 'science-states-of-matter',
    category: 'science',
    promptEs: 'Selecciona estados fundamentales de la materia.',
    promptEn: 'Select fundamental states of matter.',
    optionsEs: ['Sólido', 'Líquido', 'Gaseoso', 'Fuego'],
    optionsEn: ['Solid', 'Liquid', 'Gas', 'Fire'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['solido liquido gaseoso'],
    acceptedAnswersEn: ['solid liquid gas'],
  },
  {
    id: 'science-dna-structure',
    category: 'science',
    promptEs: '¿Qué forma geométrica describe la estructura molecular del ADN?',
    promptEn: 'What geometric shape describes the molecular structure of DNA?',
    optionsEs: ['Línea recta', 'Doble hélice', 'Esfera perfecta', 'Cubo'],
    optionsEn: ['Straight line', 'Double helix', 'Perfect sphere', 'Cube'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['doble helice', 'doble hélice'],
    acceptedAnswersEn: ['double helix'],
  },
  {
    id: 'science-natural-satellites',
    category: 'science',
    promptEs: 'Selecciona lunas o satélites naturales del sistema solar.',
    promptEn: 'Select moons or natural satellites in the solar system.',
    optionsEs: ['Titán', 'Europa', 'Ganimedes', 'Hubble'],
    optionsEn: ['Titan', 'Europa', 'Ganymede', 'Hubble'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['titan europa ganimedes'],
    acceptedAnswersEn: ['titan europa ganymede'],
  },
  {
    id: 'science-sun-star',
    category: 'science',
    promptEs: '¿Qué tipo de cuerpo celeste es el Sol?',
    promptEn: 'What type of celestial body is the Sun?',
    optionsEs: ['Planeta', 'Estrella', 'Galaxia', 'Asteroide'],
    optionsEn: ['Planet', 'Star', 'Galaxy', 'Asteroid'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['estrella'],
    acceptedAnswersEn: ['star'],
  },
  {
    id: 'science-brain-parts',
    category: 'science',
    promptEs: 'Selecciona partes que pertenecen al encéfalo humano.',
    promptEn: 'Select parts that belong to the human brain area.',
    optionsEs: ['Cerebelo', 'Corteza cerebral', 'Fémur', 'Alvéolos'],
    optionsEn: ['Cerebellum', 'Cerebral cortex', 'Femur', 'Alveoli'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['cerebelo corteza cerebral'],
    acceptedAnswersEn: ['cerebellum cerebral cortex'],
  },
  {
    id: 'science-powerhouse-cell',
    category: 'science',
    promptEs: '¿Qué orgánulo es la central energética de la célula?',
    promptEn: 'Which organelle is the powerhouse of the cell?',
    optionsEs: ['Mitocondria', 'Ribosoma', 'Lisosoma', 'Aparato de Golgi'],
    optionsEn: ['Mitochondria', 'Ribosome', 'Lysosome', 'Golgi apparatus'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['mitocondria'],
    acceptedAnswersEn: ['mitochondria'],
  },
  {
    id: 'science-noble-gases',
    category: 'science',
    promptEs: 'Selecciona elementos químicos que son gases nobles.',
    promptEn: 'Select chemical elements that are noble gases.',
    optionsEs: ['Helio', 'Neón', 'Hierro', 'Sodio'],
    optionsEn: ['Helium', 'Neon', 'Iron', 'Sodium'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['helio neon', 'helio y neon'],
    acceptedAnswersEn: ['helium neon', 'helium and neon'],
  },
  {
    id: 'science-earth-layers',
    category: 'science',
    promptEs: '¿Cómo se llama la capa más interna de la Tierra?',
    promptEn: 'What is the innermost layer of the Earth called?',
    optionsEs: ['Corteza', 'Manto', 'Núcleo', 'Atmósfera'],
    optionsEn: ['Crust', 'Mantle', 'Core', 'Atmosphere'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['nucleo', 'núcleo'],
    acceptedAnswersEn: ['core'],
  },
  {
    id: 'science-renewable-energy',
    category: 'science',
    promptEs: 'Selecciona fuentes de energía completamente renovables.',
    promptEn: 'Select fully renewable energy sources.',
    optionsEs: ['Solar', 'Eólica', 'Carbón', 'Petróleo'],
    optionsEn: ['Solar', 'Wind', 'Coal', 'Petroleum'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['solar eolica', 'solar y eolica'],
    acceptedAnswersEn: ['solar wind', 'solar and wind'],
  },
  {
    id: 'science-diamond-element',
    category: 'science',
    promptEs: '¿De qué elemento químico está compuesto el diamante puro?',
    promptEn: 'Which chemical element is pure diamond made of?',
    optionsEs: ['Oro', 'Carbono', 'Silicio', 'Plata'],
    optionsEn: ['Gold', 'Carbon', 'Silicon', 'Silver'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['carbono'],
    acceptedAnswersEn: ['carbon'],
  },
  {
    id: 'science-primary-colors-light',
    category: 'science',
    promptEs: 'Selecciona los colores primarios en la síntesis aditiva de la luz (RGB).',
    promptEn: 'Select the primary colors in the additive synthesis of light (RGB).',
    optionsEs: ['Rojo', 'Verde', 'Azul', 'Amarillo'],
    optionsEn: ['Red', 'Green', 'Blue', 'Yellow'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['rojo verde azul'],
    acceptedAnswersEn: ['red green blue'],
  },
  {
    id: 'science-acid-ph',
    category: 'science',
    promptEs: '¿Qué valor numérico define un pH perfectamente neutro?',
    promptEn: 'What numerical value defines a perfectly neutral pH?',
    optionsEs: ['0', '5', '7', '14'],
    optionsEn: ['0', '5', '7', '14'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['7', 'siete'],
    acceptedAnswersEn: ['7', 'seven'],
  },
  {
    id: 'science-dinosaur-extinction',
    category: 'science',
    promptEs: '¿Hace cuántos millones de años ocurrió la extinción masiva de los dinosaurios?',
    promptEn: 'How many millions of years ago did the mass extinction of dinosaurs occur?',
    optionsEs: ['10 millones', '66 millones', '250 millones', '500 millones'],
    optionsEn: ['10 million', '66 million', '250 million', '500 million'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['66 millones', '66'],
    acceptedAnswersEn: ['66 million', '66'],
  },
  {
    id: 'science-human-bones',
    category: 'science',
    promptEs: '¿Cuántos huesos tiene el esqueleto de un ser humano adulto estándar?',
    promptEn: 'How many bones does a standard adult human skeleton have?',
    optionsEs: ['106', '206', '306', '406'],
    optionsEn: ['106', '206', '306', '406'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['206', 'doscientos seis'],
    acceptedAnswersEn: ['206', 'two hundred six'],
  },
  {
    id: 'science-boiling-point-water',
    category: 'science',
    promptEs: '¿A qué temperatura hierve el agua pura a nivel del mar?',
    promptEn: 'At what temperature does pure water boil at sea level?',
    optionsEs: ['50 °C', '100 °C', '212 °C', '0 °C'],
    optionsEn: ['50 °C', '100 °C', '212 °C', '0 °C'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['100', '100 grados', '100 c'],
    acceptedAnswersEn: ['100', '100 degrees', '100 c'],
  },
    {
    id: 'science-sound-medium',
    category: 'science',
    promptEs: '¿A través de cuál de estos medios NO puede viajar el sonido?',
    promptEn: 'Through which of these mediums can sound NOT travel?',
    optionsEs: ['Agua', 'Aire', 'Vacío', 'Acero'],
    optionsEn: ['Water', 'Air', 'Vacuum', 'Steel'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['vacio', 'vacío'],
    acceptedAnswersEn: ['vacuum'],
  },
  {
    id: 'science-galaxies',
    category: 'science',
    promptEs: '¿Cómo se llama la galaxia en la que se encuentra nuestro sistema solar?',
    promptEn: 'What is the name of the galaxy that contains our solar system?',
    optionsEs: ['Andrómeda', 'Vía Láctea', 'Nebulosa de Orión', 'Galaxia del Triángulo'],
    optionsEn: ['Andromeda', 'Milky Way', 'Orion Nebula', 'Triangulum Galaxy'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['via lactea', 'vía láctea'],
    acceptedAnswersEn: ['milky way'],
  },
  {
    id: 'science-respiratory-organs',
    category: 'science',
    promptEs: 'Selecciona los órganos que forman parte del sistema respiratorio humano.',
    promptEn: 'Select the organs that are part of the human respiratory system.',
    optionsEs: ['Pulmones', 'Traquea', 'Estómago', 'Hígado'],
    optionsEn: ['Lungs', 'Trachea', 'Stomach', 'Liver'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['pulmones traquea', 'pulmones y traquea'],
    acceptedAnswersEn: ['lungs trachea', 'lungs and trachea'],
  },
  {
    id: 'science-einstein-equation',
    category: 'science',
    promptEs: '¿Qué letra representa la velocidad de la luz en la famosa ecuación E=mc²?',
    promptEn: 'What letter represents the speed of light in the famous E=mc² equation?',
    optionsEs: ['E', 'm', 'c', 'x'],
    optionsEn: ['E', 'm', 'c', 'x'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['c'],
    acceptedAnswersEn: ['c'],
  },
  {
    id: 'science-periodic-table-h',
    category: 'science',
    promptEs: '¿Qué elemento químico está representado por la letra "H" en la tabla periódica?',
    promptEn: 'Which chemical element is represented by the letter "H" on the periodic table?',
    optionsEs: ['Helio', 'Hierro', 'Hidrógeno', 'Mercurio'],
    optionsEn: ['Helium', 'Iron', 'Hydrogen', 'Mercury'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['hidrogeno', 'hidrógeno'],
    acceptedAnswersEn: ['hydrogen'],
  },
  {
    id: 'science-invertebrates',
    category: 'science',
    promptEs: 'Selecciona los animales que NO tienen columna vertebral (invertebrados).',
    promptEn: 'Select the animals that do NOT have a backbone (invertebrates).',
    optionsEs: ['Pulpo', 'Mariposa', 'Perro', 'Águila'],
    optionsEn: ['Octopus', 'Butterfly', 'Dog', 'Eagle'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['pulpo mariposa', 'pulpo y mariposa'],
    acceptedAnswersEn: ['octopus butterfly', 'octopus and butterfly'],
  },
  {
    id: 'science-gravity-moon',
    category: 'science',
    promptEs: '¿Cómo es la gravedad de la Luna en comparación con la de la Tierra?',
    promptEn: 'How is the Moon\'s gravity compared to Earth\'s gravity?',
    optionsEs: ['Mayor', 'Menor', 'Igual', 'No tiene'],
    optionsEn: ['Higher', 'Lower', 'Equal', 'It has none'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['menor'],
    acceptedAnswersEn: ['lower'],
  },
  {
    id: 'science-photosynthesis-output',
    category: 'science',
    promptEs: '¿Qué gas liberan las plantas a la atmósfera como resultado de la fotosíntesis?',
    promptEn: 'Which gas do plants release into the atmosphere as a result of photosynthesis?',
    optionsEs: ['Dióxido de carbono', 'Oxígeno', 'Nitrógeno', 'Metano'],
    optionsEn: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Methane'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['oxigeno', 'oxígeno'],
    acceptedAnswersEn: ['oxygen'],
  },
  {
    id: 'science-hardest-mineral',
    category: 'science',
    promptEs: '¿Cuál es el mineral natural más duro que existe en la Tierra?',
    promptEn: 'What is the hardest natural mineral known on Earth?',
    optionsEs: ['Cuarzo', 'Diamante', 'Talco', 'Rubí'],
    optionsEn: ['Quartz', 'Diamond', 'Talc', 'Ruby'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['diamante'],
    acceptedAnswersEn: ['diamond'],
  },
  {
    id: 'science-seasons-cause',
    category: 'science',
    promptEs: '¿Qué factor causa principalmente las estaciones del año en la Tierra?',
    promptEn: 'What factor primarily causes the seasons on Earth?',
    optionsEs: ['La distancia al Sol', 'La inclinación del eje terrestre', 'La actividad solar', 'Las corrientes marinas'],
    optionsEn: ['The distance to the Sun', 'The tilt of Earth\'s axis', 'Solar activity', 'Ocean currents'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['inclinacion del eje terrestre', 'inclinacion del eje', 'la inclinacion'],
    acceptedAnswersEn: ['tilt of earths axis', 'earths tilt', 'the tilt'],
  },
  {
    id: 'science-planet-rings',
    category: 'science',
    promptEs: '¿Qué planeta del sistema solar es más famoso por sus grandes y visibles anillos?',
    promptEn: 'Which planet in the solar system is most famous for its large and visible rings?',
    optionsEs: ['Júpiter', 'Saturno', 'Neptuno', 'Urano'],
    optionsEn: ['Jupiter', 'Saturn', 'Neptune', 'Uranus'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['saturno'],
    acceptedAnswersEn: ['saturn'],
  },
  {
    id: 'science-fungi-kingdom',
    category: 'science',
    promptEs: 'Selecciona los elementos que pertenecen al reino de los hongos (Fungi).',
    promptEn: 'Select the elements that belong to the fungi kingdom.',
    optionsEs: ['Champiñón', 'Moho', 'Helecho', 'Bacteria'],
    optionsEn: ['Mushroom', 'Mold', 'Fern', 'Bacteria'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['champiñon moho', 'champiñon y moho'],
    acceptedAnswersEn: ['mushroom mold', 'mushroom and mold'],
  },
  {
    id: 'science-universe-age',
    category: 'science',
    promptEs: '¿Cuál es la edad aproximada del universo desde el Big Bang?',
    promptEn: 'What is the approximate age of the universe since the Big Bang?',
    optionsEs: ['4.5 mil millones de años', '13.8 mil millones de años', '93 mil millones de años', '100 millones de años'],
    optionsEn: ['4.5 billion years', '13.8 billion years', '93 billion years', '100 million years'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['13.8 mil millones de años', '13.8 mil millones', '13800 millones'],
    acceptedAnswersEn: ['13.8 billion years', '13.8 billion'],
  },
  {
    id: 'science-main-layers-cell',
    category: 'science',
    promptEs: 'Selecciona partes fundamentales presentes en la mayoría de las células.',
    promptEn: 'Select fundamental parts present in most cells.',
    optionsEs: ['Membrana plasmática', 'Citoplasma', 'Pared de celulosa', 'Cloroplasto'],
    optionsEn: ['Plasma membrane', 'Cytoplasm', 'Cellulose wall', 'Chloroplast'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['membrana plasmatica citoplasma', 'membrana y citoplasma'],
    acceptedAnswersEn: ['plasma membrane cytoplasm', 'membrane and cytoplasm'],
  },
  {
    id: 'science-ebullition-alcohol',
    category: 'science',
    promptEs: '¿Aproximadamente a qué temperatura hierve el alcohol etílico puro a nivel del mar?',
    promptEn: 'Approximately at what temperature does pure ethyl alcohol boil at sea level?',
    optionsEs: ['50 °C', '78 °C', '100 °C', '120 °C'],
    optionsEn: ['50 °C', '78 °C', '100 °C', '120 °C'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['78', '78 grados', '78 c'],
    acceptedAnswersEn: ['78', '78 degrees', '78 c'],
  },
  {
    id: 'science-metamorphic-rocks',
    category: 'science',
    promptEs: 'Selecciona ejemplos de rocas metamórficas.',
    promptEn: 'Select examples of metamorphic rocks.',
    optionsEs: ['Mármol', 'Pizarra', 'Basalto', 'Arenisca'],
    optionsEn: ['Marble', 'Slate', 'Basalt', 'Sandstone'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['marmol pizarra', 'marmol y pizarra'],
    acceptedAnswersEn: ['marble slate', 'marble and slate'],
  },
  {
    id: 'science-cell-discovery',
    category: 'science',
    promptEs: '¿Qué científico observó por primera vez las células usando un microscopio en 1665?',
    promptEn: 'Which scientist first observed cells using a microscope in 1665?',
    optionsEs: ['Charles Darwin', 'Louis Pasteur', 'Robert Hooke', 'Gregor Mendel'],
    optionsEn: ['Charles Darwin', 'Louis Pasteur', 'Robert Hooke', 'Gregor Mendel'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['robert hooke', 'hooke'],
    acceptedAnswersEn: ['robert hooke', 'hooke'],
  },
  {
    id: 'science-ocean-deepest',
    category: 'science',
    promptEs: '¿Cómo se llama la fosa oceánica más profunda conocida en la Tierra?',
    promptEn: 'What is the name of the deepest known ocean trench on Earth?',
    optionsEs: ['Fosa de Puerto Rico', 'Fosa de las Marianas', 'Fosa de Java', 'Fosa de las Aleutianas'],
    optionsEn: ['Puerto Rico Trench', 'Mariana Trench', 'Java Trench', 'Aleutian Trench'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['fosa de las marianas', 'marianas'],
    acceptedAnswersEn: ['mariana trench', 'marianas'],
  },
  {
    id: 'science-insulators',
    category: 'science',
    promptEs: 'Selecciona los materiales que funcionan como buenos aislantes eléctricos.',
    promptEn: 'Select the materials that function as good electrical insulators.',
    optionsEs: ['Plástico', 'Madera seca', 'Cobre', 'Aluminio'],
    optionsEn: ['Plastic', 'Dry wood', 'Copper', 'Aluminum'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['plastico madera seca', 'plastico y madera'],
    acceptedAnswersEn: ['plastic dry wood', 'plastic and wood'],
  },
  {
    id: 'science-sound-speed',
    category: 'science',
    promptEs: '¿En cuál de estos medios el sonido viaja a mayor velocidad?',
    promptEn: 'In which of these mediums does sound travel at the highest speed?',
    optionsEs: ['Aire', 'Agua', 'Sólidos (como el acero)', 'Vacío'],
    optionsEn: ['Air', 'Water', 'Solids (like steel)', 'Vacuum'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['solidos', 'acero', 'los solidos'],
    acceptedAnswersEn: ['solids', 'steel', 'the solids'],
  },
    {
    id: 'science-red-planet',
    category: 'science',
    promptEs: '¿Qué planeta del sistema solar es conocido popularmente como el Planeta Rojo?',
    promptEn: 'Which planet in the solar system is popularly known as the Red Planet?',
    optionsEs: ['Venus', 'Marte', 'Júpiter', 'Mercurio'],
    optionsEn: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['marte'],
    acceptedAnswersEn: ['mars'],
  },
  {
    id: 'science-exoskeleton-animals',
    category: 'science',
    promptEs: 'Selecciona los animales que poseen un exoesqueleto.',
    promptEn: 'Select the animals that have an exoskeleton.',
    optionsEs: ['Cangrejo', 'Escarabajo', 'Perro', 'Lombriz'],
    optionsEn: ['Crab', 'Beetle', 'Dog', 'Earthworm'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['cangrejo escarabajo', 'cangrejo y escarabajo'],
    acceptedAnswersEn: ['crab beetle', 'crab and beetle'],
  },
  {
    id: 'science-gravity-acceleration',
    category: 'science',
    promptEs: '¿Cuál es el valor estándar aproximado de la aceleración de la gravedad en la Tierra?',
    promptEn: 'What is the approximate standard value of gravitational acceleration on Earth?',
    optionsEs: ['5.5 m/s²', '9.8 m/s²', '12.4 m/s²', '3.1 m/s²'],
    optionsEn: ['5.5 m/s²', '9.8 m/s²', '12.4 m/s²', '3.1 m/s²'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['9.8', '9.8 m/s2', '9,8'],
    acceptedAnswersEn: ['9.8', '9.8 m/s2'],
  },
  {
    id: 'science-comet-halley',
    category: 'science',
    promptEs: '¿Cada cuántos años aproximadamente es visible el cometa Halley desde la Tierra?',
    promptEn: 'Approximately every how many years is Halley\'s Comet visible from Earth?',
    optionsEs: ['12 años', '25 años', '76 años', '150 años'],
    optionsEn: ['12 years', '25 years', '76 years', '150 years'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['76', '76 años'],
    acceptedAnswersEn: ['76', '76 years'],
  },
  {
    id: 'science-conductors',
    category: 'science',
    promptEs: 'Selecciona los materiales que son excelentes conductores de la electricidad.',
    promptEn: 'Select the materials that are excellent conductors of electricity.',
    optionsEs: ['Cobre', 'Oro', 'Plástico', 'Vidrio'],
    optionsEn: ['Copper', 'Gold', 'Plastic', 'Glass'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['cobre oro', 'cobre y oro'],
    acceptedAnswersEn: ['copper gold', 'copper and gold'],
  },
  {
    id: 'science-pasteurization',
    category: 'science',
    promptEs: '¿Qué científico desarrolló el proceso térmico para eliminar patógenos en líquidos llamado pasteurización?',
    promptEn: 'Which scientist developed the thermal process to eliminate pathogens in liquids called pasteurization?',
    optionsEs: ['Charles Darwin', 'Alexander Fleming', 'Louis Pasteur', 'Gregor Mendel'],
    optionsEn: ['Charles Darwin', 'Alexander Fleming', 'Louis Pasteur', 'Gregor Mendel'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['louis pasteur', 'pasteur'],
    acceptedAnswersEn: ['louis pasteur', 'pasteur'],
  },
  {
    id: 'science-gas-plants',
    category: 'science',
    promptEs: '¿Qué gas absorben principalmente las plantas durante el día para realizar la fotosíntesis?',
    promptEn: 'Which gas do plants primarily absorb during the day to perform photosynthesis?',
    optionsEs: ['Oxígeno', 'Dióxido de carbono', 'Metano', 'Helio'],
    optionsEn: ['Oxygen', 'Carbon dioxide', 'Methane', 'Helium'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['dioxido de carbono', 'co2'],
    acceptedAnswersEn: ['carbon dioxide', 'co2'],
  },
  {
    id: 'science-carnivorous-plants',
    category: 'science',
    promptEs: 'Selecciona las plantas que son consideradas carnívoras.',
    promptEn: 'Select the plants that are considered carnivorous.',
    optionsEs: ['Venus atrapamoscas', 'Planta jarra', 'Helecho común', 'Girasol'],
    optionsEn: ['Venus flytrap', 'Pitcher plant', 'Common fern', 'Sunflower'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['venus atrapamoscas planta jarra'],
    acceptedAnswersEn: ['venus flytrap pitcher plant'],
  },
  {
    id: 'science-universe-element',
    category: 'science',
    promptEs: '¿Cuál es el elemento químico más abundante y ligero en todo el universo?',
    promptEn: 'What is the most abundant and lightest chemical element in the entire universe?',
    optionsEs: ['Helio', 'Oxígeno', 'Hidrógeno', 'Carbono'],
    optionsEn: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['hidrogeno', 'hidrógeno'],
    acceptedAnswersEn: ['hydrogen'],
  },
  {
    id: 'science-moon-phases',
    category: 'science',
    promptEs: 'Selecciona fases válidas del ciclo lunar.',
    promptEn: 'Select valid phases of the lunar cycle.',
    optionsEs: ['Luna nueva', 'Cuarto creciente', 'Luna roja', 'Eclipse total'],
    optionsEn: ['New moon', 'First quarter', 'Red moon', 'Total eclipse'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['luna nueva cuarto creciente'],
    acceptedAnswersEn: ['new moon first quarter'],
  },
  {
    id: 'science-human-stomach-acid',
    category: 'science',
    promptEs: '¿Qué ácido se encuentra principalmente en el estómago humano para ayudar a la digestión?',
    promptEn: 'Which acid is primarily found in the human stomach to aid digestion?',
    optionsEs: ['Ácido sulfúrico', 'Ácido clorhídrico', 'Ácido acético', 'Ácido nítrico'],
    optionsEn: ['Sulfuric acid', 'Hydrochloric acid', 'Acetic acid', 'Nitric acid'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['acido clorhidrico', 'ácido clorhídrico'],
    acceptedAnswersEn: ['hydrochloric acid', 'hcl'],
  },
  {
    id: 'science-penicillin-discoverer',
    category: 'science',
    promptEs: '¿Qué científico británico descubrió la penicilina en 1928?',
    promptEn: 'Which British scientist discovered penicillin in 1928?',
    optionsEs: ['Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Edward Jenner'],
    optionsEn: ['Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Edward Jenner'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['alexander fleming', 'fleming'],
    acceptedAnswersEn: ['alexander fleming', 'fleming'],
  },
  {
    id: 'science-natural-hazards',
    category: 'science',
    promptEs: 'Selecciona los fenómenos que se originan por la actividad interna de la Tierra.',
    promptEn: 'Select the phenomena that originate from Earth\'s internal activity.',
    optionsEs: ['Terremotos', 'Erupciones volcánicas', 'Huracanes', 'Tornados'],
    optionsEn: ['Earthquakes', 'Volcanic eruptions', 'Hurricanes', 'Tornadoes'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['terremotos erupciones volcanicas', 'terremotos y volcanes'],
    acceptedAnswersEn: ['earthquakes volcanic eruptions', 'earthquakes and volcanoes'],
  },
  {
    id: 'science-absolute-zero',
    category: 'science',
    promptEs: '¿A qué temperatura equivale aproximadamente el cero absoluto en la escala Celsius?',
    promptEn: 'What temperature is approximately equivalent to absolute zero on the Celsius scale?',
    optionsEs: ['0 °C', '-100 °C', '-273.15 °C', '-459.67 °C'],
    optionsEn: ['0 °C', '-100 °C', '-273.15 °C', '-459.67 °C'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['-273.15', '-273', 'menos 273'],
    acceptedAnswersEn: ['-273.15', '-273'],
  },
  {
    id: 'science-blood-types',
    category: 'science',
    promptEs: 'Selecciona los tipos de sangre válidos dentro del sistema AB0.',
    promptEn: 'Select valid blood types within the AB0 system.',
    optionsEs: ['Tipo A', 'Tipo 0', 'Tipo X', 'Tipo Z'],
    optionsEn: ['Type A', 'Type 0', 'Type X', 'Type Z'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['tipo a tipo 0', 'a y 0'],
    acceptedAnswersEn: ['type a type 0', 'a and 0'],
  },
  {
    id: 'science-seismograph',
    category: 'science',
    promptEs: '¿Qué instrumento científico se utiliza para medir y registrar la intensidad de los terremotos?',
    promptEn: 'What scientific instrument is used to measure and record the intensity of earthquakes?',
    optionsEs: ['Barómetro', 'Sismógrafo', 'Anemómetro', 'Termómetro'],
    optionsEn: ['Barometer', 'Seismograph', 'Anemometer', 'Thermometer'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['sismografo', 'sismógrafo'],
    acceptedAnswersEn: ['seismograph'],
  },
  {
    id: 'science-organs-endocrine',
    category: 'science',
    promptEs: 'Selecciona las glándulas que forman parte del sistema endocrino humano.',
    promptEn: 'Select the glands that are part of the human endocrine system.',
    optionsEs: ['Tiroides', 'Páncreas', 'Bazo', 'Vejiga'],
    optionsEn: ['Thyroid', 'Pancreas', 'Spleen', 'Bladder'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['tiroides pancreas', 'tiroides y pancreas'],
    acceptedAnswersEn: ['thyroid pancreas', 'thyroid and pancreas'],
  },
  {
    id: 'science-dry-ice',
    category: 'science',
    promptEs: '¿Qué compuesto químico en estado sólido constituye el llamado "hielo seco"?',
    promptEn: 'Which chemical compound in a solid state constitutes the so-called "dry ice"?',
    optionsEs: ['Agua', 'Dióxido de carbono', 'Metano', 'Nitrógeno'],
    optionsEn: ['Water', 'Carbon dioxide', 'Methane', 'Nitrogen'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['dioxido de carbono', 'co2'],
    acceptedAnswersEn: ['carbon dioxide', 'co2'],
  },
  {
    id: 'science-amphibians',
    category: 'science',
    promptEs: 'Selecciona los animales que pertenecen a la clase de los anfibios.',
    promptEn: 'Select the animals that belong to the amphibian class.',
    optionsEs: ['Rana', 'Salamandra', 'Lagartija', 'Tortuga'],
    optionsEn: ['Frog', 'Salamander', 'Lizard', 'Turtle'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['rana salamandra', 'rana y salamandra'],
    acceptedAnswersEn: ['frog salamander', 'frog and salamander'],},{id: 'science-barometer',category: 'science',promptEs: '¿Qué propiedad meteorológica mide un barómetro?',promptEn: 'What meteorological property does a barometer measure?',optionsEs: ['Humedad del aire', 'Presión atmosférica', 'Velocidad del viento', 'Temperatura'],optionsEn: ['Air humidity', 'Atmospheric pressure', 'Wind speed', 'Temperature'],correctOptionIndexes: [1],acceptedAnswersEs: ['presion atmosferica', 'presion'],acceptedAnswersEn: ['atmospheric pressure', 'pressure'],}
];
