import { TriviaQuestion } from '../types/trivia.types';

export const SPORTS_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'sports-football-world-cup',
    category: 'sports',
    promptEs: 'Cada cuantos anos se juega la Copa Mundial de futbol masculino?',
    promptEn: 'How often is the men\'s FIFA World Cup played?',
    optionsEs: ['Cada 2 anos', 'Cada 3 anos', 'Cada 4 anos', 'Cada 6 anos'],
    optionsEn: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 6 years'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['cada 4 anos', '4 anos', 'cuatro anos'],
    acceptedAnswersEn: ['every 4 years', '4 years', 'four years'],
  },
  {
    id: 'sports-basketball-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo estan en cancha en baloncesto?',
    promptEn: 'How many players per team are on the court in basketball?',
    optionsEs: ['4', '5', '6', '7'],
    optionsEn: ['4', '5', '6', '7'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['5', 'cinco'],
    acceptedAnswersEn: ['5', 'five'],
  },
  {
    id: 'sports-tennis-grand-slams',
    category: 'sports',
    promptEs: 'Selecciona torneos de Grand Slam de tenis.',
    promptEn: 'Select tennis Grand Slam tournaments.',
    optionsEs: ['Wimbledon', 'Roland Garros', 'Copa Davis', 'Abierto de Australia'],
    optionsEn: ['Wimbledon', 'Roland Garros', 'Davis Cup', 'Australian Open'],
    correctOptionIndexes: [0, 1, 3],
    acceptedAnswersEs: ['wimbledon roland garros abierto de australia', 'wimbledon roland garros australia'],
    acceptedAnswersEn: ['wimbledon roland garros australian open', 'wimbledon roland garros australia'],
  },
  {
    id: 'sports-olympic-rings',
    category: 'sports',
    promptEs: 'Cuantos anillos tiene el simbolo olimpico?',
    promptEn: 'How many rings are in the Olympic symbol?',
    optionsEs: ['4', '5', '6', '7'],
    optionsEn: ['4', '5', '6', '7'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['5', 'cinco'],
    acceptedAnswersEn: ['5', 'five'],
  },
  {
    id: 'sports-volleyball-team',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo estan en cancha en voleibol?',
    promptEn: 'How many players per team are on the court in volleyball?',
    optionsEs: ['5', '6', '7', '8'],
    optionsEn: ['5', '6', '7', '8'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['6', 'seis'],
    acceptedAnswersEn: ['6', 'six'],
  },
  {
    id: 'sports-baseball-strikes',
    category: 'sports',
    promptEs: 'Cuantos strikes necesita un bateador para quedar eliminado en beisbol?',
    promptEn: 'How many strikes does a batter need to be out in baseball?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres'],
    acceptedAnswersEn: ['3', 'three'],
  },
  {
    id: 'sports-athletics-events',
    category: 'sports',
    promptEs: 'Selecciona pruebas de atletismo.',
    promptEn: 'Select track and field events.',
    optionsEs: ['Salto largo', 'Lanzamiento de jabalina', 'Tiro libre', '100 metros'],
    optionsEn: ['Long jump', 'Javelin throw', 'Free throw', '100 meters'],
    correctOptionIndexes: [0, 1, 3],
    acceptedAnswersEs: ['salto largo lanzamiento de jabalina 100 metros', 'salto largo jabalina 100 metros'],
    acceptedAnswersEn: ['long jump javelin throw 100 meters', 'long jump javelin 100 meters'],
  },
  {
    id: 'sports-swimming-style',
    category: 'sports',
    promptEs: 'Cual de estos es un estilo de natacion competitivo?',
    promptEn: 'Which of these is a competitive swimming stroke?',
    optionsEs: ['Mariposa', 'Carrera', 'Remate', 'Drible'],
    optionsEn: ['Butterfly', 'Race', 'Spike', 'Dribble'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['mariposa'],
    acceptedAnswersEn: ['butterfly'],
  },
  {
    id: 'sports-football-penalty-distance',
    category: 'sports',
    promptEs: 'A cuantos metros esta el punto penal en futbol?',
    promptEn: 'How many meters from the goal is the penalty spot in football/soccer?',
    optionsEs: ['9 metros', '10 metros', '11 metros', '12 metros'],
    optionsEn: ['9 meters', '10 meters', '11 meters', '12 meters'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['11 metros', 'once metros', '11'],
    acceptedAnswersEn: ['11 meters', 'eleven meters', '11'],
  },
  {
    id: 'sports-chess-board',
    category: 'sports',
    promptEs: 'Cuantas casillas tiene un tablero de ajedrez?',
    promptEn: 'How many squares are on a chessboard?',
    optionsEs: ['49', '56', '64', '72'],
    optionsEn: ['49', '56', '64', '72'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['64', 'sesenta y cuatro'],
    acceptedAnswersEn: ['64', 'sixty four'],
  },

  {
    id: 'sports-rugby-sevens-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo estan en cancha en rugby sevens?',
    promptEn: 'How many players per team are on the field in rugby sevens?',
    optionsEs: ['5', '7', '11', '15'],
    optionsEn: ['5', '7', '11', '15'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['7', 'siete'],
    acceptedAnswersEn: ['7', 'seven'],
  },
  {
    id: 'sports-rugby-try-points',
    category: 'sports',
    promptEs: 'Cuantos puntos vale un try en rugby union?',
    promptEn: 'How many points is a try worth in rugby union?',
    optionsEs: ['3 puntos', '5 puntos', '6 puntos', '7 puntos'],
    optionsEn: ['3 points', '5 points', '6 points', '7 points'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['5 puntos', 'cinco puntos', '5'],
    acceptedAnswersEn: ['5 points', 'five points', '5'],
  },
  {
    id: 'sports-rugby-sevens-half-duration',
    category: 'sports',
    promptEs: 'Cuanto dura cada tiempo en rugby sevens?',
    promptEn: 'How long is each half in rugby sevens?',
    optionsEs: ['5 minutos', '7 minutos', '10 minutos', '15 minutos'],
    optionsEn: ['5 minutes', '7 minutes', '10 minutes', '15 minutes'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['7 minutos', 'siete minutos', '7'],
    acceptedAnswersEn: ['7 minutes', 'seven minutes', '7'],
  },
  {
    id: 'sports-boxing-olympic-rounds',
    category: 'sports',
    promptEs: 'Cuantos rounds tiene un combate de boxeo olimpico?',
    promptEn: 'How many rounds are in an Olympic boxing bout?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres rounds', '3 rounds'],
    acceptedAnswersEn: ['3', 'three', 'three rounds', '3 rounds'],
  },
  {
    id: 'sports-boxing-olympic-round-duration',
    category: 'sports',
    promptEs: 'Cuanto dura cada round en boxeo olimpico?',
    promptEn: 'How long is each round in Olympic boxing?',
    optionsEs: ['2 minutos', '3 minutos', '4 minutos', '5 minutos'],
    optionsEn: ['2 minutes', '3 minutes', '4 minutes', '5 minutes'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3 minutos', 'tres minutos', '3'],
    acceptedAnswersEn: ['3 minutes', 'three minutes', '3'],
  },
  {
    id: 'sports-handball-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo estan en cancha en balonmano?',
    promptEn: 'How many players per team are on the court in handball?',
    optionsEs: ['5', '6', '7', '8'],
    optionsEn: ['5', '6', '7', '8'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['7', 'siete'],
    acceptedAnswersEn: ['7', 'seven'],
  },
  {
    id: 'sports-taekwondo-rounds',
    category: 'sports',
    promptEs: 'Cuantos rounds tiene normalmente un combate de taekwondo olimpico?',
    promptEn: 'How many rounds are normally in an Olympic taekwondo match?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres rounds', '3 rounds'],
    acceptedAnswersEn: ['3', 'three', 'three rounds', '3 rounds'],
  },
  {
    id: 'sports-judo-ippon',
    category: 'sports',
    promptEs: 'Que puntuacion puede terminar inmediatamente un combate de judo?',
    promptEn: 'Which score can immediately end a judo match?',
    optionsEs: ['Ippon', 'Try', 'Home run', 'Corner'],
    optionsEn: ['Ippon', 'Try', 'Home run', 'Corner'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['ippon'],
    acceptedAnswersEn: ['ippon'],
  },
  {
    id: 'sports-greco-roman-restriction',
    category: 'sports',
    promptEs: 'En lucha grecorromana, que esta prohibido?',
    promptEn: 'In Greco-Roman wrestling, what is prohibited?',
    optionsEs: ['Agarres debajo de la cintura', 'Derribos con brazos', 'Empujar con el hombro', 'Usar uniforme rojo'],
    optionsEn: ['Holds below the waist', 'Arm takedowns', 'Pushing with the shoulder', 'Wearing a red uniform'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['agarres debajo de la cintura', 'debajo de la cintura'],
    acceptedAnswersEn: ['holds below the waist', 'below the waist'],
  },
  {
    id: 'sports-weightlifting-lifts',
    category: 'sports',
    promptEs: 'Selecciona levantamientos de halterofilia olimpica.',
    promptEn: 'Select Olympic weightlifting lifts.',
    optionsEs: ['Arranque', 'Envion', 'Tiro libre', 'Jab'],
    optionsEn: ['Snatch', 'Clean and jerk', 'Free throw', 'Jab'],
    correctOptionIndexes: [0, 1],
    acceptedAnswersEs: ['arranque envion', 'arranque y envion', 'arranque dos tiempos'],
    acceptedAnswersEn: ['snatch clean and jerk', 'snatch and clean and jerk'],
  },
  {
    id: 'sports-marathon-distance',
    category: 'sports',
    promptEs: 'Cual es la distancia oficial de una maraton?',
    promptEn: 'What is the official distance of a marathon?',
    optionsEs: ['21.097 km', '42.195 km', '50 km', '100 km'],
    optionsEn: ['21.097 km', '42.195 km', '50 km', '100 km'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['42.195 km', '42.195 kilometros', 'cuarenta y dos punto ciento noventa y cinco kilometros'],
    acceptedAnswersEn: ['42.195 km', '42.195 kilometers', 'forty two point one nine five kilometers'],
  },
  {
    id: 'sports-triathlon-disciplines',
    category: 'sports',
    promptEs: 'Selecciona disciplinas que componen un triatlon.',
    promptEn: 'Select disciplines that make up a triathlon.',
    optionsEs: ['Natacion', 'Ciclismo', 'Carrera a pie', 'Remo'],
    optionsEn: ['Swimming', 'Cycling', 'Running', 'Rowing'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['natacion ciclismo carrera a pie', 'natacion ciclismo carrera', 'nadar bicicleta correr'],
    acceptedAnswersEn: ['swimming cycling running', 'swim bike run', 'swimming biking running'],
  },
  {
    id: 'sports-triathlon-standard-run',
    category: 'sports',
    promptEs: 'Cuantos kilometros se corren en un triatlon de distancia standard?',
    promptEn: 'How many kilometers are run in a standard-distance triathlon?',
    optionsEs: ['5 km', '10 km', '21 km', '42 km'],
    optionsEn: ['5 km', '10 km', '21 km', '42 km'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['10 km', '10 kilometros', 'diez kilometros'],
    acceptedAnswersEn: ['10 km', '10 kilometers', 'ten kilometers'],
  },
  {
    id: 'sports-decathlon-events-count',
    category: 'sports',
    promptEs: 'Cuantas pruebas tiene el decatlon?',
    promptEn: 'How many events are in the decathlon?',
    optionsEs: ['7', '8', '10', '12'],
    optionsEn: ['7', '8', '10', '12'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['10', 'diez'],
    acceptedAnswersEn: ['10', 'ten'],
  },
  {
    id: 'sports-waterpolo-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo hay en el agua en waterpolo?',
    promptEn: 'How many players per team are in the water in water polo?',
    optionsEs: ['5', '6', '7', '8'],
    optionsEn: ['5', '6', '7', '8'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['7', 'siete'],
    acceptedAnswersEn: ['7', 'seven'],
  },
  {
    id: 'sports-climbing-disciplines',
    category: 'sports',
    promptEs: 'Selecciona disciplinas de escalada deportiva.',
    promptEn: 'Select sport climbing disciplines.',
    optionsEs: ['Boulder', 'Lead', 'Speed', 'Slalom'],
    optionsEn: ['Boulder', 'Lead', 'Speed', 'Slalom'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['boulder lead speed', 'boulder dificultad velocidad', 'bloque dificultad velocidad'],
    acceptedAnswersEn: ['boulder lead speed', 'bouldering lead speed'],
  },
  {
    id: 'sports-canoe-sprint-distances',
    category: 'sports',
    promptEs: 'Selecciona distancias de canotaje sprint.',
    promptEn: 'Select canoe sprint distances.',
    optionsEs: ['200 metros', '500 metros', '1000 metros', '3000 metros'],
    optionsEn: ['200 meters', '500 meters', '1000 meters', '3000 meters'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['200 metros 500 metros 1000 metros', '200 500 1000'],
    acceptedAnswersEn: ['200 meters 500 meters 1000 meters', '200 500 1000'],
  },

  {
    id: 'sports-popular-football-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo hay en cancha en futbol?',
    promptEn: 'How many players per team are on the field in football/soccer?',
    optionsEs: ['9', '10', '11', '12'],
    optionsEn: ['9', '10', '11', '12'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['11', 'once'],
    acceptedAnswersEn: ['11', 'eleven'],
  },
  {
    id: 'sports-popular-football-half-duration',
    category: 'sports',
    promptEs: 'Cuanto dura cada tiempo en un partido de futbol?',
    promptEn: 'How long is each half in a football/soccer match?',
    optionsEs: ['30 minutos', '40 minutos', '45 minutos', '60 minutos'],
    optionsEn: ['30 minutes', '40 minutes', '45 minutes', '60 minutes'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['45 minutos', 'cuarenta y cinco minutos', '45'],
    acceptedAnswersEn: ['45 minutes', 'forty five minutes', '45'],
  },
  {
    id: 'sports-popular-football-red-card',
    category: 'sports',
    promptEs: 'Que pasa cuando un jugador recibe tarjeta roja en futbol?',
    promptEn: 'What happens when a player receives a red card in football/soccer?',
    optionsEs: ['Es expulsado', 'Lanza un penal', 'Cambia de equipo', 'Gana un punto'],
    optionsEn: ['He is sent off', 'He takes a penalty', 'He changes teams', 'He wins a point'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['es expulsado', 'expulsado', 'sale del partido'],
    acceptedAnswersEn: ['he is sent off', 'sent off', 'ejected'],
  },
  {
    id: 'sports-popular-football-goalkeeper-hands',
    category: 'sports',
    promptEs: 'En que zona puede usar las manos el arquero en futbol?',
    promptEn: 'In which area can the goalkeeper use their hands in football/soccer?',
    optionsEs: ['Area penal', 'Medio campo', 'Circulo central', 'Banda lateral'],
    optionsEn: ['Penalty area', 'Midfield', 'Center circle', 'Sideline'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['area penal', 'area', 'dentro del area'],
    acceptedAnswersEn: ['penalty area', 'box', 'inside the box'],
  },
  {
    id: 'sports-popular-basketball-hoop-height',
    category: 'sports',
    promptEs: 'A que altura esta el aro de basquetbol?',
    promptEn: 'How high is the basketball hoop?',
    optionsEs: ['2.75 metros', '3.05 metros', '3.50 metros', '4 metros'],
    optionsEn: ['2.75 meters', '3.05 meters', '3.50 meters', '4 meters'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3.05 metros', '3.05', 'tres punto cero cinco metros', '10 pies'],
    acceptedAnswersEn: ['3.05 meters', '3.05', 'ten feet', '10 feet'],
  },
  {
    id: 'sports-popular-basketball-shot-clock',
    category: 'sports',
    promptEs: 'Cuantos segundos tiene un equipo para lanzar en basquetbol profesional?',
    promptEn: 'How many seconds does a team have to shoot in professional basketball?',
    optionsEs: ['14 segundos', '20 segundos', '24 segundos', '30 segundos'],
    optionsEn: ['14 seconds', '20 seconds', '24 seconds', '30 seconds'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['24 segundos', 'veinticuatro segundos', '24'],
    acceptedAnswersEn: ['24 seconds', 'twenty four seconds', '24'],
  },
  {
    id: 'sports-popular-basketball-free-throw',
    category: 'sports',
    promptEs: 'Cuantos puntos vale un tiro libre en basquetbol?',
    promptEn: 'How many points is a free throw worth in basketball?',
    optionsEs: ['1 punto', '2 puntos', '3 puntos', '4 puntos'],
    optionsEn: ['1 point', '2 points', '3 points', '4 points'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['1 punto', 'un punto', '1'],
    acceptedAnswersEn: ['1 point', 'one point', '1'],
  },
  {
    id: 'sports-popular-basketball-three-pointer',
    category: 'sports',
    promptEs: 'Cuantos puntos vale un tiro anotado desde fuera de la linea de tres?',
    promptEn: 'How many points is a made shot from outside the three-point line worth?',
    optionsEs: ['1 punto', '2 puntos', '3 puntos', '4 puntos'],
    optionsEn: ['1 point', '2 points', '3 points', '4 points'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['3 puntos', 'tres puntos', '3'],
    acceptedAnswersEn: ['3 points', 'three points', '3'],
  },
  {
    id: 'sports-popular-tennis-deuce',
    category: 'sports',
    promptEs: 'En tenis, como se llama el marcador 40-40?',
    promptEn: 'In tennis, what is the score 40-40 called?',
    optionsEs: ['Deuce', 'Ace', 'Set point', 'Break'],
    optionsEn: ['Deuce', 'Ace', 'Set point', 'Break'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['deuce', 'iguales'],
    acceptedAnswersEn: ['deuce'],
  },
  {
    id: 'sports-popular-tennis-tiebreak',
    category: 'sports',
    promptEs: 'En tenis, a cuantos puntos se juega normalmente un tie-break?',
    promptEn: 'In tennis, how many points is a tie-break normally played to?',
    optionsEs: ['5 puntos', '7 puntos', '9 puntos', '11 puntos'],
    optionsEn: ['5 points', '7 points', '9 points', '11 points'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['7 puntos', 'siete puntos', '7'],
    acceptedAnswersEn: ['7 points', 'seven points', '7'],
  },
  {
    id: 'sports-popular-tennis-double-fault',
    category: 'sports',
    promptEs: 'En tenis, cuantas oportunidades de saque tiene un jugador antes de doble falta?',
    promptEn: 'In tennis, how many service attempts does a player have before a double fault?',
    optionsEs: ['1', '2', '3', '4'],
    optionsEn: ['1', '2', '3', '4'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['2', 'dos', 'dos saques'],
    acceptedAnswersEn: ['2', 'two', 'two serves'],
  },
  {
    id: 'sports-popular-baseball-innings',
    category: 'sports',
    promptEs: 'Cuantas entradas tiene normalmente un partido de beisbol profesional?',
    promptEn: 'How many innings does a professional baseball game normally have?',
    optionsEs: ['6', '7', '9', '12'],
    optionsEn: ['6', '7', '9', '12'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['9', 'nueve', 'nueve entradas'],
    acceptedAnswersEn: ['9', 'nine', 'nine innings'],
  },
  {
    id: 'sports-popular-baseball-outs',
    category: 'sports',
    promptEs: 'Cuantos outs necesita un equipo para terminar media entrada en beisbol?',
    promptEn: 'How many outs does a team need to end a half-inning in baseball?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres outs'],
    acceptedAnswersEn: ['3', 'three', 'three outs'],
  },
  {
    id: 'sports-popular-baseball-run-bases',
    category: 'sports',
    promptEs: 'Cuantas bases debe tocar un corredor para anotar una carrera en beisbol?',
    promptEn: 'How many bases must a runner touch to score a run in baseball?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['4', 'cuatro', 'cuatro bases'],
    acceptedAnswersEn: ['4', 'four', 'four bases'],
  },
  {
    id: 'sports-popular-volleyball-set-points',
    category: 'sports',
    promptEs: 'En voleibol indoor, a cuantos puntos se juegan normalmente los primeros sets?',
    promptEn: 'In indoor volleyball, how many points are the first sets normally played to?',
    optionsEs: ['15 puntos', '21 puntos', '25 puntos', '30 puntos'],
    optionsEn: ['15 points', '21 points', '25 points', '30 points'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['25 puntos', 'veinticinco puntos', '25'],
    acceptedAnswersEn: ['25 points', 'twenty five points', '25'],
  },
  {
    id: 'sports-popular-volleyball-three-touches',
    category: 'sports',
    promptEs: 'Cuantos toques puede hacer un equipo antes de devolver el balon en voleibol?',
    promptEn: 'How many touches can a team make before returning the ball in volleyball?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres toques'],
    acceptedAnswersEn: ['3', 'three', 'three touches'],
  },
  {
    id: 'sports-popular-american-football-touchdown',
    category: 'sports',
    promptEs: 'Cuantos puntos vale un touchdown en futbol americano?',
    promptEn: 'How many points is a touchdown worth in American football?',
    optionsEs: ['3 puntos', '6 puntos', '7 puntos', '10 puntos'],
    optionsEn: ['3 points', '6 points', '7 points', '10 points'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['6 puntos', 'seis puntos', '6'],
    acceptedAnswersEn: ['6 points', 'six points', '6'],
  },
  {
    id: 'sports-popular-american-football-first-down',
    category: 'sports',
    promptEs: 'Cuantas yardas debe avanzar un equipo para conseguir un primer down?',
    promptEn: 'How many yards must a team advance to get a first down?',
    optionsEs: ['5 yardas', '10 yardas', '15 yardas', '20 yardas'],
    optionsEn: ['5 yards', '10 yards', '15 yards', '20 yards'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['10 yardas', 'diez yardas', '10'],
    acceptedAnswersEn: ['10 yards', 'ten yards', '10'],
  },
  {
    id: 'sports-popular-ice-hockey-periods',
    category: 'sports',
    promptEs: 'Cuantos periodos tiene un partido de hockey sobre hielo?',
    promptEn: 'How many periods are in an ice hockey game?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres periodos'],
    acceptedAnswersEn: ['3', 'three', 'three periods'],
  },
  {
    id: 'sports-popular-ice-hockey-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores por equipo hay normalmente sobre el hielo, incluyendo portero?',
    promptEn: 'How many players per team are normally on the ice, including the goalie?',
    optionsEs: ['5', '6', '7', '8'],
    optionsEn: ['5', '6', '7', '8'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['6', 'seis'],
    acceptedAnswersEn: ['6', 'six'],
  },
  {
    id: 'sports-popular-golf-holes',
    category: 'sports',
    promptEs: 'Cuantos hoyos tiene normalmente una ronda completa de golf?',
    promptEn: 'How many holes are normally in a full round of golf?',
    optionsEs: ['9', '12', '18', '24'],
    optionsEn: ['9', '12', '18', '24'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['18', 'dieciocho', 'dieciocho hoyos'],
    acceptedAnswersEn: ['18', 'eighteen', 'eighteen holes'],
  },
  {
    id: 'sports-popular-boxing-olympic-rounds',
    category: 'sports',
    promptEs: 'Cuantos rounds tiene un combate de boxeo olimpico?',
    promptEn: 'How many rounds are in an Olympic boxing bout?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres rounds'],
    acceptedAnswersEn: ['3', 'three', 'three rounds'],
  },
  {
    id: 'sports-popular-boxing-round-duration',
    category: 'sports',
    promptEs: 'Cuanto dura cada round en boxeo olimpico?',
    promptEn: 'How long is each round in Olympic boxing?',
    optionsEs: ['2 minutos', '3 minutos', '4 minutos', '5 minutos'],
    optionsEn: ['2 minutes', '3 minutes', '4 minutes', '5 minutes'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3 minutos', 'tres minutos', '3'],
    acceptedAnswersEn: ['3 minutes', 'three minutes', '3'],
  },
  {
    id: 'sports-popular-mma-non-title-rounds',
    category: 'sports',
    promptEs: 'Cuantos rounds tiene normalmente una pelea de MMA que no es por titulo?',
    promptEn: 'How many rounds are normally in a non-title MMA fight?',
    optionsEs: ['2', '3', '5', '7'],
    optionsEn: ['2', '3', '5', '7'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['3', 'tres', 'tres rounds'],
    acceptedAnswersEn: ['3', 'three', 'three rounds'],
  },
  {
    id: 'sports-popular-swimming-olympic-pool',
    category: 'sports',
    promptEs: 'Cuantos metros mide una piscina olimpica de largo?',
    promptEn: 'How many meters long is an Olympic swimming pool?',
    optionsEs: ['25 metros', '33 metros', '50 metros', '100 metros'],
    optionsEn: ['25 meters', '33 meters', '50 meters', '100 meters'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['50 metros', 'cincuenta metros', '50'],
    acceptedAnswersEn: ['50 meters', 'fifty meters', '50'],
  },
  {
    id: 'sports-popular-swimming-medley-order',
    category: 'sports',
    promptEs: 'Selecciona el orden correcto del combinado individual en natacion.',
    promptEn: 'Select the correct order of the individual medley in swimming.',
    optionsEs: ['Mariposa, espalda, pecho, libre', 'Libre, pecho, espalda, mariposa', 'Espalda, libre, pecho, mariposa', 'Pecho, mariposa, libre, espalda'],
    optionsEn: ['Butterfly, backstroke, breaststroke, freestyle', 'Freestyle, breaststroke, backstroke, butterfly', 'Backstroke, freestyle, breaststroke, butterfly', 'Breaststroke, butterfly, freestyle, backstroke'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['mariposa espalda pecho libre', 'mariposa espalda pecho estilo libre'],
    acceptedAnswersEn: ['butterfly backstroke breaststroke freestyle'],
  },
  {
    id: 'sports-popular-athletics-400m-lap',
    category: 'sports',
    promptEs: 'En una pista atletica estandar, cuantos metros tiene una vuelta completa?',
    promptEn: 'On a standard athletics track, how many meters is one full lap?',
    optionsEs: ['100 metros', '200 metros', '400 metros', '800 metros'],
    optionsEn: ['100 meters', '200 meters', '400 meters', '800 meters'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['400 metros', 'cuatrocientos metros', '400'],
    acceptedAnswersEn: ['400 meters', 'four hundred meters', '400'],
  },
  {
    id: 'sports-popular-athletics-4x100-relay',
    category: 'sports',
    promptEs: 'Cuantos corredores tiene un equipo en el relevo 4x100 metros?',
    promptEn: 'How many runners are on a team in the 4x100 meters relay?',
    optionsEs: ['2', '3', '4', '5'],
    optionsEn: ['2', '3', '4', '5'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['4', 'cuatro', 'cuatro corredores'],
    acceptedAnswersEn: ['4', 'four', 'four runners'],
  },
  {
    id: 'sports-popular-cycling-yellow-jersey',
    category: 'sports',
    promptEs: 'En el Tour de Francia, quien usa el maillot amarillo?',
    promptEn: 'In the Tour de France, who wears the yellow jersey?',
    optionsEs: ['Lider de la clasificacion general', 'Mejor escalador', 'Mejor sprinter', 'Ultimo corredor'],
    optionsEn: ['Leader of the general classification', 'Best climber', 'Best sprinter', 'Last rider'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['lider de la clasificacion general', 'lider general', 'clasificacion general'],
    acceptedAnswersEn: ['leader of the general classification', 'general classification leader', 'overall leader'],
  },
  {
    id: 'sports-popular-cricket-players',
    category: 'sports',
    promptEs: 'Cuantos jugadores tiene cada equipo en cricket?',
    promptEn: 'How many players are on each team in cricket?',
    optionsEs: ['9', '10', '11', '12'],
    optionsEn: ['9', '10', '11', '12'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['11', 'once'],
    acceptedAnswersEn: ['11', 'eleven'],
  },

  {
    id: 'sports-football-yellow-card-caution',
    category: 'sports',
    promptEs: 'Que comunica una tarjeta amarilla en futbol?',
    promptEn: 'What does a yellow card communicate in football/soccer?',
    optionsEs: ['Amonestacion', 'Expulsion inmediata', 'Gol valido', 'Cambio obligatorio'],
    optionsEn: ['Caution', 'Immediate sending-off', 'Valid goal', 'Mandatory substitution'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['amonestacion', 'advertencia', 'tarjeta amarilla'],
    acceptedAnswersEn: ['caution', 'warning', 'yellow card'],
  },
  {
    id: 'sports-football-second-yellow-card',
    category: 'sports',
    promptEs: 'Que pasa si un jugador recibe una segunda tarjeta amarilla en el mismo partido?',
    promptEn: 'What happens if a player receives a second yellow card in the same match?',
    optionsEs: ['Es expulsado', 'Lanza un penal', 'Sigue jugando sin sancion', 'Su equipo gana un tiro de esquina'],
    optionsEn: ['He is sent off', 'He takes a penalty', 'He keeps playing with no sanction', 'His team gets a corner kick'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['es expulsado', 'expulsado', 'segunda amarilla roja'],
    acceptedAnswersEn: ['he is sent off', 'sent off', 'second yellow red card'],
  },
  {
    id: 'sports-football-free-kick-wall-distance',
    category: 'sports',
    promptEs: 'A que distancia minima deben estar los rivales en un tiro libre?',
    promptEn: 'What minimum distance must opponents keep at a free kick?',
    optionsEs: ['5 metros', '7.32 metros', '9.15 metros', '11 metros'],
    optionsEn: ['5 meters', '7.32 meters', '9.15 meters', '11 meters'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['9.15 metros', 'nueve punto quince metros', '10 yardas'],
    acceptedAnswersEn: ['9.15 meters', 'nine point fifteen meters', '10 yards'],
  },
  {
    id: 'sports-football-direct-free-kick-goal',
    category: 'sports',
    promptEs: 'En futbol, desde cual tiro libre se puede anotar directamente en la porteria rival?',
    promptEn: 'In football/soccer, from which free kick can a goal be scored directly against the opposing team?',
    optionsEs: ['Tiro libre directo', 'Tiro libre indirecto', 'Saque de banda', 'Balon a tierra'],
    optionsEn: ['Direct free kick', 'Indirect free kick', 'Throw-in', 'Dropped ball'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['tiro libre directo', 'directo'],
    acceptedAnswersEn: ['direct free kick', 'direct'],
  },
  {
    id: 'sports-football-indirect-free-kick-signal',
    category: 'sports',
    promptEs: 'Como senala el arbitro un tiro libre indirecto?',
    promptEn: 'How does the referee signal an indirect free kick?',
    optionsEs: ['Levanta el brazo sobre la cabeza', 'Tira una moneda', 'Muestra tarjeta roja', 'Se sienta en el centro'],
    optionsEn: ['Raises an arm above the head', 'Tosses a coin', 'Shows a red card', 'Sits in the center'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['levanta el brazo', 'brazo sobre la cabeza', 'brazo arriba'],
    acceptedAnswersEn: ['raises an arm', 'arm above the head', 'arm up'],
  },
  {
    id: 'sports-football-kickoff-opponent-distance',
    category: 'sports',
    promptEs: 'En un saque inicial, a que distancia minima deben estar los rivales del balon?',
    promptEn: 'At a kick-off, what minimum distance must opponents keep from the ball?',
    optionsEs: ['2 metros', '5 metros', '9.15 metros', '16.5 metros'],
    optionsEn: ['2 meters', '5 meters', '9.15 meters', '16.5 meters'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['9.15 metros', 'nueve punto quince metros', '10 yardas'],
    acceptedAnswersEn: ['9.15 meters', 'nine point fifteen meters', '10 yards'],
  },
  {
    id: 'sports-football-kickoff-direct-goal',
    category: 'sports',
    promptEs: 'Se puede marcar gol directamente desde el saque inicial?',
    promptEn: 'Can a goal be scored directly from a kick-off?',
    optionsEs: ['Si, contra el equipo rival', 'No, nunca', 'Solo si toca al arbitro', 'Solo con la cabeza'],
    optionsEn: ['Yes, against the opposing team', 'No, never', 'Only if it touches the referee', 'Only with the head'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['si contra el rival', 'si', 'gol directo de saque inicial'],
    acceptedAnswersEn: ['yes against the opposing team', 'yes', 'direct goal from kick off'],
  },
  {
    id: 'sports-football-ball-out-of-play',
    category: 'sports',
    promptEs: 'Cuando esta el balon fuera de juego en futbol?',
    promptEn: 'When is the ball out of play in football/soccer?',
    optionsEs: ['Cuando cruza completamente la linea de banda o de meta', 'Cuando toca el poste y sigue dentro', 'Cuando el portero la atrapa', 'Cuando un jugador la pasa hacia atras'],
    optionsEn: ['When it completely crosses the touchline or goal line', 'When it hits the post and stays in', 'When the goalkeeper catches it', 'When a player passes it backward'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['cruza completamente la linea', 'sale completamente', 'pasa totalmente la linea'],
    acceptedAnswersEn: ['completely crosses the line', 'wholly passes over the line', 'fully crosses the line'],
  },
  {
    id: 'sports-football-throw-in-award',
    category: 'sports',
    promptEs: 'Cuando se concede un saque de banda?',
    promptEn: 'When is a throw-in awarded?',
    optionsEs: ['Cuando el balon cruza completamente la linea de banda', 'Cuando hay gol', 'Cuando hay fuera de juego', 'Cuando el portero ataja'],
    optionsEn: ['When the ball completely crosses the touchline', 'When there is a goal', 'When there is offside', 'When the goalkeeper saves'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['cuando cruza la linea de banda', 'sale por banda', 'balon fuera por banda'],
    acceptedAnswersEn: ['when it crosses the touchline', 'out over the touchline', 'throw in'],
  },
  {
    id: 'sports-football-throw-in-procedure',
    category: 'sports',
    promptEs: 'Como debe sacarse correctamente un saque de banda?',
    promptEn: 'How must a throw-in be taken correctly?',
    optionsEs: ['Con ambas manos desde detras y por encima de la cabeza', 'Con un pie desde el punto penal', 'Con una mano desde el centro', 'Con el hombro desde la banda'],
    optionsEn: ['With both hands from behind and over the head', 'With one foot from the penalty mark', 'With one hand from the center', 'With the shoulder from the touchline'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['ambas manos sobre la cabeza', 'dos manos por encima de la cabeza', 'desde detras y sobre la cabeza'],
    acceptedAnswersEn: ['both hands over the head', 'two hands over the head', 'from behind and over the head'],
  },
  {
    id: 'sports-football-throw-in-direct-goal',
    category: 'sports',
    promptEs: 'Que pasa si el balon entra directamente en la porteria rival desde un saque de banda?',
    promptEn: 'What happens if the ball goes directly into the opposing goal from a throw-in?',
    optionsEs: ['Se concede saque de meta', 'Se concede gol', 'Se concede penal', 'Se repite el saque de banda'],
    optionsEn: ['A goal kick is awarded', 'A goal is awarded', 'A penalty kick is awarded', 'The throw-in is retaken'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['saque de meta', 'se concede saque de meta', 'no es gol'],
    acceptedAnswersEn: ['goal kick', 'a goal kick is awarded', 'not a goal'],
  },
  {
    id: 'sports-football-goal-kick-award',
    category: 'sports',
    promptEs: 'Cuando se concede un saque de meta?',
    promptEn: 'When is a goal kick awarded?',
    optionsEs: ['Cuando el atacante toca ultimo el balon y este cruza la linea de meta sin gol', 'Cuando el defensor toca ultimo el balon y este cruza la linea de meta sin gol', 'Cuando hay una falta dentro del circulo central', 'Cuando el balon toca al arbitro'],
    optionsEn: ['When an attacker last touches the ball and it crosses the goal line without a goal', 'When a defender last touches the ball and it crosses the goal line without a goal', 'When there is a foul inside the center circle', 'When the ball touches the referee'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['atacante toca ultimo y sale por linea de meta', 'ultimo toque del atacante', 'saque de meta'],
    acceptedAnswersEn: ['attacker last touched it over the goal line', 'last touch by attacking team', 'goal kick'],
  },
  {
    id: 'sports-football-goal-kick-direct-goal',
    category: 'sports',
    promptEs: 'Se puede anotar directamente desde un saque de meta contra el equipo rival?',
    promptEn: 'Can a goal be scored directly from a goal kick against the opposing team?',
    optionsEs: ['Si', 'No', 'Solo en penales', 'Solo si toca al arbitro'],
    optionsEn: ['Yes', 'No', 'Only in penalties', 'Only if it touches the referee'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['si', 'si se puede', 'gol directo de saque de meta'],
    acceptedAnswersEn: ['yes', 'yes it can', 'direct goal from goal kick'],
  },
  {
    id: 'sports-football-corner-kick-award',
    category: 'sports',
    promptEs: 'Cuando se concede un tiro de esquina?',
    promptEn: 'When is a corner kick awarded?',
    optionsEs: ['Cuando el defensor toca ultimo el balon y este cruza la linea de meta sin gol', 'Cuando el atacante toca ultimo el balon y este cruza la linea de meta sin gol', 'Cuando el balon sale por la linea de banda', 'Cuando hay saque inicial'],
    optionsEn: ['When a defender last touches the ball and it crosses the goal line without a goal', 'When an attacker last touches the ball and it crosses the goal line without a goal', 'When the ball crosses the touchline', 'When there is a kick-off'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['defensor toca ultimo y sale por linea de meta', 'ultimo toque del defensor', 'tiro de esquina', 'corner'],
    acceptedAnswersEn: ['defender last touched it over the goal line', 'last touch by defending team', 'corner kick', 'corner'],
  },
  {
    id: 'sports-football-corner-flagpost',
    category: 'sports',
    promptEs: 'Durante un tiro de esquina, se puede mover el banderin de esquina?',
    promptEn: 'During a corner kick, can the corner flagpost be moved?',
    optionsEs: ['No', 'Si', 'Solo el portero', 'Solo en tiempo extra'],
    optionsEn: ['No', 'Yes', 'Only the goalkeeper can', 'Only in extra time'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['no', 'no se puede mover', 'el banderin no se mueve'],
    acceptedAnswersEn: ['no', 'cannot be moved', 'the flagpost cannot be moved'],
  },
  {
    id: 'sports-football-offside-position-alone',
    category: 'sports',
    promptEs: 'Estar en posicion de fuera de juego por si solo es una infraccion?',
    promptEn: 'Is being in an offside position by itself an offence?',
    optionsEs: ['No', 'Si', 'Solo si es el portero', 'Solo en el primer tiempo'],
    optionsEn: ['No', 'Yes', 'Only for the goalkeeper', 'Only in the first half'],
    correctOptionIndexes: [0],
    acceptedAnswersEs: ['no', 'no es infraccion', 'no por si solo'],
    acceptedAnswersEn: ['no', 'not an offence', 'not by itself'],
  },
  {
    id: 'sports-football-no-offside-restarts',
    category: 'sports',
    promptEs: 'Selecciona jugadas desde las que no hay fuera de juego si se recibe el balon directamente.',
    promptEn: 'Select restarts from which there is no offside offence if the ball is received directly.',
    optionsEs: ['Saque de meta', 'Saque de banda', 'Tiro de esquina', 'Tiro penal'],
    optionsEn: ['Goal kick', 'Throw-in', 'Corner kick', 'Penalty kick'],
    correctOptionIndexes: [0, 1, 2],
    acceptedAnswersEs: ['saque de meta saque de banda tiro de esquina', 'saque de meta saque de banda corner'],
    acceptedAnswersEn: ['goal kick throw in corner kick', 'goal kick throw-in corner kick'],
  },
  {
    id: 'sports-football-minimum-players',
    category: 'sports',
    promptEs: 'Cual es el minimo de jugadores que debe tener un equipo para iniciar o continuar un partido?',
    promptEn: 'What is the minimum number of players a team must have to start or continue a match?',
    optionsEs: ['5', '6', '7', '8'],
    optionsEn: ['5', '6', '7', '8'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['7', 'siete'],
    acceptedAnswersEn: ['7', 'seven'],
  },
  {
    id: 'sports-football-halftime-interval',
    category: 'sports',
    promptEs: 'Cual es la duracion maxima del descanso de medio tiempo en futbol?',
    promptEn: 'What is the maximum duration of the half-time interval in football/soccer?',
    optionsEs: ['10 minutos', '15 minutos', '20 minutos', '30 minutos'],
    optionsEn: ['10 minutes', '15 minutes', '20 minutes', '30 minutes'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['15 minutos', 'quince minutos', '15'],
    acceptedAnswersEn: ['15 minutes', 'fifteen minutes', '15'],
  },
  {
    id: 'sports-football-goal-height',
    category: 'sports',
    promptEs: 'A que altura esta el travesano de una porteria de futbol reglamentaria?',
    promptEn: 'How high is the crossbar of a regulation football/soccer goal?',
    optionsEs: ['2.00 metros', '2.44 metros', '3.05 metros', '4.00 metros'],
    optionsEn: ['2.00 meters', '2.44 meters', '3.05 meters', '4.00 meters'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['2.44 metros', 'dos punto cuarenta y cuatro metros', '8 pies'],
    acceptedAnswersEn: ['2.44 meters', 'two point forty four meters', '8 feet'],
  },

  {
    id: 'sports-football-history-first-world-cup-host',
    category: 'sports',
    promptEs: 'Que pais fue sede de la primera Copa Mundial de futbol masculino?',
    promptEn: 'Which country hosted the first men\'s FIFA World Cup?',
    optionsEs: ['Brasil', 'Italia', 'Uruguay', 'Argentina'],
    optionsEn: ['Brazil', 'Italy', 'Uruguay', 'Argentina'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['uruguay'],
    acceptedAnswersEn: ['uruguay'],
  },
  {
    id: 'sports-football-history-first-world-cup-champion',
    category: 'sports',
    promptEs: 'Que seleccion gano la primera Copa Mundial de futbol masculino en 1930?',
    promptEn: 'Which national team won the first men\'s FIFA World Cup in 1930?',
    optionsEs: ['Argentina', 'Uruguay', 'Brasil', 'Francia'],
    optionsEn: ['Argentina', 'Uruguay', 'Brazil', 'France'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['uruguay'],
    acceptedAnswersEn: ['uruguay'],
  },
  {
    id: 'sports-football-history-maracanazo',
    category: 'sports',
    promptEs: 'Que seleccion vencio a Brasil en el famoso Maracanazo de 1950?',
    promptEn: 'Which national team defeated Brazil in the famous 1950 Maracanazo?',
    optionsEs: ['Argentina', 'Italia', 'Alemania', 'Uruguay'],
    optionsEn: ['Argentina', 'Italy', 'Germany', 'Uruguay'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['uruguay'],
    acceptedAnswersEn: ['uruguay'],
  },
  {
    id: 'sports-football-history-world-cup-2022-champion',
    category: 'sports',
    promptEs: 'Que seleccion gano la Copa Mundial de futbol masculino 2022?',
    promptEn: 'Which national team won the 2022 men\'s FIFA World Cup?',
    optionsEs: ['Francia', 'Brasil', 'Argentina', 'Croacia'],
    optionsEn: ['France', 'Brazil', 'Argentina', 'Croatia'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['argentina'],
    acceptedAnswersEn: ['argentina'],
  },
  {
    id: 'sports-football-history-world-cup-2022-final-rival',
    category: 'sports',
    promptEs: 'Contra que seleccion jugo Argentina la final del Mundial 2022?',
    promptEn: 'Which national team did Argentina play against in the 2022 World Cup final?',
    optionsEs: ['Brasil', 'Francia', 'Croacia', 'Marruecos'],
    optionsEn: ['Brazil', 'France', 'Croatia', 'Morocco'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['francia'],
    acceptedAnswersEn: ['france'],
  },
  {
    id: 'sports-football-history-world-cup-2018-champion',
    category: 'sports',
    promptEs: 'Que seleccion gano la Copa Mundial de futbol masculino 2018?',
    promptEn: 'Which national team won the 2018 men\'s FIFA World Cup?',
    optionsEs: ['Croacia', 'Belgica', 'Inglaterra', 'Francia'],
    optionsEn: ['Croatia', 'Belgium', 'England', 'France'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['francia'],
    acceptedAnswersEn: ['france'],
  },
  {
    id: 'sports-football-history-world-cup-2014-champion',
    category: 'sports',
    promptEs: 'Que seleccion gano la Copa Mundial de futbol masculino 2014?',
    promptEn: 'Which national team won the 2014 men\'s FIFA World Cup?',
    optionsEs: ['Argentina', 'Alemania', 'Brasil', 'Paises Bajos'],
    optionsEn: ['Argentina', 'Germany', 'Brazil', 'Netherlands'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['alemania'],
    acceptedAnswersEn: ['germany'],
  },
  {
    id: 'sports-football-history-morocco-2022',
    category: 'sports',
    promptEs: 'Que seleccion africana llego por primera vez a semifinales de un Mundial en 2022?',
    promptEn: 'Which African national team reached a World Cup semi-final for the first time in 2022?',
    optionsEs: ['Ghana', 'Senegal', 'Marruecos', 'Camerun'],
    optionsEn: ['Ghana', 'Senegal', 'Morocco', 'Cameroon'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['marruecos', 'morocco'],
    acceptedAnswersEn: ['morocco'],
  },
  {
    id: 'sports-football-history-euro-2024-champion',
    category: 'sports',
    promptEs: 'Que seleccion gano la Eurocopa 2024?',
    promptEn: 'Which national team won UEFA EURO 2024?',
    optionsEs: ['Inglaterra', 'Francia', 'Alemania', 'Espana'],
    optionsEn: ['England', 'France', 'Germany', 'Spain'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['espana', 'españa'],
    acceptedAnswersEn: ['spain'],
  },
  {
    id: 'sports-football-history-copa-america-2024-champion',
    category: 'sports',
    promptEs: 'Que seleccion gano la Copa America 2024?',
    promptEn: 'Which national team won the 2024 Copa America?',
    optionsEs: ['Colombia', 'Argentina', 'Uruguay', 'Brasil'],
    optionsEn: ['Colombia', 'Argentina', 'Uruguay', 'Brazil'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['argentina'],
    acceptedAnswersEn: ['argentina'],
  },
  {
    id: 'sports-football-history-womens-world-cup-2023',
    category: 'sports',
    promptEs: 'Que seleccion gano la Copa Mundial Femenina de la FIFA 2023?',
    promptEn: 'Which national team won the 2023 FIFA Women\'s World Cup?',
    optionsEs: ['Inglaterra', 'Estados Unidos', 'Espana', 'Suecia'],
    optionsEn: ['England', 'United States', 'Spain', 'Sweden'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['espana', 'españa'],
    acceptedAnswersEn: ['spain'],
  },
  {
    id: 'sports-football-history-real-madrid-la-decima',
    category: 'sports',
    promptEs: 'Que club gano la famosa Decima Champions League en 2014?',
    promptEn: 'Which club won the famous La Decima Champions League title in 2014?',
    optionsEs: ['Barcelona', 'Bayern Munich', 'Liverpool', 'Real Madrid'],
    optionsEn: ['Barcelona', 'Bayern Munich', 'Liverpool', 'Real Madrid'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['real madrid'],
    acceptedAnswersEn: ['real madrid'],
  },
  {
    id: 'sports-football-history-2014-champions-final-rival',
    category: 'sports',
    promptEs: 'A que rival vencio Real Madrid en la final de la Champions League 2014?',
    promptEn: 'Which rival did Real Madrid defeat in the 2014 Champions League final?',
    optionsEs: ['Barcelona', 'Bayern Munich', 'Atletico de Madrid', 'Juventus'],
    optionsEn: ['Barcelona', 'Bayern Munich', 'Atletico Madrid', 'Juventus'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['atletico de madrid', 'atletico madrid'],
    acceptedAnswersEn: ['atletico madrid'],
  },
  {
    id: 'sports-football-history-miracle-of-istanbul',
    category: 'sports',
    promptEs: 'Que club protagonizo el Milagro de Estambul en la final de Champions League 2005?',
    promptEn: 'Which club produced the Miracle of Istanbul in the 2005 Champions League final?',
    optionsEs: ['AC Milan', 'Liverpool', 'Chelsea', 'Manchester United'],
    optionsEn: ['AC Milan', 'Liverpool', 'Chelsea', 'Manchester United'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['liverpool'],
    acceptedAnswersEn: ['liverpool'],
  },
  {
    id: 'sports-football-history-man-united-1999-final',
    category: 'sports',
    promptEs: 'Que club gano la final de Champions League 1999 con dos goles en tiempo agregado?',
    promptEn: 'Which club won the 1999 Champions League final with two stoppage-time goals?',
    optionsEs: ['Bayern Munich', 'Real Madrid', 'Manchester United', 'Juventus'],
    optionsEn: ['Bayern Munich', 'Real Madrid', 'Manchester United', 'Juventus'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['manchester united', 'man united'],
    acceptedAnswersEn: ['manchester united', 'man united'],
  },
  {
    id: 'sports-football-history-arsenal-invincibles-season',
    category: 'sports',
    promptEs: 'En que temporada Arsenal fue campeon invicto de la Premier League?',
    promptEn: 'In which season did Arsenal win the Premier League unbeaten?',
    optionsEs: ['1998-99', '2011-12', '2015-16', '2003-04'],
    optionsEn: ['1998-99', '2011-12', '2015-16', '2003-04'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['2003-04', '2003 04', 'temporada 2003-04'],
    acceptedAnswersEn: ['2003-04', '2003 04', '2003-2004 season'],
  },
  {
    id: 'sports-football-history-barcelona-sextuple-2009',
    category: 'sports',
    promptEs: 'Que club gano seis titulos en el ano calendario 2009?',
    promptEn: 'Which club won six trophies in the 2009 calendar year?',
    optionsEs: ['Real Madrid', 'Barcelona', 'Inter de Milan', 'Bayern Munich'],
    optionsEn: ['Real Madrid', 'Barcelona', 'Inter Milan', 'Bayern Munich'],
    correctOptionIndexes: [1],
    acceptedAnswersEs: ['barcelona', 'fc barcelona', 'barca'],
    acceptedAnswersEn: ['barcelona', 'fc barcelona', 'barca'],
  },
  {
    id: 'sports-football-history-superclasico-teams',
    category: 'sports',
    promptEs: 'Selecciona los equipos que juegan el Superclasico argentino.',
    promptEn: 'Select the teams that play the Argentine Superclasico.',
    optionsEs: ['Independiente', 'Boca Juniors', 'Racing Club', 'River Plate'],
    optionsEn: ['Independiente', 'Boca Juniors', 'Racing Club', 'River Plate'],
    correctOptionIndexes: [1, 3],
    acceptedAnswersEs: ['boca juniors river plate', 'boca river', 'river boca'],
    acceptedAnswersEn: ['boca juniors river plate', 'boca river', 'river boca'],
  },
  {
    id: 'sports-football-history-la-bombonera-club',
    category: 'sports',
    promptEs: 'De que club es estadio La Bombonera?',
    promptEn: 'Which club plays at La Bombonera?',
    optionsEs: ['River Plate', 'San Lorenzo', 'Boca Juniors', 'Velez Sarsfield'],
    optionsEn: ['River Plate', 'San Lorenzo', 'Boca Juniors', 'Velez Sarsfield'],
    correctOptionIndexes: [2],
    acceptedAnswersEs: ['boca juniors', 'boca'],
    acceptedAnswersEn: ['boca juniors', 'boca'],
  },
  {
    id: 'sports-football-history-libertadores-most-titles',
    category: 'sports',
    promptEs: 'Que club argentino es el maximo ganador historico de la Copa Libertadores?',
    promptEn: 'Which Argentine club is the all-time top winner of the Copa Libertadores?',
    optionsEs: ['Boca Juniors', 'River Plate', 'Estudiantes', 'Independiente'],
    optionsEn: ['Boca Juniors', 'River Plate', 'Estudiantes', 'Independiente'],
    correctOptionIndexes: [3],
    acceptedAnswersEs: ['independiente', 'independiente de avellaneda'],
    acceptedAnswersEn: ['independiente'],
  },

];
