import { RecognizableObjectSeed } from '../types/objectRecognition.types';

export const OBJECT_BANK_SEED: RecognizableObjectSeed[] = [
  {
    id: 'bottle',
    name: 'bottle',
    label: 'Botella',
    modelLabel: 'BOTTLE',
    minConfidence: 0.5,
    category: 'home',
  },
  {
    id: 'book',
    name: 'book',
    label: 'Libro',
    modelLabel: 'BOOK',
    minConfidence: 0.45,
    category: 'school',
  },
  {
    id: 'notebook',
    name: 'notebook',
    label: 'Cuaderno',
    modelLabel: 'BOOK',
    minConfidence: 0.45,
    category: 'school',
  },
  {
    id: 'keys',
    name: 'keys',
    label: 'Llaves',
    modelLabel: '',
    minConfidence: 0.5,
    category: 'personal',
    enabled: false,
  },
  {
    id: 'cup',
    name: 'cup',
    label: 'Taza',
    modelLabel: 'CUP',
    minConfidence: 0.5,
    category: 'kitchen',
  },
  {
    id: 'shoe',
    name: 'shoe',
    label: 'Zapato',
    modelLabel: '',
    minConfidence: 0.5,
    category: 'personal',
    enabled: false,
  },
  {
    id: 'toothbrush',
    name: 'toothbrush',
    label: 'Cepillo de dientes',
    modelLabel: 'TOOTHBRUSH',
    minConfidence: 0.4,
    category: 'bathroom',
  },
  {
    id: 'spoon',
    name: 'spoon',
    label: 'Cuchara',
    modelLabel: 'SPOON',
    minConfidence: 0.4,
    category: 'kitchen',
  },
  {
    id: 'pen',
    name: 'pen',
    label: 'Lapicero',
    modelLabel: '',
    minConfidence: 0.5,
    category: 'school',
    enabled: false,
  },
  {
    id: 'backpack',
    name: 'backpack',
    label: 'Mochila',
    modelLabel: 'BACKPACK',
    minConfidence: 0.5,
    category: 'school',
  },
  {
    id: 'cell-phone',
    name: 'cell_phone',
    label: 'Celular',
    modelLabel: 'CELL_PHONE',
    minConfidence: 0.45,
    category: 'personal',
  },
  {
    id: 'laptop',
    name: 'laptop',
    label: 'Laptop',
    modelLabel: 'LAPTOP',
    minConfidence: 0.5,
    category: 'school',
  },
  {
    id: 'keyboard',
    name: 'keyboard',
    label: 'Teclado',
    modelLabel: 'KEYBOARD',
    minConfidence: 0.5,
    category: 'school',
  },
  {
    id: 'mouse',
    name: 'mouse',
    label: 'Mouse',
    modelLabel: 'MOUSE',
    minConfidence: 0.45,
    category: 'school',
  },
  {
    id: 'remote',
    name: 'remote',
    label: 'Control remoto',
    modelLabel: 'REMOTE',
    minConfidence: 0.45,
    category: 'home',
  },
  {
    id: 'clock',
    name: 'clock',
    label: 'Reloj',
    modelLabel: 'CLOCK',
    minConfidence: 0.45,
    category: 'home',
  },
  {
    id: 'chair',
    name: 'chair',
    label: 'Silla',
    modelLabel: 'CHAIR',
    minConfidence: 0.55,
    category: 'home',
  },
  {
    id: 'bowl',
    name: 'bowl',
    label: 'Bol',
    modelLabel: 'BOWL',
    minConfidence: 0.5,
    category: 'kitchen',
  },
  {
    id: 'apple',
    name: 'apple',
    label: 'Manzana',
    modelLabel: 'APPLE',
    minConfidence: 0.45,
    category: 'kitchen',
  },
  {
    id: 'banana',
    name: 'banana',
    label: 'Banana',
    modelLabel: 'BANANA',
    minConfidence: 0.45,
    category: 'kitchen',
  },
];
