import { RecognizableObjectSeed } from '../types/objectRecognition.types';

export const OBJECT_BANK_SEED: RecognizableObjectSeed[] = [
  {
    id: 'bottle',
    name: 'bottle',
    label: 'Botella',
    modelLabel: 'BOTTLE',
    category: 'home',
  },
  {
    id: 'book',
    name: 'book',
    label: 'Libro',
    modelLabel: 'BOOK',
    category: 'school',
  },
  {
    id: 'notebook',
    name: 'notebook',
    label: 'Cuaderno',
    modelLabel: 'BOOK',
    category: 'school',
  },
  {
    id: 'keys',
    name: 'keys',
    label: 'Llaves',
    modelLabel: '',
    category: 'personal',
    enabled: false,
  },
  {
    id: 'cup',
    name: 'cup',
    label: 'Taza',
    modelLabel: 'CUP',
    category: 'kitchen',
  },
  {
    id: 'shoe',
    name: 'shoe',
    label: 'Zapato',
    modelLabel: 'SHOE',
    category: 'personal',
  },
  {
    id: 'toothbrush',
    name: 'toothbrush',
    label: 'Cepillo de dientes',
    modelLabel: 'TOOTHBRUSH',
    category: 'bathroom',
  },
  {
    id: 'spoon',
    name: 'spoon',
    label: 'Cuchara',
    modelLabel: 'SPOON',
    category: 'kitchen',
  },
  {
    id: 'pen',
    name: 'pen',
    label: 'Lapicero',
    modelLabel: '',
    category: 'school',
    enabled: false,
  },
  {
    id: 'backpack',
    name: 'backpack',
    label: 'Mochila',
    modelLabel: 'BACKPACK',
    category: 'school',
  },
];
